import test from'node:test';import assert from'node:assert/strict';import{adapters}from'../src/adapters/index.js';
import{Store}from'../src/db.js';import{ExperimentHarness}from'../src/experiments.js';
const A=adapters();
test('MedMemory formal observations exclude knowledge points and queries',()=>{const x=A.medmemorybench.load({persona_id:1,max_session:1});const raw=JSON.stringify(x.observations);assert.ok(x.observations.length);assert.equal(raw.includes('knowledge_points'),false);assert.equal(raw.includes('source_key_points'),false);assert.ok(x.sessions[0].knowledge_points_reference)});
test('MedLoCoMo formal QA excludes summaries',()=>{const x=A.medlocomo.load({patient_id:'16957952',max_admission:1});const raw=JSON.stringify(x.observations);assert.ok(x.observations.length);assert.equal(raw.includes('patient_summary'),false);assert.equal(raw.includes('previous_admission_summary'),false);assert.ok(x.inspection_only)});
test('MusPsy Task 3 exposes Last Memory only as Derived protocol context',()=>{let x;for(let i=0;i<50;i++){const v=A.muspsy.load({task:3,index:i});if(v.protocol_input.last_memory&&!/Last Memory:\s*None/i.test(v.protocol_input.last_memory.text)){x=v;break}}x=x||A.muspsy.load({task:3,index:0});assert.equal(x.protocol_input.last_memory.source_type,'derived');assert.equal(x.protocol_input.last_memory.not_patient_quote,true);assert.equal(JSON.stringify(x.observations).includes('Last Memory'),false)});
test('PsychEval official input is only client_info and current dialogue',()=>{const x=A.psycheval.load({therapy:'cbt',case_id:1,session:1,mode:'official_session'});assert.deepEqual(Object.keys(x.official_evaluator_input).sort(),['client_info','session_dialogue']);assert.equal(x.rollout_context,null);assert.equal(JSON.stringify(x.official_evaluator_input).includes('client_info_last'),false)});
test('query, gold, answer options and judge score cannot become core observations',()=>{const adapter=A.medmemorybench;for(const key of ['query','gold','answer_options','judge_score'])assert.throws(()=>adapter.assertCoreObservation({metadata:{[key]:'leak'}}),/leakage/)});
test('background experiment jobs preserve completed progress across pause/resume controls',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),x=h.launch('muspsy',{task:3,index:0,max_observations:8});let active=false;try{h.control(x.id,'pause');active=true;assert.equal(h.get(x.id).status,'paused');h.control(x.id,'resume');assert.equal(h.get(x.id).status,'running');}catch(e){assert.match(e.message,/not active/)}for(let i=0;i<100&&['running','paused'].includes(h.get(x.id).status);i++)await new Promise(r=>setTimeout(r,10));const done=h.get(x.id);assert.equal(done.progress.completed+done.progress.failed,done.progress.total);assert.ok(['completed','partial','failed'].includes(done.status));s.close()});
