import test from'node:test';import assert from'node:assert/strict';import{adapters}from'../src/adapters/index.js';
import{Store}from'../src/db.js';import{ExperimentHarness,MEMORY_PIPELINE_VERSION}from'../src/experiments.js';
import{medMemorySubjectId}from'../src/adapters/medmemory.js';
const A=adapters(),CLEAN_MEMORY=medMemorySubjectId(1,false),NOISE_MEMORY=medMemorySubjectId(1,true);
test('memory checkpoint compatibility contract is Patient Graph v13',()=>assert.equal(MEMORY_PIPELINE_VERSION,'patient-graph-memory-v13'));
test('experiment summaries and views omit heavy traces until one score is requested',()=>{const store=new Store(':memory:'),harness=new ExperimentHarness(store),now=new Date().toISOString(),insert=store.db.prepare(`INSERT INTO experiments(id,benchmark,status,config_json,progress_json,results_json,version_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`),score={kind:'score',score_id:'large-score',task:'adversarial',status:'scored',question:'Q',system_output:'A',gold:['A'],score:1,is_correct:true,retrieval_context:{large_trace:'must-not-be-returned-in-view'}};insert.run('medlocomo-summary','medlocomo','completed',JSON.stringify({patient_id:'16957952',mode:'all'}),JSON.stringify({retrieval_metrics:{medlocomo_official:{overall:{combined_score:.5}}}}),JSON.stringify([score]),JSON.stringify({}),now,now);insert.run('other-summary','medmemorybench','completed','{}','{}','[]','{}',now,now);const summaries=harness.listSummaries('medlocomo'),view=harness.view('medlocomo-summary'),detail=harness.scoreResult('medlocomo-summary','large-score');assert.equal(summaries.length,1);assert.equal(summaries[0].id,'medlocomo-summary');assert.equal(summaries[0].progress.retrieval_metrics.medlocomo_official.overall.combined_score,.5);assert.equal(Object.hasOwn(summaries[0],'results'),false);assert.equal(Object.hasOwn(summaries[0],'results_json'),false);assert.equal(view.result_payload,'summary');assert.equal(view.result_counts.scores,1);assert.equal(Object.hasOwn(view.results[0],'retrieval_context'),false);assert.equal(detail.retrieval_context.large_trace,'must-not-be-returned-in-view');store.close()});
class DelayedGateway{constructor(delay=10){this.delay=delay;this.active=0;this.maxActive=0;this.config={provider:'mock',model:'delayed-mock'}}publicConfig(){return this.config}async completeJSON(component,input,validator,mockFactory){this.active++;this.maxActive=Math.max(this.maxActive,this.active);await new Promise(resolve=>setTimeout(resolve,this.delay));try{const raw=await mockFactory(input),value=validator?validator(raw):raw;return{value,trace:{component,provider:'mock',model:'delayed-mock',latency_ms:this.delay,token_input:1,token_output:1,estimated_cost_usd:0,retries:0,raw_model_response:JSON.stringify(raw),model_input:input,prompt:'',parsed_response:value,raw_model_attempts:[],error:null,mock:true}}}finally{this.active--}}async completeText(component,input,mockFactory){this.active++;this.maxActive=Math.max(this.maxActive,this.active);await new Promise(resolve=>setTimeout(resolve,this.delay));try{const value=String(await mockFactory(input)||'').trim();return{value,trace:{component,provider:'mock',model:'delayed-mock',latency_ms:this.delay,token_input:1,token_output:1,estimated_cost_usd:0,retries:0,raw_model_response:value,model_input:input,prompt:'',parsed_response:value,raw_model_attempts:[],schema_enforcement:'plain_text',error:null,mock:true}}}finally{this.active--}}}
class RecordingGateway extends DelayedGateway{constructor(model,calls){super(0);this.config={provider:'live-test',model};this.calls=calls}async completeJSON(component,...args){this.calls.push({model:this.config.model,component});const result=await super.completeJSON(component,...args);result.trace.provider=this.config.provider;result.trace.model=this.config.model;return result}async completeText(component,...args){this.calls.push({model:this.config.model,component});const result=await super.completeText(component,...args);result.trace.provider=this.config.provider;result.trace.model=this.config.model;return result}}
class FailOnceGateway extends DelayedGateway{constructor(){super(0);this.didFail=false}async completeJSON(component,...args){if(component==='extractor'&&!this.didFail){this.didFail=true;throw new Error('intentional extractor failure')}return super.completeJSON(component,...args)}}
class FailJudgeGateway{constructor(){this.config={provider:'live-test',model:'failing-judge'}}async completeJSON(component){const error=new Error('intentional judge failure');error.gatewayTrace={component,error:{message:error.message}};throw error}}
test('MedMemory emits one role-attributed observation for each complete Session',()=>{const x=A.medmemorybench.load({persona_id:1,max_session:1}),raw=JSON.stringify(x.observations);assert.equal(x.subject_id,CLEAN_MEMORY);assert.equal(x.logical_subject_id,'medmemory-persona-1');assert.equal(x.memory_namespace,'clean');assert.ok(x.observations.every(item=>item.subject_id===CLEAN_MEMORY));assert.equal(x.observations.length,1);assert.equal(x.observations[0].source_type,'structured');assert.match(x.observations[0].raw_text,/\[Turn=1\]\[Role=(Patient|Doctor)\]\[Time=/);assert.match(x.observations[0].raw_text,/\[Role=Patient\]/);assert.match(x.observations[0].raw_text,/\[Role=Doctor\]/);assert.equal(raw.includes('knowledge_points'),false);assert.equal(raw.includes('source_key_points'),false);assert.ok(x.sessions[0].knowledge_points_reference)});
test('MedMemory noise keeps the interleaved prefix through the selected regular session',()=>{const x=A.medmemorybench.load({persona_id:1,noise:true,max_session:1}),regular=x.sessions.filter(s=>!s.is_noise),noise=x.sessions.filter(s=>s.is_noise);assert.equal(x.subject_id,NOISE_MEMORY);assert.equal(x.logical_subject_id,'medmemory-persona-1');assert.equal(x.memory_namespace,'with-noise');assert.ok(x.observations.every(item=>item.subject_id===NOISE_MEMORY));assert.deepEqual(regular.map(s=>s.session_id),[1]);assert.ok(noise.length);assert.equal(x.sessions.at(-1).session_id,1);assert.ok(noise.every(s=>/^noise-(family|health)-\d+$/.test(s.episode_id)));assert.equal(x.observations.some(o=>o.episode_id.includes('undefined')),false)});
test('MedMemory accepts the dataset multi-hop query type',()=>{const x=A.medmemorybench.load({persona_id:1,max_session:100,query_type:'multi_hop_clinical_deduction'});assert.ok(x.queries.length);assert.ok(x.queries.every(q=>q.query_type==='multi_hop_clinical_deduction'))});
test('MedMemory reports the next session when a query type has no task in range',()=>{const x=A.medmemorybench.load({persona_id:1,max_session:1,query_type:'entity_exact_match'});assert.equal(x.queries.length,0);assert.deepEqual(x.query_selection,{query_type:'entity_exact_match',selected_count:0,next_available_session:10})});
test('MedMemory selects an exact session window and keeps checkpoint boundaries',()=>{const x=A.medmemorybench.load({persona_id:1,start_session:2,session_count:2});assert.deepEqual(x.memory_window,{start_session:2,end_session:3,session_count:2,resume_session:1,resume_prefix_hash:x.memory_window.resume_prefix_hash});assert.deepEqual(x.sessions.map(s=>s.session_id),[2,3]);assert.deepEqual(x.session_ranges.map(r=>r.session_id),[2,3]);assert.equal(x.session_ranges[0].start_index,0);assert.equal(x.session_ranges.at(-1).end_index,x.observations.length);assert.ok(x.observations.every(o=>['session-2','session-3'].includes(o.episode_id)))});
test('MedMemory answer contracts expose format but not hidden answers',()=>{const cases=A.medmemorybench.cases(A.medmemorybench.load({persona_id:1,max_session:10}));assert.ok(cases.length);for(const item of cases){assert.equal('answers'in item.metadata,false);assert.equal('source_key_points'in item.metadata,false);assert.equal(item.metadata.answer_contract.language,'match the question language');assert.ok(item.metadata.answer_contract.format)}});
test('MedMemory query visibility stops at each query Session and Clean contains no Noise episode',()=>{const cases=A.medmemorybench.cases(A.medmemorybench.load({persona_id:1,max_session:20,noise:false})),session10=cases.find(item=>item.metadata.query_session===10);assert.ok(session10);assert.ok(session10.metadata.visible_episode_ids.includes('session-10'));assert.equal(session10.metadata.visible_episode_ids.includes('session-11'),false);assert.equal(session10.metadata.visible_episode_ids.some(id=>id.startsWith('noise-')),false)});
test('MedMemory preserves raw multiple-choice output and applies official option_match',()=>{const cases=A.medmemorybench.cases(A.medmemorybench.load({persona_id:1,max_session:10})),item=cases.find(x=>x.score_id==='session_10_mq_2'),normalized=A.medmemorybench.normalizeAnswer('A, B',item);assert.equal(normalized,'A, B');assert.equal(A.medmemorybench.compatibleScore(normalized,item.gold,item).score,1);const twoGold=cases.find(x=>x.score_id==='session_10_mq_1');assert.equal(A.medmemorybench.compatibleScore('B. 阿莫西林',twoGold.gold,twoGold).score,0)});
test('MedMemory sends TLA and SUA to official LLM Judge and does not add unofficial bilingual aliases',()=>{const cases=A.medmemorybench.cases(A.medmemorybench.load({persona_id:1,max_session:10})),temporal=cases.find(x=>x.score_id==='session_10_tla_2'),state=cases.find(x=>x.score_id==='session_10_sua_1'),entity=cases.find(x=>x.score_id==='session_10_eem_2');assert.equal(A.medmemorybench.requiresOfficialJudge(temporal),true);assert.equal(A.medmemorybench.requiresOfficialJudge(state),true);assert.throws(()=>A.medmemorybench.compatibleScore('2024-01-05',temporal.gold,temporal),/official LLM judge/);assert.equal(A.medmemorybench.normalizeAnswer('The patient has stopped taking empagliflozin due to safety concerns.',state),'The patient has stopped taking empagliflozin due to safety concerns.');assert.equal(A.medmemorybench.compatibleScore('cefuroxime',entity.gold,entity).score,0)});
test('MedLoCoMo formal QA always loads the complete patient timeline and excludes summaries',()=>{const full=A.medlocomo.load({patient_id:'16957952'}),legacyLimited=A.medlocomo.load({patient_id:'16957952',max_admission:1}),raw=JSON.stringify(full.observations);assert.equal(full.observations.length,full.admissions.length);assert.ok(full.observations.length>1);assert.equal(legacyLimited.observations.length,full.observations.length);assert.equal(raw.includes('patient_summary'),false);assert.equal(raw.includes('previous_admission_summary'),false);assert.ok(full.inspection_only)});
test('MedLoCoMo mode and question type select the requested QA without truncating to 20',()=>{const data=A.medlocomo.load({patient_id:'16957952'}),single=A.medlocomo.cases(data,{mode:'single admission'}),cross=A.medlocomo.cases(data,{mode:'cross_admission'}),reasoning=A.medlocomo.cases(data,{mode:'single_admission',query_type:'medical_reasoning'});assert.equal(single.length,69);assert.equal(cross.length,69);assert.ok(single.every(item=>item.metadata.scope==='single_admission'));assert.ok(cross.every(item=>item.metadata.scope==='cross_admission'));assert.ok(reasoning.length);assert.ok(reasoning.every(item=>item.task==='medical_reasoning'&&item.metadata.scope==='single_admission'));assert.equal(A.medlocomo.cases(data,{mode:'all'}).length,data.queries.length)});
test('MedLoCoMo experiment ignores legacy admission and observation caps',async()=>{const store=new Store(':memory:'),harness=new ExperimentHarness(store),expected=A.medlocomo.load({patient_id:'16957952'}).observations.length,launched=harness.launch('medlocomo',{patient_id:'16957952',mode:'single_admission',max_admission:1,max_observations:1,max_queries:1});assert.equal(launched.progress.total,expected);assert.equal(launched.config.max_admission,undefined);assert.equal(launched.config.max_observations,undefined);harness.control(launched.id,'cancel');for(let index=0;index<100&&harness.active.has(launched.id);index++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(harness.active.has(launched.id),false);store.close()});
test('CPCD-Bench loads official tasks and preserves online-script evaluator fields post-answer only',()=>{const data=A.cpcdbench.load({case_id:'张明_261'}),cases=A.cpcdbench.cases(data),srg=cases.find(item=>item.task==='session_level_response_generation'),memory=cases.find(item=>item.task==='memory_recall');assert.ok(data.observations.length);assert.ok(cases.length);assert.equal(String(srg.question).includes(String(srg.gold[0])),false);assert.equal(srg.metadata.protocol_only,true);assert.equal(srg.metadata.full_consultation_history,null);assert.ok(srg.metadata.representative_point);assert.equal(srg.metadata.task_file,'张明261.json');assert.ok(memory.metadata.answer_source.primary_session);assert.equal(memory.metadata.full_session_file,'张明261_fullsession.json');assert.ok(Array.isArray(memory.metadata.full_consultation_history));assert.ok(memory.metadata.official_rubric.length>100);assert.equal(memory.metadata.answer_prompt_protocol,'official-online-template-adapted-careharness-memory');assert.equal(memory.metadata.official_evaluation.metric,'official online-script rubric LLM-as-Judge')});
test('QA benchmarks attach centralized answer contracts',()=>{const cases=[A.medmemorybench.cases(A.medmemorybench.load({persona_id:1,max_session:10}))[0],A.medlocomo.cases(A.medlocomo.load({patient_id:'16957952'}))[0],A.cpcdbench.cases(A.cpcdbench.load({case_id:'张明_261'}))[0]];for(const item of cases){assert.ok(item.metadata.answer_contract.language,item.task);assert.ok(item.metadata.answer_contract.grounding,item.task);assert.ok(item.metadata.answer_contract.format,item.task)}});
test('query, gold, answer options and judge score cannot become core observations',()=>{const adapter=A.medmemorybench;for(const key of ['query','gold','answer_options','judge_score'])assert.throws(()=>adapter.assertCoreObservation({metadata:{[key]:'leak'}}),/leakage/)});
test('all benchmark adapters emit the same minimal core observation fields',()=>{const samples=[A.medmemorybench.load({persona_id:1,max_session:1}),A.medlocomo.load({patient_id:'16957952'}),A.cpcdbench.load({case_id:'张明_261'})];const expected=['episode_id','event_time','raw_text','source_type','subject_id','turn_id'];for(const sample of samples){assert.ok(sample.observations.length);assert.deepEqual(Object.keys(sample.observations[0]).sort(),expected)}});
test('experiment defaults to every observation in the selected session range',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),expected=A.medmemorybench.load({persona_id:1,max_session:1}).observations.length,x=h.launch('medmemorybench',{persona_id:1,max_session:1,max_queries:1});assert.equal(x.progress.total,expected);assert.equal(x.progress.memory_build_completeness.status,'building');h.control(x.id,'cancel');for(let i=0;i<100&&h.active.has(x.id);i++)await new Promise(r=>setTimeout(r,5));assert.equal(h.active.has(x.id),false);const cancelled=h.get(x.id);assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.progress.memory_build_completeness.memory_incomplete,true);assert.equal(s.memoryStateScope(CLEAN_MEMORY).status,'incomplete');s.close()});
test('MedMemory Clean and With-noise State stores never clear or overwrite each other',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s);await h.start('medmemorybench',{persona_id:1,noise:true,start_session:1,session_count:1,query_type:'entity_exact_match',max_queries:1});const noiseBefore=s.statesFor(NOISE_MEMORY),noiseScope=s.memoryStateScope(NOISE_MEMORY);assert.ok(noiseBefore.length);assert.equal(noiseScope.memory_namespace,'with-noise');assert.equal(s.statesFor(CLEAN_MEMORY).length,0);const clean=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,query_type:'entity_exact_match',max_queries:1}),cleanStates=s.statesFor(CLEAN_MEMORY);assert.equal(clean.progress.cleared_states,0);assert.ok(cleanStates.length);assert.equal(s.memoryStateScope(CLEAN_MEMORY).memory_namespace,'clean');assert.deepEqual(s.statesFor(NOISE_MEMORY),noiseBefore);assert.equal(s.memoryStateScope(NOISE_MEMORY).experiment_id,noiseScope.experiment_id);assert.equal(h.preview('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}).current_state_scope.subject_id,CLEAN_MEMORY);assert.equal(h.preview('medmemorybench',{persona_id:1,noise:true,start_session:1,session_count:1}).current_state_scope.subject_id,NOISE_MEMORY);const noiseCheckpoints=s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints WHERE subject_id=?`).get(NOISE_MEMORY).n,cleanCheckpoints=s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints WHERE subject_id=?`).get(CLEAN_MEMORY).n;assert.ok(noiseCheckpoints>0);assert.ok(cleanCheckpoints>0);assert.deepEqual(new Set(s.memorySubjects().map(item=>item.subject_id)),new Set([CLEAN_MEMORY,NOISE_MEMORY]));s.close()});
test('background experiment jobs preserve progress and score external queries without state leakage',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),subjectId='background-safe',gold='gold-answer-never-present-in-memory';h.adapters.synthetic={load:()=>({observations:[{subject_id:subjectId,source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'The patient reports a stable condition.'}]}),cases:()=>[{score_id:'background-query',task:'entity_exact_match',question:'What is the target answer?',gold:[gold],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'en',format:'brief'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const x=h.launch('synthetic',{});try{h.control(x.id,'pause');assert.equal(h.get(x.id).status,'paused');h.control(x.id,'resume');assert.equal(h.get(x.id).status,'running')}catch(e){assert.match(e.message,/not active/)}for(let i=0;i<100&&['running','paused'].includes(h.get(x.id).status);i++)await new Promise(r=>setTimeout(r,10));const done=h.get(x.id);assert.equal(done.progress.completed+done.progress.failed,done.progress.total);assert.ok(done.results.some(r=>r.kind==='score'));assert.equal(JSON.stringify(s.statesFor(subjectId)).includes(gold),false);s.close()});
test('query-time retrieval excludes future Session State and its evidence',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),observations=[{subject_id:'future-safe',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我这一阶段的血糖持续偏高。'},{subject_id:'future-safe',source_type:'patient',episode_id:'session-2',turn_id:'1',event_time:'2024-02-01',raw_text:'我这一阶段的血糖已经恢复正常。'}];h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-session-1',task:'state_update',question:'患者当时的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const done=await h.start('synthetic',{}),score=done.results.find(item=>item.kind==='score');assert.equal(done.progress.query_total,1);assert.equal(done.progress.scored,1);assert.ok(score.retrieval_context.retrieved_states.length);assert.ok(score.retrieval_context.retrieved_states.every(item=>item.episode_id==='session-1'));assert.ok(score.retrieval_context.retrieved_evidence.every(item=>item.episode_id==='session-1'));assert.deepEqual(score.evidence_trace.state_ids,score.retrieval_context.retrieved_states.map(item=>item.state_id));assert.deepEqual(score.evidence_trace.evidence_ids,score.retrieval_context.retrieved_evidence.map(item=>item.evidence_id));assert.equal(score.retrieval_trace.evidence_index_gate.enabled,true);assert.equal(score.retrieval_trace.candidate_stage.content_dedup_gate.enabled,true);assert.equal(done.progress.retrieval_metrics.query_count,1);assert.equal(done.progress.retrieval_metrics.zero_recall_queries,0);assert.equal(done.progress.retrieval_metrics.by_query_type.state_update.accuracy,1);s.close()});
test('the Evidence Index Gate is mandatory and removed decision-layer config cannot reach the answer model',async()=>{
  const s=new Store(':memory:'),pipelineGateway=new DelayedGateway(0),plannerGateway=new DelayedGateway(0),answerGateway=new DelayedGateway(0);answerGateway.config={provider:'live-test',model:'answer-input-recorder'};
  const registry={pipelineOptions:()=>({gateway:pipelineGateway}),assignmentSnapshot:()=>({global:pipelineGateway.config,judge:answerGateway.config}),gateway:component=>component==='judge'?answerGateway:plannerGateway},h=new ExperimentHarness(s,undefined,registry),observations=[{subject_id:'gated-query',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我规律服用降糖药，但血糖仍升高并持续掉重、多饮、多尿。'}];
  h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-gated',task:'inference_generation',question:'患者是否应该自行增加降糖药剂量？',gold:['不应自行加量'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'患者特异性回答'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};
  const done=await h.start('synthetic',{evidence_index_gate:false,obsolete_decision_gate:true,obsolete_decision_gates:{enabled:true}}),score=done.results.find(item=>item.kind==='score'),candidateIds=score.retrieval_context.candidate_states.map(item=>item.state_id),retrievedIds=score.retrieval_context.retrieved_states.map(item=>item.state_id);
  assert.equal(done.config.evidence_index_gate,true);assert.equal(score.retrieval_trace.evidence_index_gate.enabled,true);assert.ok(score.retrieval_trace.evidence_index_gate.chains.length);assert.ok(score.retrieval_trace.evidence_index_gate.coverage);assert.equal(score.retrieval_trace.selection_mode,'candidate_passthrough');assert.deepEqual(retrievedIds,candidateIds);
  assert.equal(Object.hasOwn(done.config,'obsolete_decision_gate'),false);assert.equal(Object.hasOwn(done.config,'obsolete_decision_gates'),false);assert.equal(Object.hasOwn(score,'decision_gates'),false);assert.equal(Object.hasOwn(score.retrieval_context,'decision_gates'),false);assert.equal(Object.hasOwn(score.answer_model_trace.model_input,'decision_gates'),false);
  assert.equal(done.progress.retrieval_metrics.evidence_index_gate_queries,1);assert.equal(Object.hasOwn(done.progress.retrieval_metrics,'decision_gate_queries'),false);assert.equal(done.progress.retrieval_metrics.candidate_passthrough_queries,1);assert.ok(Number.isFinite(done.progress.retrieval_metrics.average_gate_coverage));assert.equal(Object.hasOwn(done.progress.retrieval_metrics,'average_gate_selection_coverage'),false);assert.equal(Object.hasOwn(done.progress.retrieval_metrics,'average_chain_node_retention'),false);s.close();
});
test('wrong-answer export includes only wrong questions and their State, Evidence and raw observations',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),observations=[{subject_id:'wrong-export',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}];h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-wrong',task:'entity_exact_match',question:'患者的血糖状态是什么？',gold:['正确答案'],metadata:{query_session:1,answer_contract:{language:'zh-CN',format:'简短答案'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:.5,is_correct:false,method:'test_partial'})};const done=await h.start('synthetic',{api_key:'must-not-leak'}),exported=h.wrongAnswerExport(done.id),item=exported.wrong_answers[0],raw=JSON.stringify(exported);assert.equal(exported.summary.total_score_results,1);assert.equal(exported.summary.wrong_answer_count,1);assert.deepEqual(exported.summary.score_ids,['q-wrong']);assert.equal(item.question,'患者的血糖状态是什么？');assert.deepEqual(item.gold,['正确答案']);assert.ok(item.related_states.length);assert.ok(item.related_evidence.length);assert.equal(item.related_observations[0].raw_text,'我的血糖持续偏高。');assert.equal(raw.includes('must-not-leak'),false);assert.equal(exported.experiment.config.api_key,'[REDACTED]');s.close()});
test('CPCD wrong-answer export includes every scored rubric result below full marks',()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),now=new Date().toISOString(),results=[{kind:'score',score_id:'cpcd-partial',task:'memory_recall',status:'scored',score:.95,is_correct:null,scoring_method:'cpcd_bench_official_llm_judge',scoring_details:{raw_average_score:4.75,dimension_scores:{accuracy:{score:4},completeness:{score:5},temporal_consistency:{score:5},no_hallucination:{score:5}}}},{kind:'score',score_id:'cpcd-full',task:'memory_recall',status:'scored',score:1,is_correct:null,scoring_method:'cpcd_bench_official_llm_judge',scoring_details:{raw_average_score:5}}];s.db.prepare(`INSERT INTO experiments(id,benchmark,status,config_json,progress_json,results_json,version_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run('cpcd-export','cpcdbench','completed','{}','{}',JSON.stringify(results),'{}',now,now);const exported=h.wrongAnswerExport('cpcd-export');assert.equal(exported.summary.total_score_results,2);assert.equal(exported.summary.wrong_answer_count,1);assert.equal(exported.summary.cpcd_below_full_score_count,1);assert.deepEqual(exported.summary.score_ids,['cpcd-partial']);assert.equal(exported.wrong_answers[0].scoring_details.dimension_scores.accuracy.score,4);assert.match(exported.wrong_answer_criterion,/CPCD-Bench rubric result is below the full score/);s.close()});
test('query answer-model failures make the experiment partial and remain in the diagnostic export',async()=>{const s=new Store(':memory:'),pipelineGateway=new DelayedGateway(0),plannerGateway=new DelayedGateway(0),answerGateway=new FailJudgeGateway(),registry={pipelineOptions:()=>({gateway:pipelineGateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:'delayed-mock'},judge:answerGateway.config}),gateway:component=>component==='judge'?answerGateway:plannerGateway},h=new ExperimentHarness(s,undefined,registry),observations=[{subject_id:'query-failure',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}];h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-failed',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const done=await h.start('synthetic',{}),score=done.results.find(item=>item.kind==='score'),exported=h.wrongAnswerExport(done.id);assert.equal(done.status,'partial');assert.equal(done.progress.query_failed,1);assert.equal(done.progress.retrieval_metrics.failed_query_count,1);assert.equal(score.status,'failed');assert.equal(score.scoring_method,'answer_failed');assert.equal(exported.summary.query_failure_count,1);assert.deepEqual(exported.summary.score_ids,['q-failed']);assert.equal(exported.wrong_answers[0].answer_model_trace.error.message,'intentional judge failure');s.close()});
test('experiment preprocesses at most four observations concurrently and commits in source order',async()=>{const s=new Store(':memory:'),gateway=new DelayedGateway(),registry={pipelineOptions:()=>({gateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:'delayed-mock'}}),gateway:()=>gateway},h=new ExperimentHarness(s,undefined,registry),observations=Array.from({length:8},(_,index)=>({subject_id:'parallel-patient',source_type:'patient',episode_id:'session-1',turn_id:String(index+1),event_time:'2026-01-01',raw_text:index%2?'我已经停药。':'我按时服药。'}));h.adapters.synthetic={load:()=>({observations,queries:[]}),cases:()=>[],compatibleScore:()=>({score:0,is_correct:false,method:'test'})};const done=await h.start('synthetic',{});assert.equal(gateway.maxActive,4);assert.equal(done.progress.preprocess_completed,8);assert.equal(done.progress.preprocess_concurrency,4);const committed=s.db.prepare(`SELECT turn_id FROM observations ORDER BY rowid`).all();assert.deepEqual(committed.map(x=>x.turn_id),observations.map(x=>x.turn_id));s.close()});
test('MedMemory builds one complete Session, answers its queries, then starts the next Session',async()=>{
  const s=new Store(':memory:'),calls=[],gateway=new RecordingGateway('ordered-live',calls),registry={pipelineOptions:()=>({gateway}),assignmentSnapshot:()=>({global:gateway.config}),gateway:()=>gateway},h=new ExperimentHarness(s,undefined,registry),observations=[
    {subject_id:'medmemory-ordered',source_type:'structured',episode_id:'session-1',turn_id:'session',event_time:'2026-01-01',raw_text:'[Turn=1][Role=Patient][Time=2026-01-01]\n我规律服用二甲双胍。'},
    {subject_id:'medmemory-ordered',source_type:'structured',episode_id:'session-2',turn_id:'session',event_time:'2026-01-02',raw_text:'[Turn=1][Role=Patient][Time=2026-01-02]\n我今天血糖偏高。'}
  ],queries=[
    {score_id:'q-session-1',task:'state_update',question:'第一阶段用药状态？',gold:['规律服用'],metadata:{query_session:1,visible_episode_ids:['session-1'],answer_contract:{language:'zh-CN',format:'简短状态'}}},
    {score_id:'q-session-2',task:'state_update',question:'第二阶段血糖状态？',gold:['偏高'],metadata:{query_session:2,visible_episode_ids:['session-1','session-2'],answer_contract:{language:'zh-CN',format:'简短状态'}}}
  ],data={observations,memory_window:{start_session:1,end_session:2,session_count:2,resume_session:0,resume_prefix_hash:null},session_ranges:[{session_id:1,start_index:0,end_index:1,prefix_hash:'session-1-prefix'},{session_id:2,start_index:1,end_index:2,prefix_hash:'session-2-prefix'}]};
  h.adapters.medmemorybench={load:()=>data,cases:()=>queries,normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};
  const done=await h.start('medmemorybench',{persona_id:1,noise:false}),components=calls.map(item=>item.component),resultOrder=done.results.filter(item=>item.run_id||item.kind==='score').map(item=>item.kind==='score'?item.score_id:item.observation.episode_id);
  assert.equal(done.status,'completed');
  assert.equal(done.progress.preprocess_concurrency,1);
  assert.deepEqual(resultOrder,['session-1','q-session-1','session-2','q-session-2']);
  assert.ok(components.indexOf('medmemory_answer')<components.lastIndexOf('extractor'));
  assert.deepEqual(done.results.filter(item=>item.kind==='score').map(item=>item.query_session),[1,2]);
  s.close();
});
test('MedMemory can score a frozen current-State snapshot without rebuilding, mutation or future-State leakage',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),observations=[{subject_id:'medmemory-persona-1',source_type:'structured',episode_id:'session-1',turn_id:'session',event_time:'2024-01-01',raw_text:'[Turn=1][Role=Patient][Time=2024-01-01] 我目前血糖偏高。'},{subject_id:'medmemory-persona-1',source_type:'structured',episode_id:'session-2',turn_id:'session',event_time:'2024-02-01',raw_text:'[Turn=1][Role=Patient][Time=2024-02-01] 我目前血糖已经恢复正常。'}],query={score_id:'current-state-q1',task:'state_update',question:'患者在 Session 1 的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}},data={observations,memory_window:{start_session:1,end_session:2,session_count:2,resume_session:0,resume_prefix_hash:null},session_ranges:[{session_id:1,start_index:0,end_index:1,prefix_hash:'session-1-prefix'},{session_id:2,start_index:1,end_index:2,prefix_hash:'session-2-prefix'}]};
  h.adapters.medmemorybench={load:()=>data,cases:()=>[query],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test_current_state'})};
  const subject=observations[0].subject_id,built=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:2}),currentScope=s.memoryStateScope(subject);s.saveMemoryStateScope({...currentScope,memory_scope_key:'different-builder-and-model-scope'});const before={states:s.statesFor(subject),edges:s.graphEdgesFor(subject),evidence:s.evidenceFor(subject),scope:s.memoryStateScope(subject),runCount:s.db.prepare(`SELECT COUNT(*) AS n FROM runs`).get().n,checkpointCount:s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints`).get().n},done=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:2,score_only_current_state:true,evidence_index_gate:true}),score=done.results.find(item=>item.kind==='score'),after={states:s.statesFor(subject),edges:s.graphEdgesFor(subject),evidence:s.evidenceFor(subject),scope:s.memoryStateScope(subject),runCount:s.db.prepare(`SELECT COUNT(*) AS n FROM runs`).get().n,checkpointCount:s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints`).get().n};
  assert.equal(built.status,'completed');assert.equal(done.status,'completed');assert.equal(done.config.score_only_current_state,true);assert.equal(done.progress.total,0);assert.equal(done.progress.completed,0);assert.equal(done.progress.memory_build_completeness.status,'not_run_current_state');assert.equal(done.results.filter(item=>item.run_id).length,0);assert.equal(score.memory_completeness.policy,'answer_and_score_frozen_current_state');assert.equal(score.memory_incomplete,false);assert.ok(score.retrieval_context.retrieved_states.length>0);assert.ok(score.retrieval_context.retrieved_states.every(item=>item.episode_id==='session-1'));assert.ok(score.retrieval_context.retrieved_evidence.every(item=>item.episode_id==='session-1'));assert.equal(done.config.current_state_snapshot.source_end_session,2);assert.equal(done.config.current_state_snapshot.state_count,before.states.length);assert.match(done.config.current_state_snapshot.fingerprint,/^[a-f0-9]{64}$/);assert.deepEqual(after,before);s.close();
});
test('MedMemory current-State scoring rejects missing Session coverage and mismatched Noise before creating an experiment',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),observation={subject_id:'medmemory-persona-1',source_type:'structured',episode_id:'session-1',turn_id:'session',event_time:'2024-01-01',raw_text:'[Turn=1][Role=Patient][Time=2024-01-01] 我目前血糖偏高。'},query={score_id:'current-state-q2',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1','session-2'],query_session:2,answer_contract:{language:'zh-CN',format:'简短状态'}}},data={observations:[observation],memory_window:{start_session:1,end_session:1,session_count:1,resume_session:0,resume_prefix_hash:null},session_ranges:[{session_id:1,start_index:0,end_index:1,prefix_hash:'session-1-prefix'}]};
  h.adapters.medmemorybench={load:()=>data,cases:()=>[],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test_current_state'})};await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1});const count=h.list().length;h.adapters.medmemorybench.cases=()=>[query];await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,score_only_current_state:true}),/只完整覆盖到 Session 1.*Session 2/);await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:true,start_session:1,session_count:1,score_only_current_state:true}),/Persona 或 Noise/);assert.equal(h.list().length,count);s.close();
});
test('MedMemory session rerun restores the prior checkpoint and deletes later State only in its mode namespace',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s);const initial=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:3});assert.equal(initial.status,'completed');assert.equal(initial.progress.checkpoint_session,3);assert.ok(s.statesFor(CLEAN_MEMORY).some(x=>x.episode_id==='session-3'));assert.deepEqual({...s.memoryStateScope(CLEAN_MEMORY),updated_at:undefined,experiment_id:undefined,memory_scope_key:undefined},{subject_id:CLEAN_MEMORY,logical_subject_id:'medmemory-persona-1',memory_namespace:'clean',benchmark:'medmemorybench',persona_id:1,noise:false,memory_pipeline_version:MEMORY_PIPELINE_VERSION,memory_scope_key:undefined,source_start_session:1,source_end_session:3,complete_through_session:3,current_session:null,status:'completed',experiment_id:undefined,target_start_session:1,target_end_session:3,observation_total:3,observation_succeeded:3,observation_failed:0,updated_at:undefined});const rerun=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1});assert.equal(rerun.status,'completed');assert.equal(rerun.progress.reused_through_session,1);assert.equal(rerun.progress.window_start_session,2);assert.equal(rerun.progress.window_end_session,2);assert.ok(rerun.results.filter(x=>x.run_id).every(x=>x.observation.episode_id==='session-2'));const states=s.statesFor(CLEAN_MEMORY),scope=s.memoryStateScope(CLEAN_MEMORY);assert.ok(states.some(x=>x.episode_id==='session-1'));assert.ok(states.some(x=>x.episode_id==='session-2'));assert.equal(states.some(x=>x.episode_id==='session-3'),false);assert.equal(scope.source_start_session,1);assert.equal(scope.source_end_session,2);assert.equal(scope.complete_through_session,2);assert.equal(scope.noise,false);assert.equal(scope.memory_namespace,'clean');assert.equal(scope.memory_pipeline_version,MEMORY_PIPELINE_VERSION);assert.equal(scope.status,'completed');assert.equal(scope.observation_total,2);assert.equal(scope.observation_succeeded,2);assert.equal(scope.observation_failed,0);assert.equal(h.preview('medmemorybench',{persona_id:1,start_session:2,session_count:1}).current_state_scope.source_end_session,2);assert.equal(s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints WHERE subject_id=? AND session_no>2`).get(CLEAN_MEMORY).n,0);s.close()});
test('MedMemory refuses to reuse a checkpoint from a different noise configuration',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s);await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1});await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:true,start_session:2,session_count:1}),/兼容 Checkpoint/);s.close()});
test('v13 refuses a legacy v5 checkpoint scope instead of silently restoring it',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),data=A.medmemorybench.load({persona_id:1,noise:false,start_session:2,session_count:1});s.saveMemoryCheckpoint({benchmark:'medmemorybench',subject_id:CLEAN_MEMORY,scope_key:'legacy-six-state-session-memory-v5-scope',session_no:data.memory_window.resume_session,prefix_hash:data.memory_window.resume_prefix_hash,experiment_id:'legacy-v5',progress:{total:1,succeeded:1,failed:0}});await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);assert.equal(h.list().length,0);s.close()});
test('bootstrap cannot relabel a completed v9 experiment and its States as a v13 graph checkpoint',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}),legacyConfig={...first.config,memory_pipeline_version:'six-state-session-memory-v9'};
  assert.ok(s.statesFor(CLEAN_MEMORY).length>0);
  s.db.prepare(`UPDATE experiments SET config_json=? WHERE id=?`).run(JSON.stringify(legacyConfig),first.id);
  s.db.exec(`DELETE FROM memory_checkpoints`);
  const experimentCount=h.list().length;
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);
  assert.equal(h.list().length,experimentCount);
  assert.equal(s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints`).get().n,0);
  s.close();
});
test('a complete v13 Patient Graph snapshot can bootstrap a deleted checkpoint',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}),stateCount=s.statesFor(CLEAN_MEMORY).length;
  assert.equal(first.config.memory_pipeline_version,MEMORY_PIPELINE_VERSION);
  assert.match(first.config.memory_scope_key,/^[a-f0-9]{64}$/);
  assert.ok(stateCount>0);
  s.db.exec(`DELETE FROM memory_checkpoints`);
  const resumed=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1});
  assert.equal(resumed.progress.reused_through_session,1);
  assert.equal(resumed.progress.restored_states,stateCount);
  assert.ok(s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints WHERE session_no=1`).get().n>0);
  s.close();
});
test('bootstrap rejects a v13 graph snapshot missing one expected node',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}),states=s.statesFor(CLEAN_MEMORY);
  assert.ok(states.length>1);
  s.db.exec(`DELETE FROM memory_checkpoints`);
  s.db.prepare(`DELETE FROM patient_graph_nodes WHERE id=?`).run(states[0].state_id);
  const experimentCount=h.list().length;
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);
  assert.equal(h.list().length,experimentCount);
  assert.equal(s.db.prepare(`SELECT COUNT(*) AS n FROM memory_checkpoints`).get().n,0);
  assert.equal(h.get(first.id).config.memory_pipeline_version,MEMORY_PIPELINE_VERSION);
  s.close();
});
test('a corrupted stored checkpoint is rejected and rebuilt from the complete v13 graph snapshot',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}),stateCount=s.statesFor(CLEAN_MEMORY).length,row=s.db.prepare(`SELECT id,state_json FROM memory_checkpoints WHERE experiment_id=? AND session_no=1`).get(first.id),truncated=JSON.parse(row.state_json);
  truncated.pop();
  s.db.prepare(`UPDATE memory_checkpoints SET state_json=? WHERE id=?`).run(JSON.stringify(truncated),row.id);
  const resumed=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),repaired=JSON.parse(s.db.prepare(`SELECT state_json FROM memory_checkpoints WHERE id=?`).get(row.id).state_json);
  assert.equal(resumed.progress.reused_through_session,1);
  assert.equal(resumed.progress.restored_states,stateCount);
  assert.equal(repaired.length,stateCount);
  s.close();
});
test('resume rejects a checkpoint whose State references missing Evidence',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1}),state=s.statesFor(CLEAN_MEMORY)[0],experimentCount=h.list().length;
  assert.ok(state.evidence_ids.length>0);
  s.db.prepare(`DELETE FROM evidence WHERE id=?`).run(state.evidence_ids[0]);
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);
  assert.equal(h.list().length,experimentCount);
  assert.equal(h.get(first.id).status,'completed');
  s.close();
});
test('segmented v13 Patient Graph checkpoints validate their complete parent lineage',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s);
  await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1});
  await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1});
  const stateCount=s.statesFor(CLEAN_MEMORY).length,resumed=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:3,session_count:1});
  assert.equal(resumed.progress.reused_through_session,2);
  assert.equal(resumed.progress.restored_states,stateCount);
  s.close();
});
test('query-only partial experiments retain a resumable complete memory checkpoint',async()=>{
  const s=new Store(':memory:'),pipelineGateway=new DelayedGateway(0),plannerGateway=new DelayedGateway(0),answerGateway=new FailJudgeGateway(),registry={pipelineOptions:()=>({gateway:pipelineGateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:'delayed-mock'},judge:answerGateway.config}),gateway:component=>component==='judge'?answerGateway:plannerGateway},h=new ExperimentHarness(s,undefined,registry),adapter=h.adapters.medmemorybench;
  adapter.cases=data=>[{score_id:`query-${data.memory_window.start_session}`,task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:data.observations.map(item=>item.episode_id),query_session:data.memory_window.start_session,answer_contract:{language:'zh-CN',format:'简短状态'}}}];
  const first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1});
  assert.equal(first.status,'partial');
  assert.equal(first.progress.failed,0);
  assert.equal(first.progress.query_failed,1);
  assert.equal(first.progress.memory_build_completeness.memory_incomplete,false);
  const stateCount=s.statesFor(CLEAN_MEMORY).length,resumed=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1});
  assert.equal(resumed.progress.reused_through_session,1);
  assert.equal(resumed.progress.restored_states,stateCount);
  s.close();
});
test('MedMemory checkpoint compatibility follows model identity rather than transport endpoint',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),firstModel={provider:'mock',model:'same-memory-model',base_url:'https://old-transport.test/v1'},secondModel={provider:'mock',model:'same-memory-model',base_url:'https://new-transport.test/v1'};await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,model:firstModel});const resumed=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1,model:secondModel});assert.equal(resumed.progress.reused_through_session,1);s.close()});
test('MedMemory checkpoint scope distinguishes providers even when the model name is identical',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),model='same-name-different-provider';
  await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,model:{provider:'mock',model}});
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1,model:{provider:'openai-compatible',base_url:'https://provider-change.test/v1',model}}),/完整兼容 Checkpoint/);
  s.close();
});
test('MedMemory checkpoint scope distinguishes temperature and max token settings',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),base={provider:'mock',model:'sampling-sensitive-model',temperature:0,max_tokens:1200};
  await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,model:base});
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1,model:{...base,temperature:.4}}),/完整兼容 Checkpoint/);
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1,model:{...base,max_tokens:2400}}),/完整兼容 Checkpoint/);
  s.close();
});
test('checkpoint lineage rejects Runs whose actual memory model differs from the recorded creation identity',async()=>{
  const s=new Store(':memory:'),h=new ExperimentHarness(s),actualModel={provider:'mock',model:'actual-run-model'},claimedModel={provider:'mock',model:'claimed-creation-model'},first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,model:actualModel}),referenceStore=new Store(':memory:'),referenceHarness=new ExperimentHarness(referenceStore),reference=await referenceHarness.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1,model:claimedModel}),dirtyConfig={...first.config,model:reference.config.model,resolved_models:reference.config.resolved_models,memory_scope_key:reference.config.memory_scope_key};
  s.db.prepare(`UPDATE experiments SET config_json=? WHERE id=?`).run(JSON.stringify(dirtyConfig),first.id);
  s.db.prepare(`UPDATE memory_checkpoints SET scope_key=? WHERE experiment_id=?`).run(reference.config.memory_scope_key,first.id);
  await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1,model:claimedModel}),/完整兼容 Checkpoint/);
  referenceStore.close();s.close();
});
test('an intentionally truncated memory build is partial and leaves an incomplete State scope',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),done=await h.start('medmemorybench',{persona_id:1,noise:false,max_session:10,max_observations:1,max_queries:1}),scope=s.memoryStateScope(CLEAN_MEMORY);assert.equal(done.status,'partial');assert.equal(done.progress.memory_build_completeness.memory_incomplete,true);assert.equal(scope.status,'incomplete');assert.equal(scope.complete_through_session,1);s.close()});
test('MedMemory refuses to bootstrap or reuse a checkpoint containing a failed Session',async()=>{const s=new Store(':memory:'),gateway=new FailOnceGateway(),registry={pipelineOptions:()=>({gateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:'delayed-mock'}}),gateway:()=>gateway},h=new ExperimentHarness(s,undefined,registry),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:1});assert.equal(first.status,'failed');assert.equal(first.progress.completed,0);assert.equal(first.progress.failed,1);assert.equal(first.progress.memory_build_completeness.memory_incomplete,true);const failedScope=s.memoryStateScope(CLEAN_MEMORY);assert.equal(failedScope.status,'incomplete');assert.equal(failedScope.complete_through_session,0);await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);s.db.exec(`DELETE FROM memory_checkpoints;DELETE FROM memory_state_scopes;`);await assert.rejects(()=>h.start('medmemorybench',{persona_id:1,noise:false,start_session:2,session_count:1}),/完整兼容 Checkpoint/);s.close()});
test('retry preserves the original data range and resolves the currently assigned models',async()=>{const s=new Store(':memory:'),gateway=new FailOnceGateway();let currentModel='model-before-retry';const registry={pipelineOptions:()=>({gateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:currentModel}}),gateway:()=>gateway},h=new ExperimentHarness(s,undefined,registry),first=await h.start('medmemorybench',{persona_id:1,noise:false,start_session:1,session_count:3,query_type:'entity_exact_match',max_queries:1});currentModel='model-at-retry';const retry=h.retryFailed(first.id);assert.equal(first.progress.failed,1);assert.equal(retry.progress.total,3);assert.equal(retry.config.retry_of,first.id);assert.equal(retry.config.start_session,1);assert.equal(retry.config.session_count,3);assert.equal(retry.config.noise,false);assert.equal(retry.config.query_type,'entity_exact_match');assert.equal(retry.config.max_queries,1);assert.equal(retry.config.resolved_models.global.model,'model-at-retry');h.control(retry.id,'cancel');for(let index=0;index<100&&h.active.has(retry.id);index++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(h.active.has(retry.id),false);s.close()});
test('retry drops every explicit old model override and executes with current registry gateways',async()=>{
  const s=new Store(':memory:'),calls=[],pipelineGateway=new RecordingGateway('current-pipeline',calls),plannerGateway=new RecordingGateway('current-planner',calls),answerGateway=new RecordingGateway('current-answer',calls),scoringJudgeGateway=new RecordingGateway('current-scoring-judge',calls),medLoCoMoJudgeGateway=new RecordingGateway('current-medlocomo-judge',calls),cpcdJudgeGateway=new RecordingGateway('current-cpcd-judge',calls);
  const registry={pipelineOptions:()=>({gateway:pipelineGateway}),assignmentSnapshot:()=>({global:{provider:'live-test',model:'current-pipeline'},query_planner:{provider:'live-test',model:'current-planner'},judge:{provider:'live-test',model:'current-answer'},scoring_judge:{provider:'live-test',model:'current-scoring-judge'},medlocomo_judge:{provider:'live-test',model:'current-medlocomo-judge'},cpcd_judge:{provider:'live-test',model:'current-cpcd-judge'}}),gateway:component=>component==='judge'?answerGateway:component==='scoring_judge'?scoringJudgeGateway:component==='medlocomo_judge'?medLoCoMoJudgeGateway:component==='cpcd_judge'?cpcdJudgeGateway:plannerGateway};
  const h=new ExperimentHarness(s,undefined,registry),observations=[{subject_id:'explicit-model-retry',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}],query={score_id:'q-current-model',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}};let caseCalls=0;
  h.adapters.synthetic={load:()=>({observations}),cases:()=>{caseCalls++;if(caseCalls===2)throw new Error('force retry after old overrides');return[query]},normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};
  const oldModel=name=>({provider:'mock',model:name}),first=await h.start('synthetic',{max_observations:1,max_queries:1,model:oldModel('old-global'),answer_model:oldModel('old-answer'),judge_model:oldModel('old-judge'),scoring_judge_model:oldModel('old-scoring-judge'),medlocomo_judge_model:oldModel('old-medlocomo-judge'),cpcd_judge_model:oldModel('old-cpcd-judge'),query_planner_model:oldModel('old-planner'),state_selector_model:oldModel('old-state-selector'),selector_model:oldModel('old-selector')}),launched=h.retryFailed(first.id);
  for(let index=0;index<200&&h.active.has(launched.id);index++)await new Promise(resolve=>setTimeout(resolve,5));const retry=h.get(launched.id);assert.equal(first.status,'failed');assert.equal(retry.status,'completed');
  for(const key of ['model','answer_model','judge_model','scoring_judge_model','medlocomo_judge_model','cpcd_judge_model','query_planner_model','state_selector_model','selector_model'])assert.equal(Object.hasOwn(retry.config,key),false,key);
  for(const key of ['global','query_planner','judge','scoring_judge','medlocomo_judge','cpcd_judge'])assert.ok(retry.config.resolved_models[key],key);
  assert.ok(calls.some(item=>item.model==='current-pipeline'&&item.component==='extractor'));assert.ok(calls.some(item=>item.model==='current-planner'&&item.component==='query_planner'));assert.equal(calls.some(item=>item.component==='state_selector'),false);assert.ok(calls.some(item=>item.model==='current-answer'&&item.component==='judge'));assert.equal(calls.some(item=>item.model.startsWith('old-')),false);s.close();
});
test('background launch freezes creation-time Pipeline, Planner, original Answer and scoring Judge gateways',async()=>{
  const s=new Store(':memory:'),calls=[],makeSet=label=>({pipeline:new RecordingGateway(`${label}-pipeline`,calls),planner:new RecordingGateway(`${label}-planner`,calls),answer:new RecordingGateway(`${label}-answer`,calls),scoringJudge:new RecordingGateway(`${label}-scoring-judge`,calls)}),sets={A:makeSet('A'),B:makeSet('B')};let current='A';
  const registry={pipelineOptions:()=>({gateway:sets[current].pipeline}),assignmentSnapshot:()=>({global:{...sets[current].pipeline.config},extractor:{...sets[current].pipeline.config},router:{...sets[current].pipeline.config},query_planner:{...sets[current].planner.config},judge:{...sets[current].answer.config},scoring_judge:{...sets[current].scoringJudge.config}}),gateway:component=>component==='judge'?sets[current].answer:component==='scoring_judge'?sets[current].scoringJudge:sets[current].planner},h=new ExperimentHarness(s,undefined,registry),observations=[{subject_id:'launch-model-freeze',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}];
  h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-launch-freeze',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};
  const launched=h.launch('synthetic',{max_queries:1});current='B';
  for(let index=0;index<200&&h.active.has(launched.id);index++)await new Promise(resolve=>setTimeout(resolve,5));
  const done=h.get(launched.id),memoryResult=done.results.find(item=>item.run_id),run=s.getRun(memoryResult.run_id);
  assert.equal(done.status,'completed');
  assert.equal(done.config.resolved_models.global.model,'A-pipeline');
  assert.equal(run.config.model.model,'A-pipeline');
  for(const component of ['extractor','router','query_planner','judge'])assert.ok(calls.some(item=>item.model.startsWith('A-')&&item.component===component),component);
  assert.equal(calls.some(item=>item.component==='state_selector'),false);
  assert.equal(calls.some(item=>item.model.startsWith('B-')),false);
  s.close();
});
test('unexpected scoring errors terminalize start runs without losing completed results or diagnostics',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),observations=[{subject_id:'unexpected-start',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}],preservedQuery={score_id:'q-preserved',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}},brokenQuery={score_id:'q-unexpected',task:'state_update',question:'这道题会触发意外错误。',gold:['偏高']};Object.defineProperty(brokenQuery,'metadata',{get(){throw new Error('unexpected scoring explosion')}});h.adapters.synthetic={load:()=>({observations}),cases:()=>[preservedQuery,brokenQuery],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const done=await h.start('synthetic',{max_observations:1,max_queries:2}),fatal=done.results.find(item=>item.kind==='experiment_error');assert.equal(done.status,'failed');assert.equal(h.active.has(done.id),false);assert.equal(done.progress.phase,'finished');assert.equal(done.progress.current,null);assert.equal(done.progress.scoring_current,null);assert.equal(done.progress.eta_seconds,0);assert.equal(done.progress.preprocess_active,0);assert.equal(done.progress.scored,1);assert.equal(done.progress.query_failed,1);assert.equal(done.progress.memory_build_completeness.status,'complete');assert.equal(done.progress.memory_build_completeness.memory_incomplete,false);assert.equal(done.results.filter(item=>item.run_id&&item.status==='completed').length,1);assert.equal(done.results.find(item=>item.kind==='score')?.score_id,'q-preserved');assert.equal(fatal.status,'failed');assert.equal(fatal.phase,'scoring');assert.equal(fatal.error.message,'unexpected scoring explosion');assert.equal(done.progress.fatal_error.message,'unexpected scoring explosion');const retry=h.retryFailed(done.id);assert.equal(retry.config.max_observations,1);assert.equal(retry.config.max_queries,2);h.control(retry.id,'cancel');for(let index=0;index<100&&h.active.has(retry.id);index++)await new Promise(resolve=>setTimeout(resolve,5));s.close()});
test('unexpected scoring errors terminalize background launches through the same execution path',async()=>{const s=new Store(':memory:'),h=new ExperimentHarness(s),observations=[{subject_id:'unexpected-launch',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}],query={score_id:'q-launch-error',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}};let caseCalls=0;h.adapters.synthetic={load:()=>({observations}),cases:()=>{caseCalls++;if(caseCalls===2)throw new Error('background scoring explosion');return[query]},normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const launched=h.launch('synthetic',{max_queries:1});for(let index=0;index<200&&h.active.has(launched.id);index++)await new Promise(resolve=>setTimeout(resolve,5));const done=h.get(launched.id),fatal=done.results.find(item=>item.kind==='experiment_error');assert.equal(h.active.has(launched.id),false);assert.equal(done.status,'failed');assert.equal(done.progress.phase,'finished');assert.equal(done.progress.eta_seconds,0);assert.equal(done.progress.query_failed,1);assert.equal(done.results.filter(item=>item.run_id&&item.status==='completed').length,1);assert.equal(fatal.error.message,'background scoring explosion');s.close()});
test('queries with a visible memory-build failure are skipped and exported with full diagnostics',async()=>{const s=new Store(':memory:'),gateway=new FailOnceGateway(),registry={pipelineOptions:()=>({gateway}),assignmentSnapshot:()=>({global:{provider:'mock',model:'delayed-mock'}}),gateway:()=>gateway},h=new ExperimentHarness(s,undefined,registry),observations=[{subject_id:'incomplete-memory',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2024-01-01',raw_text:'我的血糖持续偏高。'}];h.adapters.synthetic={load:()=>({observations}),cases:()=>[{score_id:'q-incomplete',task:'state_update',question:'患者目前的血糖状态是什么？',gold:['偏高'],metadata:{visible_episode_ids:['session-1'],query_session:1,answer_contract:{language:'zh-CN',format:'简短状态'}}}],normalizeAnswer:value=>value,compatibleScore:()=>({score:1,is_correct:true,method:'test'})};const done=await h.start('synthetic',{}),score=done.results.find(item=>item.kind==='score');assert.equal(done.status,'failed');assert.equal(done.progress.memory_build_completeness.memory_incomplete,true);assert.equal(score.status,'skipped');assert.equal(score.memory_incomplete,true);assert.equal(score.scoring_method,'memory_incomplete');assert.equal(score.raw_judge_output,null);assert.equal(score.retrieval_trace.memory_incomplete,true);assert.equal(score.retrieval_trace.memory_completeness.failed_episode_ids[0],'session-1');assert.equal(done.progress.retrieval_metrics.memory_incomplete_queries,1);assert.equal(done.progress.retrieval_metrics.candidate_zero_recall_queries,1);const exported=h.wrongAnswerExport(done.id),item=exported.wrong_answers[0];assert.equal(exported.export_version,3);assert.equal(exported.summary.memory_incomplete_count,1);assert.equal(item.memory_incomplete,true);assert.equal(item.related_memory_build_failures.length,1);assert.deepEqual(item.score_result.memory_completeness,score.memory_completeness);assert.ok(item.retrieval_context);s.close()});
