import test from'node:test';
import assert from'node:assert/strict';
import{applyInvestigationAssessment,contextualizeMemory,investigationAssessmentInput,refineWorkingMemory,sanitizeInvestigationAssessment,searchMemory,traceMemoryGraph,verifyWorkingMemory}from'../src/careharness-actions.js';

const node=(id,text,extra={})=>({memory_id:id,observation_id:`o-${id}`,subject_id:'p',text,source_type:'patient',episode_id:`session-${id}`,turn_id:'1',event_time:'2025-01-01',certainty:1,polarity:'affirmed',families:['PE'],factor_key:`factor:${id}`,status:'active',version:1,version_chain:[],...extra});
const edge=(from,to)=>({edge_id:`${from}-${to}`,subject_id:'p',from_memory_id:from,to_memory_id:to,edge_family:'temporal',relation_type:'updates',support_memory_ids:[from,to],status:'verified',confidence:1,persistent:true,causal_claim:false});

test('search follows only its step-local instruction',()=>{
  const nodes=[node('m1','患者空腹血糖为 9 mmol/L。'),node('m2','患者睡眠稳定。')],request={question:'原始问题保持不解析'};
  assert.equal(searchMemory(request,nodes,[],{objective:'查找空腹血糖'}).memory_nodes[0].memory_id,'m1');
  assert.equal(searchMemory(request,nodes,[],{}).memory_nodes.length,0);
});

test('context retrieves complete visible Sessions around a selected aspect',()=>{const result=contextualizeMemory({question:'Q'},[node('a','患者血糖升高。',{episode_id:'session-1'}),node('b','医生建议复查血糖。',{episode_id:'session-1',source_type:'doctor'}),node('c','患者睡眠稳定。',{episode_id:'session-2'})],{objective:'调查血糖'});assert.equal(result.anchors[0].episode_id,'session-1');assert.deepEqual(new Set(result.memory_nodes.map(item=>item.memory_id)),new Set(['a','b']));});

test('trace follows verified graph links and optionally the same factor',()=>{const nodes=[node('a','初始指标。',{factor_key:'glucose'}),node('b','后续指标。',{factor_key:'glucose'}),node('c','无关记录。')],result=traceMemoryGraph(nodes,[edge('a','b')],[nodes[0]],{seed_memory_ids:['a'],depth:1,include_same_factor:true});assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['a','b']);assert.deepEqual(result.memory_edges.map(item=>item.edge_id),['a-b']);});

test('trace finds the shortest available path toward a policy-selected semantic endpoint',()=>{const nodes=[node('a','患者初始指标异常。'),node('b','患者开始规律治疗。'),node('c','治疗后指标仍持续恶化。'),node('d','无关睡眠记录。')],result=traceMemoryGraph(nodes,[edge('a','b'),edge('b','c')],[nodes[0]],{seed_memory_ids:['a'],target_terms:['持续恶化'],depth:3,include_same_factor:false,include_same_concept:false,max_paths:1});assert.deepEqual(result.trace.shortest_paths,[{target_memory_id:'c',memory_ids:['a','b','c'],edge_ids:['a-b','b-c'],navigation_step_count:2}]);assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['a','b','c']);assert.equal(result.trace.navigation_paths[0].semantics,'navigation_only_non_causal');assert.equal(result.trace.navigation_paths[0].establishes_patient_fact,false);assert.deepEqual(result.trace.navigation_paths[0].navigation_links.map(link=>[link.link_kind,link.pseudo,link.establishes_causal_relation]),[['verified_graph_edge',false,false],['verified_graph_edge',false,false]]);});

test('trace labels same-factor navigation as a pseudo link rather than a patient or causal fact',()=>{const nodes=[node('a','早期血糖异常。',{factor_key:'glucose'}),node('b','后期血糖继续升高。',{factor_key:'glucose'})],result=traceMemoryGraph(nodes,[],[nodes[0]],{seed_memory_ids:['a'],target_memory_ids:['b'],depth:1,include_same_factor:true,include_same_concept:false});const link=result.trace.navigation_paths[0].navigation_links[0];assert.equal(link.link_kind,'same_factor_bridge');assert.equal(link.pseudo,true);assert.equal(link.establishes_patient_fact,false);assert.equal(link.establishes_causal_relation,false);assert.deepEqual(result.memory_edges,[]);});

test('trace deterministically applies both temporal gate and persistent refinement boundary',()=>{const nodes=[node('allowed','目标日记录。',{event_time:'2024-01-16',factor_key:'x'}),node('excluded','目标日但已被 Refine 排除。',{event_time:'2024-01-16',factor_key:'x'}),node('outside','时间窗外记录。',{event_time:'2024-02-20',factor_key:'x'})],result=traceMemoryGraph(nodes,[edge('allowed','excluded'),edge('allowed','outside')],nodes,{seed_memory_ids:['allowed'],depth:2,include_same_factor:true},{temporal_gate:{hard:true,start_date:'2024-01-16',end_date:'2024-02-15'},refinement_boundary:{boundary_id:'r1',excluded_memory_ids:['excluded'],temporal:{start_date:'2024-01-01',end_date:'2024-01-31'}}});assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['allowed']);assert.deepEqual(result.memory_edges,[]);assert.equal(result.trace.temporal_gate.start_date,'2024-01-16');assert.deepEqual(result.trace.refinement_boundary.excluded_memory_ids,['excluded']);});

test('semantic assessor input contains Memory Nodes and no static slots',()=>{const input=investigationAssessmentInput({question:'为什么变化？'},{memory_nodes:[node('a','患者指标升高。')],memory_edges:[]},{objective:'检查变化原因'}),raw=JSON.stringify(input);assert.equal(input.nodes[0].memory_id,'a');assert.doesNotMatch(raw,/node_blueprint|slot_id|state_id|evidence_id/);});

test('semantic assessor receives navigation paths with an explicit non-evidence contract',()=>{const navigation_paths=[{target_memory_id:'b',memory_ids:['a','b'],navigation_step_count:1,navigation_links:[{from_memory_id:'a',to_memory_id:'b',link_kind:'same_factor_bridge',pseudo:true}]}],input=investigationAssessmentInput({question:'为什么变化？'},{memory_nodes:[node('a','指标升高。'),node('b','治疗调整。')],memory_edges:[],navigation_paths},{objective:'检查关系'});assert.equal(input.navigation_paths[0].semantics,'navigation_only_non_causal');assert.equal(input.navigation_paths[0].navigation_links[0].pseudo,true);assert.match(input.navigation_path_policy,/not patient evidence/);});

test('semantic assessor distinguishes documentation date from a matched relative clinical target',()=>{const temporal_gate={hard:true,kind:'relative_documentation_window',anchor_date:'2024-01-15',target_date:'2024-01-16',start_date:'2024-01-16',end_date:'2024-02-15'},input=investigationAssessmentInput({question:'患者在2024-01-15次日测得的空腹血糖值是多少？'},{temporal_gate,memory_nodes:[node('target','患者回忆餐后血糖约 11 mmol/L，次日空腹血糖为 12-13 mmol/L。',{event_time:'2024-01-20'}),node('distractor','第二天空腹血糖升高，整天只剩 20% 电量。',{event_time:'2024-01-21'})],memory_edges:[]},{objective:'判断目标值'});assert.equal(input.nodes[0].recorded_at,'2024-01-20');assert.equal(input.nodes[0].event_time_semantics,'documentation_or_session_date');assert.equal(input.temporal_target.documentation_date_need_not_equal_target_date,true);assert.deepEqual(input.nodes[0].temporal_target_match.measurements,['12-13 mmol/L']);assert.equal(input.nodes[1].temporal_target_match,null);assert.equal(input.temporal_target.candidate_matches.length,1);assert.equal(input.temporal_target.candidate_matches[0].target_date,'2024-01-16');});

test('assessment keeps grounded query-time connections separate from persistent graph edges',()=>{const baseline={memory_nodes:[node('a','A'),node('b','B')],memory_edges:[]},output=applyInvestigationAssessment({question:'Q'},baseline,{assessment:'supported',relevant_memory_ids:['a','missing'],covered_aspects:['A 后出现 B'],connections:[{from_memory_id:'a',to_memory_id:'b',relation_type:'associated_with',assessment:'supports',supporting_memory_ids:['a','b','missing'],confidence:.9},{from_memory_id:'a',to_memory_id:'missing',assessment:'supports'}],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.relevant_memory_ids,['a']);assert.deepEqual(output.semantic_evaluation.connections[0].supporting_memory_ids,['a','b']);assert.equal(output.semantic_evaluation.connections[0].provenance_scope,'query_time_assessment_only');assert.equal(output.semantic_evaluation.connections[0].establishes_graph_fact,false);assert.deepEqual(output.memory_edges,[]);assert.deepEqual(output.working_memory.memory_edges,[]);assert.equal(output.working_memory.assessed_connections.length,1);assert.equal(output.working_memory.assessment,'supported');});

test('assessment hands off only grounded answer-focus items',()=>{const baseline={memory_nodes:[node('a','当前值为 8 mmol/L。'),node('b','旧值为 10 mmol/L。')],memory_edges:[]},output=applyInvestigationAssessment({question:'当前值是多少？'},baseline,{assessment:'supported',relevant_memory_ids:['a'],covered_aspects:['当前值'],answer_focus:[{aspect:'当前值为 8 mmol/L',role:'current',memory_ids:['a','missing'],required_in_answer:true},{aspect:'无依据',role:'target',memory_ids:['missing']}],connections:[],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.answer_focus,[{aspect:'当前值为 8 mmol/L',role:'current',source_refs:['memory:a'],memory_ids:['a'],required_in_answer:true}]);assert.deepEqual(output.working_memory.answer_focus,output.semantic_evaluation.answer_focus);assert.equal(output.working_memory.version,'careharness-working-memory.v7-claim-grounded');});

test('assessment rejects a whole claim when only one value or short phrase is grounded',()=>{const baseline={memory_nodes:[node('a','患者当前指标为 8 unit/L。')],memory_edges:[]},output=applyInvestigationAssessment({question:'目前情况如何？'},baseline,{assessment:'supported',answer_focus:[{aspect:'患者开始 REGIMEN-Z 后指标为 8 unit/L，并已确诊 DXQ',memory_ids:['a']}],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.answer_focus,[]);assert.equal(output.semantic_evaluation.assessment,'partial');assert.match(output.semantic_evaluation.missing_information[0],/not fully supported/);});

test('assessment protects negation and accepts a faithful multi-phrase summary',()=>{const baseline={memory_nodes:[node('weight','患者两个月内体重下降约 5 kg，并且仍在持续掉重。'),node('glucose','患者有低血糖发作，血糖为 3.2 mmol/L。')],memory_edges:[]},output=applyInvestigationAssessment({question:'有哪些重要变化？'},baseline,{assessment:'supported',answer_focus:[{aspect:'患者两个月体重持续下降约 5 kg',memory_ids:['weight']},{aspect:'患者没有低血糖发作，血糖为 3.2 mmol/L',memory_ids:['glucose']}],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.answer_focus.map(item=>item.memory_ids),[['weight']]);});

test('assessment rejects high-overlap claims whose clinical direction is reversed',()=>{const baseline={memory_nodes:[node('trend','患者指标由 6 升高到 8，其他记录保持不变。'),node('usage','患者方案甲已开始使用，其他记录保持不变。'),node('status','患者总体状态在本周之后明显改善，且其他方面稳定。'),node('amount','患者方案用量仍然不足，且需要后续复查。')],memory_edges:[]},output=applyInvestigationAssessment({question:'这些状态是什么？'},baseline,{assessment:'supported',answer_focus:[{aspect:'患者指标由 6 升高到 8，其他记录保持不变',memory_ids:['trend']},{aspect:'患者指标由 6 下降到 8，其他记录保持不变',memory_ids:['trend']},{aspect:'患者方案甲已停止使用，其他记录保持不变',memory_ids:['usage']},{aspect:'患者总体状态在本周之后明显恶化，且其他方面稳定',memory_ids:['status']},{aspect:'患者方案用量仍然过量，且需要后续复查',memory_ids:['amount']}],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.answer_focus.map(item=>item.memory_ids),[['trend']]);assert.equal(output.semantic_evaluation.assessment,'partial');});

test('assessment keeps sourced patient facts and explicit generic bridges but rejects fabricated protected facts',()=>{const baseline={memory_nodes:[node('diagnosis','患者已确诊 DXQ，MARKER+++ 阳性。'),node('response','患者的方案甲疗效已明显减弱。')],memory_edges:[]},output=applyInvestigationAssessment({question:'这些信息如何联系？'},baseline,{assessment:'supported',answer_focus:[],reasoning_hypotheses:[{hypothesis_id:'fact',grounding_scope:'source_supported_patient_fact',summary:'患者已确诊 DXQ 且 MARKER+++ 阳性',supporting_memory_ids:['diagnosis']},{hypothesis_id:'fabricated',grounding_scope:'source_supported_patient_fact',summary:'患者指标 X 为 0.2 unitX',supporting_memory_ids:['diagnosis']},{hypothesis_id:'bridge',grounding_scope:'generic_clinical_bridge',summary:'一般而言，进行性细胞功能下降可能使既有方案疗效减弱。',supporting_memory_ids:['diagnosis','response']},{hypothesis_id:'generic-patient-event',grounding_scope:'generic_clinical_bridge',summary:'一般而言，患者已经开始 REGIMEN-Z 治疗。',supporting_memory_ids:['diagnosis']}],missing_information:[]});assert.deepEqual(output.semantic_evaluation.reasoning_hypotheses.map(item=>item.hypothesis_id),['fact','bridge']);assert.equal(output.semantic_evaluation.reasoning_hypotheses[0].establishes_patient_fact,true);assert.equal(output.semantic_evaluation.reasoning_hypotheses[1].establishes_patient_fact,false);assert.equal(output.semantic_evaluation.reasoning_hypotheses[1].grounding_scope,'generic_clinical_bridge');assert.equal(output.semantic_evaluation.assessment,'partial');});

test('state projection deletes baseline/current distinctions and assessor hypotheses',()=>{const baseline={memory_nodes:[node('march','患者近期出现明显的早晨疲劳、脑雾加重及起床困难。'),node('april','患者仍感脑雾。')],memory_edges:[]},input=investigationAssessmentInput({question:'患者24年3月的脑雾症状相比两周前发生了什么变化？'},baseline,{objective:'选择问题目标状态'},{target_only_focus_roles:true,allow_reasoning_hypotheses:false}),output=applyInvestigationAssessment({question:'患者24年3月的脑雾症状相比两周前发生了什么变化？'},baseline,{assessment:'supported',relevant_memory_ids:['march'],covered_aspects:['脑雾加重'],answer_focus:[{aspect:'患者近期出现明显的早晨疲劳、脑雾加重及起床困难',role:'baseline',memory_ids:['march'],required_in_answer:true}],reasoning_hypotheses:[{summary:'无法判断变化',supporting_memory_ids:['april']}],missing_information:[]},{target_only_focus_roles:true});assert.equal(input.focus_role_policy.includes('do not use baseline or current'),true);assert.equal(input.output_schema.answer_focus[0].role,'target');assert.deepEqual(input.output_schema.reasoning_hypotheses,[]);assert.equal(output.semantic_evaluation.answer_focus[0].role,'target');assert.deepEqual(output.semantic_evaluation.reasoning_hypotheses,[]);});

test('exact relative target consistency repair rejects an erroneous baseline label',()=>{const temporal_gate={hard:true,kind:'relative_documentation_window',anchor_date:'2024-01-15',target_date:'2024-01-16',start_date:'2024-01-16',end_date:'2024-02-15'},baseline={temporal_gate,memory_nodes:[node('target','患者自述最近几天未监测血糖；回忆上周餐后血糖约 11 mmol/L，次日空腹血糖 12-13 mmol/L。',{event_time:'2024-01-20'})],memory_edges:[]},output=applyInvestigationAssessment({question:'患者在2024-01-15次日测得的空腹血糖值是多少？'},baseline,{assessment:'unresolved',relevant_memory_ids:['target'],covered_aspects:['存在回忆值'],answer_focus:[{aspect:'次日空腹血糖 12-13 mmol/L',role:'baseline',source_refs:['memory:target']}],connections:[],reasoning_hypotheses:[],missing_information:['缺少2024-01-16当天的空腹血糖值']},{exact_entity:true});assert.equal(output.semantic_evaluation.assessment,'supported');assert.deepEqual(output.semantic_evaluation.missing_information,[]);assert.deepEqual(output.semantic_evaluation.relevant_memory_ids,['target']);assert.equal(output.semantic_evaluation.answer_focus[0].role,'target');assert.deepEqual(output.semantic_evaluation.temporal_target_matches[0].measurements,['12-13 mmol/L']);});

test('temporal consistency repair does not promote a later value without a relative-time link',()=>{const temporal_gate={hard:true,kind:'relative_documentation_window',anchor_date:'2024-01-15',target_date:'2024-01-16',start_date:'2024-01-16',end_date:'2024-02-15'},baseline={temporal_gate,memory_nodes:[node('later','患者本次空腹血糖为 9 mmol/L。',{event_time:'2024-01-20'})],memory_edges:[]},output=applyInvestigationAssessment({question:'患者在2024-01-15次日测得的空腹血糖值是多少？'},baseline,{assessment:'unresolved',answer_focus:[{aspect:'本次空腹血糖为 9 mmol/L',role:'baseline',memory_ids:['later']}],missing_information:['缺少目标日数值']},{exact_entity:true});assert.equal(output.semantic_evaluation.assessment,'unresolved');assert.equal(output.semantic_evaluation.answer_focus[0].role,'baseline');assert.equal(output.semantic_evaluation.temporal_target_matches,undefined);});

test('assessment can cite matching Profile and recent Session facts but rejects mismatched citations',()=>{const baseline={patient_profile:{sections:[{items:[{source_ref:'memory:p1',text:'患者近期体重下降约 5 kg。'}]}]},recent_sessions:[{episode_id:'session-9',transcript:'患者：最近口渴和尿频明显加重。'}],memory_nodes:[],memory_edges:[]},output=applyInvestigationAssessment({question:'目前风险如何？'},baseline,{assessment:'supported',answer_focus:[{aspect:'患者近期体重下降约 5 kg',source_refs:['memory:p1']},{aspect:'患者最近口渴和尿频明显加重',source_refs:['session:session-9']},{aspect:'患者已经恢复正常',source_refs:['memory:p1']}],reasoning_hypotheses:[],missing_information:[]});assert.deepEqual(output.semantic_evaluation.answer_focus.map(item=>item.source_refs),[['memory:p1'],['session:session-9']]);});

test('assessment annotates relevance without deleting candidates above an answer limit',()=>{const baseline={memory_nodes:[node('a','A'),node('b','B'),node('c','C')],memory_edges:[]},output=applyInvestigationAssessment({question:'Q'},baseline,{assessment:'supported',relevant_memory_ids:['c'],covered_aspects:['C'],connections:[],reasoning_hypotheses:[],missing_information:[]},{answer_memory_limit:1});assert.deepEqual(output.memory_nodes.map(item=>item.memory_id),['a','b','c']);assert.equal(output.verification,null);assert.deepEqual(output.semantic_evaluation.relevant_memory_ids,['c']);});

test('refine replaces broad current information with explicit grounded Memory IDs',()=>{const nodes=[node('a','目标信息。'),node('b','干扰信息。')],result=refineWorkingMemory({question:'Q'},nodes,[],{memory_ids:['a']});assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['a']);assert.deepEqual(result.trace.removed_memory_ids,['b']);});

test('conservative state Refine treats selected IDs as priorities and removes only hard temporal mismatches',()=>{const nodes=[node('preferred','被 Assessor 选中的状态。',{event_time:'2024-03-27'}),node('also-relevant','同月另一条可能相关的状态。',{event_time:'2024-03-10'}),node('wrong-time','时间范围外的状态。',{event_time:'2024-04-01'})],result=refineWorkingMemory({question:'患者24年3月的状态是什么？'},nodes,[],{memory_ids:['preferred'],temporal:{operator:'range',start_date:'2024-03-01',end_date:'2024-03-31',prefer:'latest'}},{conservative:true,limit:3});assert.deepEqual(new Set(result.memory_nodes.map(item=>item.memory_id)),new Set(['preferred','also-relevant']));assert.deepEqual(result.trace.removed_memory_ids,['wrong-time']);assert.deepEqual(result.trace.protected_memory_ids,['preferred']);assert.equal(result.trace.removal_policy,'hard_temporal_mismatch_only');});

test('verification enforces one patient and bounded unique Memory IDs',()=>{const duplicate=node('a','A'),other=node('x','X',{subject_id:'other'}),result=verifyWorkingMemory([duplicate,duplicate,node('b','B'),other],[edge('a','b')],{limit:2});assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['a','b']);assert.equal(result.memory_edges.length,1);});

test('verification rejects graph edges whose support references an unselected Memory Node',()=>{const invalid={...edge('a','b'),edge_id:'invalid-support',support_memory_ids:['a','b','c']},result=verifyWorkingMemory([node('a','A'),node('b','B')],[invalid],{limit:2});assert.deepEqual(result.memory_edges,[]);assert.deepEqual(result.rejected_edge_ids,['invalid-support']);assert.equal(result.complete,true);});

test('verification reports overflow without silently truncating valid Memory Nodes',()=>{const result=verifyWorkingMemory([node('a','A'),node('b','B'),node('c','C')],[],{limit:2});assert.deepEqual(result.memory_nodes.map(item=>item.memory_id),['a','b','c']);assert.equal(result.complete,false);assert.equal(result.overflow,true);assert.equal(result.overflow_count,1);assert.equal(result.requires_refine,true);});

test('assessor sanitizer preserves uncertainty and rejects self-links',()=>{const clean=sanitizeInvestigationAssessment({assessment:'partial',relevant_memory_ids:['a'],covered_aspects:['已知 A'],connections:[{from_memory_id:'a',to_memory_id:'a'},{from_memory_id:'a',to_memory_id:'b',assessment:'unresolved',confidence:.7}],reasoning_hypotheses:[{summary:'可能相关',supporting_memory_ids:['a'],confidence:.6}],missing_information:['缺少后续记录']});assert.equal(clean.connections.length,1);assert.equal(clean.connections[0].assessment,'unresolved');assert.equal(clean.reasoning_hypotheses[0].supporting_memory_ids[0],'a');});

test('task strategy controls the bounded answer-focus capacity instead of one global eight-item cap',()=>{const answer_focus=Array.from({length:18},(_,index)=>({aspect:`事实 ${index}`,memory_ids:[`m${index}`]})),input=investigationAssessmentInput({question:'为什么会这样？'},{memory_nodes:[],memory_edges:[]},{objective:'检查完整链'},{answer_focus_limit:16}),wide=sanitizeInvestigationAssessment({assessment:'supported',answer_focus},{answer_focus_limit:16}),narrow=sanitizeInvestigationAssessment({assessment:'supported',answer_focus},{answer_focus_limit:2});assert.equal(input.answer_focus_limit,16);assert.match(input.output_schema.answer_focus[0].aspect,/at most 16/);assert.equal(wide.answer_focus.length,16);assert.equal(narrow.answer_focus.length,2);});

test('assessor cannot declare supported while decision-changing information is missing',()=>{const clean=sanitizeInvestigationAssessment({assessment:'supported',missing_information:['缺少治疗反应']});assert.equal(clean.assessment,'partial');assert.deepEqual(clean.missing_information,['缺少治疗反应']);});
