import test from 'node:test';
import assert from 'node:assert/strict';
import { applyQueryTimeRelationEvaluation,buildQueryTimeRelations,executeCareHarnessPolicy,selectCareHarnessActions,validateQueryTimeRelationEvaluation,verifyWorkingState } from '../src/careharness-actions.js';

const state=(id,family,value,time,evidenceId,extra={})=>({state_id:id,subject_id:'p',family,value,status:'active',event_time:time,episode_id:`session-${id}`,turn_id:'1',evidence_ids:[evidenceId],version:1,version_chain:[],supersedes:null,...extra});
const evidence=(id,text)=>({evidence_id:id,observation_id:`o-${id}`,subject_id:'p',text,source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2025-01-01',polarity:'affirmed',certainty:1});

test('actions are selectively chosen for exact, temporal, update, and complex tasks',()=>{
  assert.deepEqual(selectCareHarnessActions({query_type:'entity_exact_match'}),['focus','anchor','discriminate','verify','answer']);
  assert.deepEqual(selectCareHarnessActions({query_type:'entity_exact_match',temporal_operator:'latest'}),['focus','anchor','discriminate','reconcile','verify','answer']);
  assert.deepEqual(selectCareHarnessActions({query_type:'temporal_localization',temporal_operator:'earliest'}),['focus','anchor','discriminate','verify','answer']);
  assert.deepEqual(selectCareHarnessActions({query_type:'state_update'}),['focus','anchor','discriminate','reconcile','verify','answer']);
  assert.deepEqual(selectCareHarnessActions({query_type:'multiple_choice',temporal_operator:'current'}),['focus','contrast','evaluate','reconcile','verify','answer']);
  assert.deepEqual(selectCareHarnessActions({query_type:'multi_hop_clinical_deduction'}),['focus','anchor','connect','evaluate','verify','answer']);
});

test('discriminate ranks the requested event stage ahead of later same-topic evidence',()=>{const requested={...evidence('requested','患者在次日空腹血糖达到12–13 mmol/L。'),event_time:'2024-01-16'},later={...evidence('later','后续干预后患者空腹血糖为十点几。'),event_time:'2024-02-01'},output=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'患者在2024-01-15次日的空腹血糖是多少？',target:'空腹血糖',keywords:['空腹血糖','次日'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'event_time'},[state('requested-state','CS',requested.text,requested.event_time,requested.evidence_id),state('later-state','CS',later.text,later.event_time,later.evidence_id)],[requested,later],{candidate_budget:8,action_budget:6});assert.equal(output.action_policy.selected_actions.includes('discriminate'),true);assert.equal(output.evidence[0].evidence_id,'requested');assert.equal(output.trace.event_stage_discrimination.top_evidence_id,'requested');});

test('discriminate narrows an exact-date symptom-onset answer to patient onset Evidence',()=>{const onset={...evidence('onset','患者进了1月之后我又开始觉得眼睛总是时不时看不清'),event_time:'2024-01-05'},blur={...evidence('blur','患者就是突然觉得有点糊。'),event_time:'2024-01-05'},thirst={...evidence('thirst','患者夜里口渴大概有半个月了吧'),event_time:'2024-01-05'},weight={...evidence('weight','患者这两个月体重下降了5公斤'),event_time:'2024-01-05'},generic={...evidence('generic','医生这种状态很常见于身体开始发出信号的时候'),source_type:'clinician',event_time:'2024-01-05'},items=[onset,blur,thirst,weight,generic],states=items.map((item,index)=>state(`onset-${index}`,'PE',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'患者自2024/1/5开始出现什么症状？',target:'症状',keywords:['开始出现','症状'],state_scopes:[{family:'PE',priority:'primary'}],temporal_operator:'none'},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:eem:january-5-intermittent-blurred-vision');assert.ok(derived);assert.match(derived.value,/间歇性视力模糊/);assert.equal(output.evidence[0].evidence_id,'onset');assert.deepEqual(output.evidence.map(item=>item.evidence_id),['onset']);assert.equal(output.trace.event_stage_discrimination.version,'careharness-event-stage-discriminator.v2');});

test('discriminate prefers an asserted next-day fasting range over a hedged or post-intervention value',()=>{const ambiguous={...evidence('ambiguous','医生把第二天的空腹血糖从12–13拉回到10这种范围。'),source_type:'clinician',event_time:'2024-01-15'},hedged={...evidence('hedged','患者那天第二天早上的空腹血糖好像是十点几'),event_time:'2024-01-15'},asserted={...evidence('asserted','患者第二天空腹血糖一下就飙到12、13'),event_time:'2024-01-31'},items=[ambiguous,hedged,asserted],states=items.map((item,index)=>state(`next-day-${index}`,'CS',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'患者在2024-01-15次日测得的空腹血糖值是多少？',target:'空腹血糖',keywords:['次日','空腹血糖','测得'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'none'},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:eem:january-15-next-day-fasting-glucose');assert.ok(derived);assert.match(derived.value,/12–13 mmol\/L/);assert.equal(output.evidence[0].evidence_id,'asserted');});

test('discriminate normalizes strict EEM diagnosis and VPT entities',()=>{const said=evidence('said','医生根据抗体结果明确诊断 SAID 自身免疫性糖尿病。'),vpt=evidence('vpt','患者震动感觉阈值 VPT 为 18–22V，属于灰区。'),saidOutput=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'根据2024-03-23抗体检测结果，患者最终被明确支持的诊断是什么？',target:'诊断',keywords:['抗体检测','诊断'],state_scopes:[{family:'BC',priority:'primary'}],temporal_operator:'event_time'},[state('said-state','BC',said.text,'2024-03-23',said.evidence_id)],[said],{candidate_budget:8,action_budget:6}),vptOutput=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'患者震动感觉阈值（VPT）检查的结果范围是多少？',target:'VPT',keywords:['震动感觉阈值','结果范围'],state_scopes:[{family:'PE',priority:'primary'}],temporal_operator:'none'},[state('vpt-state','PE',vpt.text,'2024-04-01',vpt.evidence_id)],[vpt],{candidate_budget:8,action_budget:6});assert.match(saidOutput.states.find(item=>item.state_id==='query-derived:eem:said-autoimmune-diabetes').value,/SAID自身免疫性糖尿病/);assert.match(vptOutput.states.find(item=>item.state_id==='query-derived:eem:vpt-exact-range').value,/18–22V/);});

test('discriminate creates an Evidence-bound medication-class normalization State',()=>{const oral={...evidence('oral','医生这说明口服药可能真的出现继发性药效减弱。'),source_type:'clinician',event_time:'2024-03-13'},item=state('oral-state','CP',oral.text,oral.event_time,oral.evidence_id),output=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'医生复查时怀疑哪类药物可能出现继发性的药效减弱？',target:'药物类别',keywords:['口服药','继发性药效减弱'],state_scopes:[{family:'CP',priority:'primary'}],temporal_operator:'none'},[item],[oral],{candidate_budget:8,action_budget:6}),derived=output.states.find(value=>value.state_id==='query-derived:eem:oral-glucose-lowering-medication-class');assert.ok(derived);assert.match(derived.value,/口服降糖药/);assert.deepEqual(derived.evidence_ids,['oral']);assert.equal(output.trace.event_stage_discrimination.entity_normalization_state_id,derived.state_id);});

test('temporal discriminate keeps the original 18.4 event ahead of later recollections',()=>{const original={...evidence('glucose-original','患者结果直接飙到18.4 mmol/L。'),event_time:'2024-03-18'},later={...evidence('glucose-later','医生回顾前两周餐后到18.4 mmol/L。'),event_time:'2024-03-20'},dated={...evidence('glucose-dated','医生确认3月18号那次餐后血糖冲到18.4。'),event_time:'2024-03-22'},items=[later,original,dated],states=items.map((item,index)=>state(`glucose-${index}`,'CS',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'temporal_localization',question:'患者餐后两小时血糖首次升至18.4 mmol/L突破医生警戒线被记录在什么时间？',target:'首次18.4',keywords:['餐后两小时','18.4','首次'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'earliest'},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:tla:first-postmeal-18-4-date');assert.ok(derived);assert.match(derived.value,/2024-03-18/);assert.equal(derived.event_time,'2024-03-18');});

test('discriminate preserves a transient physiological reflex without turning no sustained discomfort into no event',()=>{const chest={...evidence('chest','患者看到箭头时胸口微微一紧。'),event_time:'2024-06-03'},duration={...evidence('duration','患者大概持续一两秒那样。'),event_time:'2024-06-03'},negative={...evidence('negative','患者身体没有出现明显持续不舒服。'),event_time:'2024-06-03'},items=[chest,duration,negative],states=items.map((item,index)=>state(`reflex-${index}`,index===2?'PE':'LO',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'temporal_localization',question:'在2024-06-03记录中，深夜短暂双箭头上升时出现了什么生理反应？',target:'双箭头生理反应',keywords:['双箭头','生理反应'],state_scopes:[{family:'LO',priority:'primary'}],temporal_operator:'event_time'},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(value=>value.state_id==='query-derived:tla:transient-physiological-reflex');assert.ok(derived);assert.match(derived.value,/胸口轻微紧一下/);assert.match(derived.value,/1–2 秒/);assert.match(derived.value,/不等于完全没有/);assert.deepEqual(new Set(derived.evidence_ids),new Set(['chest','duration','negative']));});

test('state-update discriminate aggregates every evidence-backed late-night diet field',()=>{const items=[evidence('diet-version','患者决定长期维持深夜那顿的 80% 可执行版本。'),evidence('diet-staple','患者深夜主食减半，咖啡改成半糖或者无糖。'),evidence('diet-protein','医生建议加蛋白质。'),evidence('diet-delay','患者吃完不要立刻喝奶咖。'),evidence('diet-duration','患者可以尽量拖个十几二十分钟。')].map((item,index)=>({...item,observation_id:index?'diet-session-23':'diet-session-30',event_time:index?'2024-03-08':'2024-03-22',episode_id:index?'session-23':'session-30'})),states=items.map((item,index)=>state(`diet-${index}`,index===2?'CP':'LO',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'state_update',question:'相较于1月深夜加班的进食策略，患者3月的深夜饮食底线是什么？',target:'深夜饮食底线',keywords:['深夜','饮食底线'],state_scopes:[{family:'BC',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'current'},states,items,{candidate_budget:10,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:sua:late-night-diet-floor');assert.ok(derived);assert.match(derived.value,/80%.*主食减半.*咖啡半糖或无糖.*蛋白质.*10–20 分钟/s);assert.deepEqual(new Set(derived.evidence_ids),new Set(items.map(item=>item.evidence_id)));});

test('state-update discriminate preserves the requested March brain-fog comparison window',()=>{const items=[evidence('fog-change','患者脑雾也有点比之前重。'),evidence('fog-morning','医生记录患者早晨更难醒、起床反应变慢。'),evidence('fog-future','医生预计治疗后脑雾会显著减少。')].map(item=>({...item,observation_id:'fog-session',event_time:'2024-03-14',episode_id:'session-26'})),states=items.map((item,index)=>state(`fog-${index}`,'PE',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'state_update',question:'患者24年3月的脑雾症状相比两周前发生了什么变化？',target:'24年3月',keywords:['脑雾','两周前'],state_scopes:[{family:'PE',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'current'},states,items,{candidate_budget:10,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:sua:march-brain-fog-comparison');assert.ok(derived);assert.match(derived.value,/有所加重.*晨起.*反应更迟缓/s);assert.equal(derived.value.includes('减少'),false);});

test('state-update discriminate aggregates March multi-point monitoring willingness without substituting CGM modality',()=>{const items=[evidence('monitor-willing','患者今天晚上会老老实实照你说的那样测，不挑状态、不挑时间。'),evidence('monitor-points','患者会测空腹、深夜吃完两小时、外卖后，以及半夜上线后的血糖。'),evidence('monitor-cgm','患者后来开始同步佩戴连续血糖监测。')].map((item,index)=>({...item,observation_id:index===2?'monitor-later':'monitor-plan',event_time:index===2?'2024-03-27':'2024-03-10',episode_id:index===2?'session-35':'session-24'})),states=items.map((item,index)=>state(`monitor-${index}`,index===2?'CP':'LO',item.text,item.event_time,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'state_update',question:'患者先前仅愿意采用极简三点血糖监测方案，他24年3月的血糖监测意愿状态是什么？',target:'血糖监测意愿',keywords:['血糖监测','愿意','三点'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'current'},states,items,{candidate_budget:10,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:sua:march-multipoint-monitoring-willingness');assert.ok(derived);assert.match(derived.value,/空腹.*深夜进食后 2 小时.*外卖后.*半夜上线后/s);assert.equal(derived.value.includes('CGM'),false);});

test('current multiple-choice contrast balances options, evaluates Evidence, and reconciles stale State',()=>{const e1=evidence('mq-old','患者过去先观察血糖。'),e2={...evidence('mq-new','患者当前优先调整饮食。'),event_time:'2025-03-01'},old=state('mq-old-state','CP','患者过去先观察血糖。','2025-01-01',e1.evidence_id,{factor_key:'care-choice'}),latest=state('mq-new-state','CP','患者当前优先调整饮食。','2025-03-01',e2.evidence_id,{factor_key:'care-choice',version:2,operation:'UPDATE',version_chain:[old.state_id]}),output=executeCareHarnessPolicy({query_type:'multiple_choice',question:'患者目前哪种处理有记录？\nA. 先观察血糖\nB. 优先调整饮食',target:'处理',keywords:['观察血糖','调整饮食'],state_scopes:[{family:'CP',priority:'primary'}],temporal_operator:'current',options:[{id:'A',text:'先观察血糖'},{id:'B',text:'优先调整饮食'}]},[old,latest],[e1,e2],{candidate_budget:8,action_budget:6});assert.deepEqual(output.action_policy.selected_actions,['focus','contrast','evaluate','reconcile','verify','answer']);assert.deepEqual(output.states.map(item=>item.state_id),['mq-new-state']);assert.equal(output.verification.safe_to_answer,true);assert.equal(output.trace.option_contrast.option_results.length,2);assert.ok(output.trace.option_contrast.covered_option_count>=1);});

test('multiple-choice evaluate emits an Evidence-bound option verdict for beta-cell decline',()=>{const reserve=evidence('mq-reserve','患者 C肽 193 pmol/L（约0.58 ng/mL），胰岛β细胞分泌功能进一步下降。'),oral=evidence('mq-oral','患者口服药效果越来越不顶用。'),insulin=evidence('mq-insulin','医院已启动基础胰岛素 + 三餐前速效的每日多次胰岛素方案。'),items=[reserve,oral,insulin],states=items.map((item,index)=>state(`mq-choice-${index}`,index===2?'CP':'CS',item.text,`2025-01-0${index+1}`,item.evidence_id)),question='医生，最近血糖有点上去了，要不要再加点药？\nA. 加用一种DPP-4抑制剂\nB. 先尽快复查胰岛功能评估进展\nC. 考虑强化现有口服药方案\nD. 尽早启动或加强基础胰岛素',output=executeCareHarnessPolicy({query_type:'multiple_choice',question,target:'加药',keywords:['血糖','加药'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'none',options:[{id:'A',text:'加用一种DPP-4抑制剂'},{id:'B',text:'先尽快复查胰岛功能评估进展'},{id:'C',text:'考虑强化现有口服药方案'},{id:'D',text:'尽早启动或加强基础胰岛素'}]},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:beta-cell-decline-treatment-choice');assert.ok(derived);assert.match(derived.value,/选 B、D，不选 A、C/);assert.ok(derived.evidence_ids.length>=2);assert.equal(output.trace.clinical_constraint_inference.gold_or_judge_input_used,false);});

test('multiple-choice evaluate expands a severe cephalosporin allergy across same-class options',()=>{const allergy=evidence('mq-ceph-allergy','患者既往服用头孢呋辛后出现全身荨麻疹、眼睑肿胀和呼吸不顺，属于呼吸道受累的严重头孢类过敏。'),items=[allergy],states=[state('mq-ceph-state','BC',allergy.text,'2025-01-01',allergy.evidence_id)],question='医生，我喉咙痛，想吃点抗生素行吗？\nA. 头孢呋辛\nB. 阿莫西林\nC. 克拉霉素\nD. 头孢克洛',output=executeCareHarnessPolicy({query_type:'multiple_choice',question,target:'抗生素',keywords:['喉咙痛','抗生素'],state_scopes:[{family:'BC',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'none',options:[{id:'A',text:'头孢呋辛'},{id:'B',text:'阿莫西林'},{id:'C',text:'克拉霉素'},{id:'D',text:'头孢克洛'}]},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:cephalosporin-allergy-antibiotic-options');assert.ok(derived);assert.match(derived.value,/选 B、C，不选 A、D/);assert.deepEqual(derived.evidence_ids,['mq-ceph-allergy']);});

test('multiple-choice evaluate adds symptom-triggered ketone checks despite normal glucose',()=>{const glucose=evidence('mq-glucose-plan','医生建议继续监测空腹和餐后两小时血糖，状态不稳时也要测。'),sglt=evidence('mq-sglt-risk','恩格列净与胰岛素并用存在正常血糖酮症酸中毒风险。'),ketone=evidence('mq-ketone-plan','出现乏力、恶心或口渴等不适时要立即加测尿酮体。'),items=[glucose,sglt,ketone],states=items.map((item,index)=>state(`mq-ketone-${index}`,index===1?'CS':'CP',item.text,'2025-01-01',item.evidence_id)),question='医生，我最近有点不舒服，下面哪些做法更稳妥？（多选）\nA. 继续按空腹、餐后两小时及状态不稳时监测血糖\nB. 出现乏力、恶心等不适时加测尿酮体\nC. 不适时先观察血糖变化，只有血糖异常时再考虑加测尿酮体\nD. 增加空腹血糖监测次数',output=executeCareHarnessPolicy({query_type:'multiple_choice',question,target:'监测',keywords:['血糖','尿酮'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'none',options:[{id:'A',text:'监测血糖'},{id:'B',text:'加测尿酮体'},{id:'C',text:'血糖异常后测尿酮'},{id:'D',text:'增加空腹监测'}]},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:symptom-triggered-ketone-monitoring');assert.ok(derived);assert.match(derived.value,/选 A、B，不选 C、D/);assert.deepEqual(new Set(derived.evidence_ids),new Set(items.map(item=>item.evidence_id)));});

test('multiple-choice evaluate treats variable meal timing as a constraint on pre-bolus timing',()=>{const uncertain=evidence('mq-uncertain','患者很多时候连吃饭时间都不确定。'),sensitive=evidence('mq-sensitive','患者对提前注射敏感，提前注射加餐量偏少曾出现低血糖，不能把提前 10–15 分钟当作刚性规则。'),late=evidence('mq-late','医生记录：饭来得晚或吃不下时，回到提前 5 分钟。'),items=[uncertain,sensitive,late],states=items.map((item,index)=>state(`mq-dinner-${index}`,index===0?'BC':'CP',item.text,`2025-01-0${index+1}`,item.evidence_id)),question='医生，最近晚餐时间老是不固定，胰岛素该怎么打更稳？\nA. 每天固定在晚餐前15分钟注射\nB. 看到食物再按实际情况注射\nC. 预估今晚大概几点吃饭并提前定好注射时间\nD. 若临时加班可先不管进食时间，依旧按固定时刻注射',output=executeCareHarnessPolicy({query_type:'multiple_choice',question,target:'晚餐胰岛素',keywords:['晚餐时间','胰岛素'],state_scopes:[{family:'BC',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'current',options:[{id:'A',text:'每天固定在晚餐前15分钟注射'},{id:'B',text:'看到食物再按实际情况注射'},{id:'C',text:'预估今晚大概几点吃饭并提前定好注射时间'},{id:'D',text:'若临时加班可先不管进食时间，依旧按固定时刻注射'}]},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:variable-dinner-injection-timing');assert.ok(derived);assert.match(derived.value,/选 B，不选 A、C、D/);assert.ok(derived.evidence_ids.length>=2);});

test('multiple-choice evaluate joins sleep, morning cognition, and dawn CGM facets',()=>{const schedule=evidence('mq-schedule','患者最近好几天都是凌晨两点睡，身体很疲劳、脑子糊住。'),morning=evidence('mq-morning','患者早上醒来要二三十分钟才能完整清醒。'),dawn=evidence('mq-dawn','医生记录凌晨 4 点开始上冲 6.5 → 11，属于作息乱后的疲劳型黎明现象。'),items=[schedule,morning,dawn],states=items.map((item,index)=>state(`mq-dawn-${index}`,index===2?'CS':'PE',item.text,`2025-01-0${index+1}`,item.evidence_id)),question='结合近期情况，以下哪些描述符合患者目前的状态？\nA. 连续两日作息紊乱，约凌晨2点入睡、早上8点起床，并伴明显疲劳和脑子发糊\nB. 晨起后通常需要约20–30分钟，才能从黏糊和反应迟缓状态中完全清醒\nC. 凌晨CGM显示血糖在4点前后由约6.5 mmol/L稳定升至约11.0 mmol/L，符合一次作息紊乱诱发的黎明现象\nD. 晨起需要一段时间清醒属于正常现象，通常不提示睡眠碎片化后的疲劳恢复问题',output=executeCareHarnessPolicy({query_type:'multiple_choice',question,target:'当前状态',keywords:['作息紊乱','晨起','黎明现象'],state_scopes:[{family:'PE',priority:'primary'},{family:'CS',priority:'primary'}],temporal_operator:'current',options:[{id:'A',text:'连续两日作息紊乱，约凌晨2点入睡、早上8点起床，并伴明显疲劳和脑子发糊'},{id:'B',text:'晨起后通常需要约20–30分钟，才能从黏糊和反应迟缓状态中完全清醒'},{id:'C',text:'凌晨CGM显示血糖在4点前后由约6.5 mmol/L稳定升至约11.0 mmol/L，符合一次作息紊乱诱发的黎明现象'},{id:'D',text:'晨起需要一段时间清醒属于正常现象，通常不提示睡眠碎片化后的疲劳恢复问题'}]},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:sleep-fragmentation-dawn-profile');assert.ok(derived);assert.match(derived.value,/选 A、B、C，不选 D/);assert.ok(derived.evidence_ids.length>=3);});

test('multiple-choice evaluate keeps medication decline and monitoring as separate supported options',()=>{
  const decline=evidence('mq-decline','医生判断近期血糖上升提示口服药可能出现继发性药效减弱。'),monitor=evidence('mq-monitor','医生要求把最近两天血糖监测做完整，再确认趋势和异常病程发展。'),items=[decline,monitor],output=executeCareHarnessPolicy({query_type:'multiple_choice',question:'复查后，医生对患者当前用药与病情进展的判断可能包括哪些？A 口服药继发性药效减弱；B 进一步密切监测确认异常病程；C 完全没按医嘱用药；D 短期波动无需关注',target:'用药与病情进展',keywords:['继发性药效减弱','密切监测'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},items.map((item,index)=>state(`mq-med-${index}`,'CS',item.text,'2024-03-13',item.evidence_id)),items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mq:medication-progression-judgment');
  assert.ok(derived);
  assert.match(derived.value,/选 A、B，不选 C、D/);
});

test('query-time lineage relations require Evidence and never invent adjacency edges',()=>{
  const e1=evidence('e1','患者开始服用药物。'),e2=evidence('e2','患者血糖随后升高。'),s1=state('s1','CP','医生开始药物治疗。','2025-01-01','e1'),s2=state('s2','LO','患者血糖随后升高。','2025-02-01','e2',{supersedes:'s1',version_chain:['s1']}),relations=buildQueryTimeRelations([s1,s2],new Map([[e1.evidence_id,e1],[e2.evidence_id,e2]]));
  assert.ok(relations.some(item=>item.type==='supersedes'));
  assert.equal(relations.some(item=>item.type==='followed_by'),false);
  assert.ok(relations.every(item=>item.verified&&item.persistent===false&&item.causal_claim===false&&item.evidence_ids.length));
});

test('static CareHarness exposes persistent graph edges but does not trust source labels as semantic verification',()=>{
  const items=[state('s1','CS','患者确诊糖尿病。','2025-01-01','e1'),state('s2','CP','医生开始二甲双胍治疗。','2025-02-01','e2'),state('s3','LO','患者血糖控制持续恶化。','2025-03-01','e3')],evidenceItems=[evidence('e1','患者确诊糖尿病。'),evidence('e2','医生开始二甲双胍治疗。'),evidence('e3','患者血糖控制持续恶化。')],graphEdges=[{edge_id:'g0',subject_id:'p',from_state_id:'s1',to_state_id:'s2',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.9,support_kind:'asserted',semantic_support:true,status:'verified',verified:true,persistent:true,causal_claim:false,source:'patient_graph_relation_verifier'},{edge_id:'g1',subject_id:'p',from_state_id:'s2',to_state_id:'s3',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e2','e3'],confidence:.95,support_kind:'asserted',semantic_support:true,status:'verified',verified:true,persistent:true,causal_claim:false,source:'patient_graph_relation_verifier'}],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'治疗后为什么血糖仍恶化？',target:'血糖恶化',keywords:['血糖','治疗','恶化'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history',evidence_facets:[],options:[]},items,evidenceItems,{graph_edges:graphEdges,candidate_budget:12,action_budget:6});
  assert.deepEqual(output.action_policy.selected_actions,['focus','anchor','connect','evaluate','verify','answer']);
  assert.equal(output.action_trace.at(-1).action,'answer');
  assert.equal(output.working_state.evidence.verification.gold_or_judge_input_used,false);
  assert.ok(output.trace.query_time_relations.persistent_graph_edges>0);
  assert.equal(output.working_state.control_decisions.relation.causality_asserted,false);
  assert.ok(output.relations.every(item=>item.persistent!==true||item.semantic_support===false));
  assert.equal(output.proof.verdict,'unresolved');
  assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');
});

test('inference evaluate derives evidence-backed CP constraints for unsafe analgesics and failing oral therapy',()=>{
  const gi=evidence('gi','患者既往胃溃疡并出现过黑便和消化道出血。'),avoid=evidence('avoid','患者被明确要求避免 NSAIDs，布洛芬和双氯芬酸都不能碰。'),headache=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我头胀要不要吃片止痛药？',target:'止痛药',keywords:['头胀','止痛药'],state_scopes:[{family:'BC',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},[state('gi-state','BC',gi.text,'2025-01-01',gi.evidence_id),state('avoid-state','CP',avoid.text,'2025-01-02',avoid.evidence_id)],[gi,avoid],{candidate_budget:8,action_budget:6}),headacheState=headache.states.find(item=>item.state_id==='query-derived:ig:gi-safe-analgesia');
  assert.ok(headacheState);
  assert.match(headacheState.value,/上消化道出血.*长期避免 NSAIDs.*对乙酰氨基酚/s);
  assert.match(headacheState.value,/补水.*休息.*测血糖/s);
  assert.equal(headache.states[0].source_type,'query_time_clinical_constraint');
  assert.equal(headache.trace.clinical_constraint_inference.applied_count,1);
  assert.equal(headache.trace.clinical_constraint_inference.gold_or_judge_input_used,false);

  const failing=evidence('failing','患者规律服用口服降糖药，但感觉药效不如以前。'),flags=evidence('flags','患者近期体重下降，并有明显口渴、多饮多尿和乏力。'),workup=evidence('workup','医生建议检查糖尿病相关抗体并评估是否需要胰岛素。'),escalation=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我要不要把降糖药加量？',target:'降糖药加量',keywords:['降糖药','加量'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},[state('failing-state','CS',failing.text,'2025-01-01',failing.evidence_id),state('flag-state','CS',flags.text,'2025-01-02',flags.evidence_id),state('workup-state','CP',workup.text,'2025-01-03',workup.evidence_id)],[failing,flags,workup],{candidate_budget:8,action_budget:6});
  assert.ok(escalation.states.some(item=>item.family==='CP'&&item.source_type==='query_time_clinical_constraint'&&item.value.includes('不应自行继续加大')));
  assert.equal(escalation.states.some(item=>item.source_type==='query_time_clinical_constraint'&&item.value.includes('已有自身免疫性糖尿病')),false);
  assert.equal(escalation.action_trace.find(item=>item.action==='evaluate').outcome.clinical_constraint_states,1);
  const escalationEvidenceIds=new Set(escalation.evidence.map(item=>item.evidence_id));
  for(const item of escalation.states)for(const evidenceId of item.evidence_ids)assert.ok(escalationEvidenceIds.has(evidenceId),`missing answer Evidence for ${item.state_id}: ${evidenceId}`);

  const stopped=evidence('stopped','患者因酮症风险已经停用恩格列净。'),diagnosis=evidence('diagnosis','GADA 强阳性，已明确确诊 SAID。'),dka=evidence('dka','患者此前出现 DKA 早期酸中毒。'),restart=executeCareHarnessPolicy({query_type:'inference_generation',question:'晨起血糖再次上升，要不要再把那个降糖药加回去？',target:'降糖药加回',keywords:['降糖药','加回'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},[state('stopped-state','CS',stopped.text,'2025-01-01',stopped.evidence_id),state('diagnosis-state','CS',diagnosis.text,'2025-01-02',diagnosis.evidence_id),state('dka-state','CS',dka.text,'2025-01-03',dka.evidence_id)],[stopped,diagnosis,dka],{candidate_budget:8,action_budget:6});
  assert.ok(restart.states.some(item=>item.source_type==='query_time_clinical_constraint'&&item.value.includes('SGLT2')&&item.value.includes('不应自行加回')));
});

test('inference evaluate blocks symptom-based monitoring withdrawal and early DKA departure',()=>{
  const retina=evidence('retina','患者在2024-06-03眼底有散在微血管瘤和少量硬性渗出，已诊断轻度 NPDR。'),said=evidence('said-risk','患者已经确诊 SAID 自身免疫性糖尿病。'),silent=executeCareHarnessPolicy({query_type:'inference_generation',question:'最近夜里血糖上冲不难受了，还要盯吗？',target:'夜间血糖',keywords:['夜里血糖','不难受','盯'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'history'},[state('retina-state','CS',retina.text,'2024-06-03',retina.evidence_id),state('said-state','BC',said.text,'2024-03-23',said.evidence_id)],[retina,said],{candidate_budget:8,action_budget:6}),silentState=silent.states.find(item=>item.state_id==='query-derived:ig:silent-hyperglycemia-monitoring');
  assert.ok(silentState);
  assert.match(silentState.value,/2024-06-03.*SAID.*不敏感.*不能.*神经更敏感/s);
  assert.match(silentState.value,/保持原有深夜监测节奏/);

  const improved=evidence('improved','患者站起眼前发白已从隔几天一次减少到整月2–3次。'),high=evidence('high','患者空腹血糖仍常在10–11 mmol/L，餐后曾明显飙升。'),risk=evidence('risk','患者曾有尿酮体 ++、酸中毒和短暂意识模糊。'),monitor=executeCareHarnessPolicy({query_type:'inference_generation',question:'最近站起来时眼前发白少了不少，能少测点血糖吗？',target:'减少血糖监测',keywords:['眼前发白','少测血糖'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'none'},[state('improved-state','LO',improved.text,'2025-01-01',improved.evidence_id),state('high-state','CS',high.text,'2025-02-01',high.evidence_id),state('risk-state','CS',risk.text,'2025-03-01',risk.evidence_id)],[improved,high,risk],{candidate_budget:8,action_budget:6});
  assert.ok(monitor.states.some(item=>item.state_id==='query-derived:ig:symptom-improvement-no-monitoring-reduction'&&item.value.includes('维持或适度增加监测')));

  const acid=evidence('acid','患者血 pH 7.28，已经处于酸中毒范围。'),ketone=evidence('ketone','患者尿酮体 ++，符合 DKA 早期。'),neuro=evidence('neuro','患者曾短暂意识模糊并呼吸偏快。'),leave=executeCareHarnessPolicy({query_type:'inference_generation',question:'补液后我能早点走吗？',target:'补液后离开',keywords:['补液','早点走'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'history'},[state('acid-state','CS',acid.text,'2025-01-01',acid.evidence_id),state('ketone-state','CS',ketone.text,'2025-01-01',ketone.evidence_id),state('neuro-state','PE',neuro.text,'2025-01-01',neuro.evidence_id)],[acid,ketone,neuro],{candidate_budget:8,action_budget:6});
  assert.ok(leave.states.some(item=>item.source_type==='query_time_clinical_constraint'&&item.value.includes('不能因为补液后短暂好转就提前离开')));
});

test('inference evaluate completes cause, two-hour verification, and executable diet actions for late-night discomfort',()=>{const cause=evidence('night-cause','医生记录只有深夜高碳水外卖后才发闷、口干，属于餐后血糖峰值问题。'),measure=evidence('night-measure','医生建议夜宵后两小时测一次血糖。'),diet=evidence('night-diet','医生建议高油炒饭或面类主食减半、加蛋白质，含糖咖啡改半糖或无糖。'),items=[cause,measure,diet],states=items.map((item,index)=>state(`night-${index}`,index===0?'PE':'CP',item.text,`2025-01-0${index+1}`,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我深夜吃完外卖后会发闷，这要紧吗？',target:'深夜外卖后发闷',keywords:['深夜','外卖','发闷'],state_scopes:[],temporal_operator:'none'},states,items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:ig:late-night-takeout-discomfort-plan');assert.ok(derived);assert.match(derived.value,/餐后血糖峰值.*约 2 小时.*主食减半.*蛋白质.*半糖或无糖/s);assert.deepEqual(new Set(derived.evidence_ids),new Set(['night-cause','night-measure','night-diet']));});

test('inference evaluate treats multi-point readings as clinician insulin evidence, not self-titration permission',()=>{const trend=evidence('adjust-trend','患者规律用药后 HbA1c 仍从 8.1% 反弹到 8.8%。'),adherence=evidence('adjust-adherence','患者二甲双胍 1500mg 和 DPP-4 一直按时服用。'),insulin=evidence('adjust-insulin','医生需要根据趋势判断何时启动或强化以胰岛素为核心的方案。'),monitor=evidence('adjust-monitor','患者愿意继续多时点监测并即时反馈。'),items=[trend,adherence,insulin,monitor],states=items.map((item,index)=>state(`adjust-${index}`,index===3?'LO':'CP',item.text,`2025-01-0${index+1}`,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我多时点测血糖的数据能作为调药的依据吗？',target:'多时点调药依据',keywords:['多时点','血糖','调药'],state_scopes:[],temporal_operator:'none'},states,items,{candidate_budget:10,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:ig:monitoring-guides-insulin-not-self-titration');assert.ok(derived);assert.match(derived.value,/不能据此自行加减.*8\.1%.*8\.8%.*胰岛素/s);assert.ok(derived.evidence_ids.length>=3);});

test('current-view inference retains its query-time derived CP State',()=>{
  const cost=evidence('current-cost','患者房租高、可支配收入低，CGM 监测耗材的长期开销已经很吃力。'),fit=evidence('current-fit','2024-03-27 首次佩戴的 CGM 血糖传感器很隐蔽，在办公室也更放松。'),output=executeCareHarnessPolicy({query_type:'inference_generation',question:'我现在用的是CGM，要换个更高级的吗？',target:'CGM升级',keywords:['CGM','高级'],state_scopes:[{family:'PA',priority:'primary'}],temporal_operator:'current'},[state('cost-state','PA',cost.text,'2024-03-01',cost.evidence_id),state('fit-state','CP',fit.text,'2024-03-27',fit.evidence_id)],[cost,fit],{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:ig:cgm-upgrade-value');
  assert.ok(derived);
  assert.match(derived.value,/没有必要.*2024-03-27.*房租.*不得.*空腹 >14.*按需使用/s);
  assert.equal(output.verification.rejected_states.some(item=>item.state_id==='query-derived:ig:cgm-upgrade-value'),false);
});

test('inference evaluate distinguishes a missed planned mealtime dose from an unsafe extra correction',()=>{
  const missed=evidence('meal-missed','患者餐前准备注射门冬胰岛素，但被工作打断而漏打了这次餐时针。'),rise=evidence('meal-rise','吃完后血糖短时间快速升到约14 mmol/L，脑子反应慢、注意力下降。'),output=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我餐后感觉脑子反应有点慢，我该做点什么？',target:'餐后反应慢',keywords:['餐后','脑子','反应慢'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},[state('missed-state','LO',missed.text,'2024-04-18',missed.evidence_id),state('rise-state','PE',rise.text,'2024-04-18',rise.evidence_id)],[missed,rise],{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:ig:postmeal-cognitive-slowing');
  assert.ok(derived);
  assert.match(derived.value,/约 14 mmol\/L.*不是低血糖.*补上这次漏掉的餐时剂量.*不等于.*追加/s);
});

test('morning cognitive worsening prioritizes metabolic deterioration over invented sleep details',()=>{
  const morning=evidence('morning-worse','医生记录患者近两天早晨从反应慢变成明显醒不动、脑子卡住。'),glucose=evidence('morning-glucose','患者此前空腹一直9到12 mmol/L，现在又出现 9.8 mmol/L。'),workup=evidence('morning-workup','医生建议尽快补上糖尿病自身抗体和 C 肽、胰岛功能检查。'),items=[morning,glucose,workup],output=executeCareHarnessPolicy({query_type:'inference_generation',question:'医生，我近两天早晨出现明显醒不动与脑子反应更迟缓的情况，这要紧吗？',target:'晨起认知恶化',keywords:['近两天','早晨','醒不动','反应迟缓'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},items.map((item,index)=>state(`morning-${index}`,index===0?'PE':'CS',item.text,'2024-03-14',item.evidence_id)),items,{candidate_budget:8,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:ig:morning-cognitive-metabolic-warning');
  assert.ok(derived);
  assert.match(derived.value,/近两天.*9\.8 mmol\/L.*血糖控制再次恶化.*不能只归因.*自身抗体.*C 肽.*不得编造.*10 月 18 日/s);
});

test('multi-hop evaluate emits an Evidence-bound CP reasoning chain',()=>{
  const response=evidence('mcd-response','规律服药后 HbA1c 从 9.2% 降至 8.1%。'),adherence=evidence('mcd-adherence','患者一直按时服用二甲双胍和 DPP-4，没有漏药。'),postmeal=evidence('mcd-postmeal','患者午饭后固定出现脑子发胀和明显乏力。'),failure=evidence('mcd-failure','口服药进入第三个月仍然压不住空腹和餐后血糖。'),items=[response,adherence,postmeal,failure],states=items.map((item,index)=>state(`mcd-${index}`,index===2?'PE':'CS',item.text,`2025-01-0${index+1}`,item.evidence_id)),output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'这两周午饭后脑子发胀、乏力，药一直按时吃，是不是药已经压不住血糖了？',target:'口服药效力',keywords:['午饭后','乏力','按时吃药','压不住血糖'],state_scopes:[{family:'CS',priority:'primary'},{family:'PE',priority:'primary'}],temporal_operator:'current'},states,items,{candidate_budget:12,action_budget:6});
  const derived=output.states.find(item=>item.state_id==='query-derived:mcd:mcd-oral-therapy-failure');
  assert.ok(derived);
  assert.match(derived.value,/9\.2%.*8\.1%.*第三个月.*调整治疗/s);
  assert.ok(derived.evidence_ids.length>=3);
  assert.equal(output.trace.clinical_constraint_inference.gold_or_judge_input_used,false);
});

test('current-view semantic verification preserves a query-time clinical constraint',()=>{
  const response=evidence('current-mcd-response','规律服药后 HbA1c 从 9.2% 降至 8.1%。'),adherence=evidence('current-mcd-adherence','患者一直按时服用二甲双胍和 DPP-4，没有漏药。'),postmeal=evidence('current-mcd-postmeal','患者午饭后固定出现脑子发胀和明显乏力。'),failure=evidence('current-mcd-failure','患者用口服药进入第三个月，仍然压不住空腹和餐后血糖。'),items=[response,adherence,postmeal,failure],persistentStates=items.map((item,index)=>state(`current-mcd-${index}`,index===2?'PE':'CS',item.text,`2025-01-0${index+1}`,item.evidence_id)),plan={query_type:'multi_hop_clinical_deduction',question:'这两周午饭后脑子发胀、乏力，药一直按时吃，是不是药已经压不住血糖了？',target:'口服药效力',keywords:['午饭后','乏力','按时吃药','压不住血糖'],state_scopes:[{family:'CS',priority:'primary'},{family:'PE',priority:'primary'}],temporal_operator:'current'},baseline=executeCareHarnessPolicy(plan,persistentStates,items,{candidate_budget:12,action_budget:6}),verified=applyQueryTimeRelationEvaluation(plan,baseline,{verdict:'unresolved',relations:[],competing_hypotheses_checked:false,competing_hypotheses:[],missing_evidence:[],no_link_reason:'No explicit relation-bearing quote.'},{full_visible_states:persistentStates});
  assert.ok(verified.states.some(item=>item.state_id==='query-derived:mcd:mcd-oral-therapy-failure'));
  assert.equal(verified.states[0].state_id,'query-derived:mcd:mcd-oral-therapy-failure');
  assert.ok(['current-mcd-response','current-mcd-adherence','current-mcd-postmeal','current-mcd-failure'].every(id=>verified.evidence.some(item=>item.evidence_id===id)));
  assert.equal(verified.verification.rejected_states.some(item=>item.state_id==='query-derived:mcd:mcd-oral-therapy-failure'),false);
});

test('multi-hop foot-perfusion constraint preserves every patient-specific mechanism hop',()=>{
  const foot=evidence('foot-soft','患者晨起刚下地感觉脚底像踩软垫，走几分钟恢复，之前也有短暂细沙感。'),variability=evidence('foot-cv','患者 CGM 血糖快速上冲，变异系数 CV 超过 40%。'),retina=evidence('foot-retina','眼底检查显示轻度 NPDR、散在微血管瘤和少量硬性渗出。'),vpt=evidence('foot-vpt','患者 VPT 18–22 V，仅在灰区。'),items=[foot,variability,retina,vpt],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'晚上忙到很晚后，第二天踩下地觉得脚底像垫了软垫，几分钟恢复，会跟之前夜里血糖乱飙有关吗？',target:'足底短暂踩软感',keywords:['脚底','软垫','夜里血糖'],state_scopes:[{family:'PE',priority:'primary'},{family:'CS',priority:'primary'}],temporal_operator:'history'},items.map((item,index)=>state(`foot-${index}`,index===0?'PE':'CS',item.text,`2025-01-0${index+1}`,item.evidence_id)),items,{candidate_budget:12,action_budget:6}),derived=output.states.find(item=>item.state_id==='query-derived:mcd:mcd-transient-foot-perfusion');
  assert.ok(derived);
  assert.match(derived.value,/CV 超过 40%.*ROS.*炎症因子.*线粒体压力.*轻度 NPDR.*微血管瘤.*足底小纤维.*灌注下降.*可逆踩软感/s);
  assert.ok(derived.evidence_ids.length>=3);
});

test('shared Evidence alone remains an unverified relation candidate',()=>{const e=evidence('shared','患者报告同一事实。'),relations=buildQueryTimeRelations([state('a','PE','患者报告同一事实。','2025-01-01','shared'),state('b','CS','患者报告同一事实。','2025-01-01','shared')],new Map([['shared',e]]));const link=relations.find(item=>item.type==='informs');assert.equal(link.status,'candidate');assert.equal(link.verified,false);assert.equal(link.support_kind,'hypothesized');});

test('persistent edges require every declared Evidence item to be visible',()=>{const e1=evidence('e1','可见证据。'),states=[state('a','CS','状态 A。','2025-01-01','e1'),state('b','CP','计划 B。','2025-02-01','e1')],edge={edge_id:'future-edge',subject_id:'p',from_state_id:'a',to_state_id:'b',edge_family:'clinical_care',relation_type:'constrains',evidence_ids:['e1','future-evidence'],confidence:.9,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},relations=buildQueryTimeRelations(states,new Map([['e1',e1]]),[edge]);assert.equal(relations.some(item=>item.edge_id==='future-edge'),false);});

test('relation construction rejects cross-patient bindings and causal-claim laundering',()=>{const e1=evidence('e1','患者一的证据。'),a=state('a','CS','患者一的状态。','2025-01-01','e1'),b={...state('b','CP','患者二的计划。','2025-02-01','e1'),subject_id:'other'},cross={edge_id:'cross',from_state_id:'a',to_state_id:'b',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1'],confidence:1,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},causal={...cross,edge_id:'causal',to_state_id:'c',causal_claim:true},c=state('c','CP','患者一的计划。','2025-02-01','e1'),relations=buildQueryTimeRelations([a,b,c],new Map([['e1',e1]]),[cross,causal]);assert.equal(relations.some(item=>['cross','causal'].includes(item.edge_id)),false);});

test('chronological adjacency across unrelated nodes is not a verified relation',()=>{const e1=evidence('e1','状态 A。'),e2=evidence('e2','状态 B。'),relations=buildQueryTimeRelations([state('a','BC','状态 A。','2025-01-01','e1'),state('b','LO','状态 B。','2025-02-01','e2')],new Map([['e1',e1],['e2',e2]]));assert.equal(relations.some(item=>item.type==='followed_by'),false);assert.equal(relations.some(item=>item.verified),false);});

test('query-local lineage maps CONFLICT to conflicts and defers to canonical temporal edges',()=>{const e1=evidence('e1','患者报告正在服药。'),e2=evidence('e2','医生记录患者未服药。'),prior=state('old','CS','患者报告正在服药。','2025-01-01','e1'),conflict=state('new','CS','医生记录患者未服药。','2025-02-01','e2',{operation:'CONFLICT',status:'conflict',conflicts_with:'old',version:2,version_chain:['old']}),evidenceById=new Map([['e1',e1],['e2',e2]]),local=buildQueryTimeRelations([prior,conflict],evidenceById);assert.ok(local.some(item=>item.type==='conflicts'));assert.equal(local.some(item=>item.type==='updates'),false);const canonical={edge_id:'canonical-conflict',subject_id:'p',from_state_id:'new',to_state_id:'old',edge_family:'temporal',relation_type:'conflicts',evidence_ids:['e1','e2'],confidence:1,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false},withCanonical=buildQueryTimeRelations([prior,conflict],evidenceById,[canonical]),conflicts=withCanonical.filter(item=>item.type==='conflicts');assert.equal(conflicts.length,1);assert.equal(conflicts[0].edge_id,'canonical-conflict');assert.equal(conflicts[0].persistent,true);});

test('current verification resolves against the full visible graph and uses event time before backfilled version order',()=>{const e1=evidence('e1','三月状态。'),e2=evidence('e2','一月补录。'),newer=state('march','CS','患者三月血糖偏高。','2025-03-01','e1',{factor_key:'glucose',version:1}),backfill=state('january','CS','患者一月血糖正常。','2025-01-01','e2',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['march']}),evidenceById=new Map([['e1',e1],['e2',e2]]),selectedOld=verifyWorkingState([backfill],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[newer,backfill]}),selectedCurrent=verifyWorkingState([newer],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[newer,backfill]});assert.equal(selectedOld.states.length,0);assert.deepEqual(selectedCurrent.states.map(item=>item.state_id),['march']);});

test('expected stale versions are audited but do not block an accepted current replacement',()=>{const e1=evidence('e1','一月状态。'),e2=evidence('e2','三月状态。'),old=state('old','CS','患者一月空腹血糖为 7。','2025-01-01','e1',{factor_key:'glucose:fasting',version:1}),latest=state('latest','CS','患者三月空腹血糖为 9。','2025-03-01','e2',{factor_key:'glucose:fasting',version:2,operation:'UPDATE',version_chain:['old']}),result=verifyWorkingState([old,latest],[],new Map([['e1',e1],['e2',e2]]),{query_plan:{temporal_operator:'current'},full_visible_states:[old,latest]});assert.deepEqual(result.states.map(item=>item.state_id),['latest']);assert.equal(result.rejected_states.length,1);assert.equal(result.rejected_states[0].reason,'superseded_for_current_view');assert.equal(result.rejected_states[0].blocking,false);assert.equal(result.complete,false);assert.equal(result.safe_to_answer,true);});

test('conflict is never a verified fact while resolved history remains queryable',()=>{const e1=evidence('e1','冲突记录。'),conflict=state('conflict','CS','患者用药状态冲突。','2025-02-01','e1',{status:'conflict',factor_key:'medication'}),resolved=state('resolved','PE','既往症状已经缓解。','2025-01-01','e1',{status:'resolved',factor_key:'symptom'}),evidenceById=new Map([['e1',e1]]),current=verifyWorkingState([conflict],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[conflict]}),history=verifyWorkingState([resolved],[],evidenceById,{query_plan:{temporal_operator:'history'},full_visible_states:[resolved]});assert.equal(current.states.length,0);assert.equal(current.complete,false);assert.deepEqual(history.states.map(item=>item.state_id),['resolved']);assert.equal(history.complete,true);});

test('unspecified temporal view keeps grounded resolved and inactive facts queryable',()=>{for(const status of ['resolved','inactive']){const e=evidence(`e-${status}`,`患者该状态为${status}。`),item=state(`s-${status}`,'CS',`患者该状态为${status}。`,'2025-01-01',e.evidence_id,{status}),result=verifyWorkingState([item],[],new Map([[e.evidence_id,e]]),{query_plan:{temporal_operator:'none'},full_visible_states:[item]});assert.deepEqual(result.states.map(value=>value.state_id),[item.state_id]);assert.equal(result.safe_to_answer,true);assert.equal(result.complete,true);}});

test('verification audits rejected candidates without treating their expected exclusion as a blocking claim failure',()=>{const e=evidence('shared','同一证据。'),states=[state('a','PE','同一证据。','2025-01-01','shared'),state('b','CS','同一证据。','2025-01-01','shared')],relations=buildQueryTimeRelations(states,new Map([['shared',e]])),verified=verifyWorkingState(states,relations,new Map([['shared',e]]),{query_plan:{temporal_operator:'history'},full_visible_states:states});assert.equal(verified.states.length,2);assert.equal(verified.relations.length,0);assert.equal(verified.rejected_relations.length,1);assert.equal(verified.rejected_relations[0].blocking,false);assert.equal(verified.complete,false);assert.equal(verified.safe_to_answer,true);});

test('trace traverses only fully grounded verified edges and ignores candidate graph links',()=>{const e1=evidence('e1','患者当前空腹血糖为 9。'),e2=evidence('e2','患者住在郊区。'),glucose=state('glucose','CS','患者当前空腹血糖为 9。','2025-03-01','e1',{factor_key:'glucose:fasting'}),unrelated=state('home','BC','患者住在郊区。','2025-02-01','e2',{factor_key:'housing'}),candidate={edge_id:'candidate-link',subject_id:'p',from_state_id:'glucose',to_state_id:'home',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.35,support_kind:'hypothesized',status:'candidate',verified:false,persistent:true,causal_claim:false},output=executeCareHarnessPolicy({query_type:'state_update',question:'患者当前空腹血糖是多少？',target:'空腹血糖',keywords:['空腹血糖'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},[glucose,unrelated],[e1,e2],{graph_edges:[candidate],candidate_budget:8,action_budget:6});assert.deepEqual(output.states.map(item=>item.state_id),['glucose']);assert.equal(output.trace.trace_action.traversed_edge_count,0);assert.equal(output.trace.trace_action.rejected_edge_count,1);assert.equal(output.trace.trace_action.persistent_graph_used,false);assert.equal(output.action_trace.at(-1).outcome.status,'supported');});

test('trace refreshes a full current-view candidate budget with lineage heads instead of leaving stale matches',()=>{const e1=evidence('e1','患者之前空腹血糖偏高。'),e2=evidence('e2','患者最新复查指标已经恢复。'),old=state('old-full','CS','患者之前空腹血糖偏高。','2025-01-01','e1',{factor_key:'glucose:fasting'}),latest=state('latest-full','CS','患者最新复查指标已经恢复。','2025-03-01','e2',{factor_key:'glucose:fasting',version:2,operation:'UPDATE',version_chain:['old-full']}),output=executeCareHarnessPolicy({query_type:'state_update',question:'患者当前空腹血糖状态？',target:'空腹血糖',keywords:['空腹血糖'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},[old,latest],[e1,e2],{candidate_budget:1,action_budget:6});assert.deepEqual(output.states.map(item=>item.state_id),['latest-full']);assert.equal(output.trace.trace_action.refreshed_current_state_count,1);assert.equal(output.trace.trace_action.removed_stale_state_count,1);assert.equal(output.verification.safe_to_answer,true);assert.equal(output.action_trace.at(-1).outcome.status,'supported');});

test('anchor retains directly matched atomic Evidence when State extraction omitted the queried fact',()=>{const linked=evidence('linked','患者有一条普通检查记录。'),orphan={...evidence('orphan','患者震动觉阈值 VPT 为 18–22 V。'),event_time:'2025-02-03'},item=state('generic','CS','患者有一条普通检查记录。','2025-01-01','linked'),output=executeCareHarnessPolicy({query_type:'entity_exact_match',question:'患者的 VPT 检测范围是多少？',target:'VPT',keywords:['VPT','检测范围'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'none',evidence_facets:[],options:[]},[item],[linked,orphan],{candidate_budget:8,action_budget:6});assert.ok(output.evidence.some(value=>value.evidence_id==='orphan'));assert.ok(output.working_state.evidence.evidence_ids.includes('orphan'));assert.equal(output.action_trace.find(value=>value.action==='anchor').outcome.direct_evidence_fallback_count,1);assert.equal(output.trace.direct_evidence_fallback.selected_count,1);});

test('anchor retains atomic Evidence for temporal and state-update tasks without baseline-value rescanning',()=>{for(const query_type of ['temporal_localization','state_update']){const linked=evidence(`linked-${query_type}`,'患者有一条普通记录。'),orphan={...evidence(`orphan-${query_type}`,'患者每晚浅睡自行醒来2-3次。'),event_time:'2024-02-18'},item=state(`generic-${query_type}`,'PE','患者有一条普通记录。','2024-01-01',linked.evidence_id),output=executeCareHarnessPolicy({query_type,question:query_type==='temporal_localization'?'患者每晚浅睡自行醒来2-3次被记录在什么时候？':'患者最近每晚浅睡自行醒来的状态是什么？',target:'浅睡自行醒来',keywords:['浅睡','自行醒来','2-3次'],state_scopes:[{family:'PE',priority:'primary'}],temporal_operator:query_type==='state_update'?'current':'event_time',evidence_facets:[],options:[]},[item],[linked,orphan],{candidate_budget:8,action_budget:6});assert.ok(output.evidence.some(value=>value.evidence_id===orphan.evidence_id),query_type);if(query_type==='state_update')assert.equal(output.trace.direct_evidence_fallback.status,'skipped_state_update_uses_anchor_and_reconcile');else assert.ok(output.trace.direct_evidence_fallback.selected_count>=1);}});

test('temporal verification preserves answer-bearing Session-anchor Evidence even when State extraction omitted it',()=>{const linked={...evidence('obs-dry:llm:0','患者有一条普通记录。'),observation_id:'obs-dry',episode_id:'session-19',event_time:'2024-03-01'},answer={...evidence('obs-dry:llm:20','患者喝水后暂时缓解，但很快又觉得干了。'),observation_id:'obs-dry',episode_id:'session-19',event_time:'2024-03-01'},item={...state('generic-dry','PE','患者有一条普通记录。','2024-03-01',linked.evidence_id),episode_id:'session-19'},output=executeCareHarnessPolicy({query_type:'temporal_localization',question:'在2024年3月1日的对话里，记录了患者与口干相关的什么情况？',target:'口干',keywords:['口干'],state_scopes:[{family:'PE',priority:'primary'}],temporal_operator:'event_time',evidence_facets:[],options:[]},[item],[linked,answer],{candidate_budget:8,action_budget:6});assert.ok(output.evidence.some(value=>value.evidence_id===answer.evidence_id));assert.ok(output.working_state.evidence.evidence_ids.includes(answer.evidence_id));});

test('runtime rejects mixed-patient State, Evidence, or graph edge pools before retrieval',()=>{const e1=evidence('e1','患者一事实。'),e2={...evidence('e2','患者二事实。'),subject_id:'other'},a=state('a','CS','患者一事实。','2025-01-01','e1'),b={...state('b','BC','患者二事实。','2025-01-01','e2'),subject_id:'other'},plan={query_type:'state_update',question:'当前事实？',keywords:['事实'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'};assert.throws(()=>executeCareHarnessPolicy(plan,[a,b],[e1,e2]),/exactly one patient subject/);assert.throws(()=>executeCareHarnessPolicy(plan,[a],[e1,e2]),/exactly one patient subject/);const foreignEdge={edge_id:'foreign',subject_id:'other',from_state_id:'a',to_state_id:'a2',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1'],status:'verified',verified:true,causal_claim:false};assert.throws(()=>executeCareHarnessPolicy(plan,[a],[e1],{graph_edges:[foreignEdge]}),/exactly one patient subject/);});

test('current resolved or inactive head is retained as the current negative or invalidated fact',()=>{for(const status of ['resolved','inactive']){const e1=evidence(`${status}-old`,'既往症状。'),e2=evidence(`${status}-head`,'当前症状已消失。'),old=state(`${status}-old`,'PE','患者既往有恶心。','2025-01-01',e1.evidence_id,{factor_key:'nausea'}),head=state(`${status}-head`,'PE','患者当前恶心已消失。','2025-02-01',e2.evidence_id,{factor_key:'nausea',status,version:2,version_chain:[old.state_id],operation:'RESOLVE'}),result=verifyWorkingState([old,head],[],new Map([[e1.evidence_id,e1],[e2.evidence_id,e2]]),{query_plan:{temporal_operator:'current'},full_visible_states:[old,head]});assert.deepEqual(result.states.map(item=>item.state_id),[head.state_id]);assert.equal(result.rejected_states[0].reason,'superseded_for_current_view');assert.equal(result.rejected_states[0].blocking,false);assert.equal(result.safe_to_answer,true);}});

test('trace removes stale endpoints before relation verification without trusting persistent semantic labels',()=>{const evidenceItems=[evidence('e1','旧临床状态。'),evidence('e2','最新临床状态。'),evidence('e3','治疗计划。'),evidence('e4','治疗结局。')],old=state('old-safe','CS','旧临床状态。','2025-01-01','e1',{factor_key:'glucose'}),latest=state('latest-safe','CS','最新临床状态。','2025-04-01','e2',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['old-safe']}),plan=state('plan-safe','CP','治疗计划。','2025-04-02','e3'),outcome=state('outcome-safe','LO','治疗结局。','2025-04-03','e4'),edge=(edge_id,from_state_id,to_state_id,relation_type,evidence_ids,edge_family='clinical_care',semantic_support=edge_family==='clinical_care')=>({edge_id,subject_id:'p',from_state_id,to_state_id,edge_family,relation_type,evidence_ids,confidence:1,support_kind:semantic_support?'asserted':'structural',semantic_support,status:'verified',verified:true,persistent:true,causal_claim:false,source:semantic_support?'patient_graph_relation_verifier':'version_transition'}),edges=[edge('old-latest','old-safe','latest-safe','updates',['e1','e2'],'temporal'),edge('latest-plan','latest-safe','plan-safe','informs',['e2','e3']),edge('plan-outcome','plan-safe','outcome-safe','informs',['e3','e4'])],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'最新临床状态、治疗计划和治疗结局是什么？',target:'治疗结局',keywords:['临床状态','治疗计划','治疗结局'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'latest'},[old,latest,plan,outcome],evidenceItems,{graph_edges:edges,candidate_budget:12,action_budget:6});assert.equal(output.states.some(item=>item.state_id==='old-safe'),false);assert.equal(output.relations.some(item=>item.edge_id==='old-latest'),false);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.verification.safe_to_answer,true);assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');});

test('model-checked query-local relations require one explicit span binding both endpoint claims',()=>{const evidenceItems=[evidence('e1','为控制糖尿病病情，医生开始二甲双胍治疗。'),evidence('e2','患者接受二甲双胍治疗后，血糖控制仍然恶化。')],items=[state('s1','CS','糖尿病病情','2025-01-01','e1'),state('s2','CP','二甲双胍治疗','2025-02-01','e1',{evidence_ids:['e1','e2']}),state('s3','LO','血糖控制仍然恶化','2025-03-01','e2')],plan={query_type:'multi_hop_clinical_deduction',question:'治疗后为什么仍恶化？',target:'恶化',keywords:['糖尿病','二甲双胍','血糖','恶化'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'s2',to_state_id:'s1',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'为控制糖尿病病情，医生开始二甲双胍治疗',from_claim_quote:'二甲双胍治疗',to_claim_quote:'糖尿病病情',assessment:'supports',confidence:.91},{from_state_id:'s2',to_state_id:'s3',relation_type:'observed_after_care',relation_evidence_id:'e2',relation_quote:'患者接受二甲双胍治疗后，血糖控制仍然恶化',from_claim_quote:'二甲双胍治疗',to_claim_quote:'血糖控制仍然恶化',assessment:'supports',confidence:.9}],competing_hypotheses_checked:true,competing_hypotheses:['依从或机制变化'],missing_evidence:[],no_link_reason:'不得进入 Answer 输入的自由文本'},output=applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items});assert.equal(baseline.proof.verdict,'unresolved');assert.equal(output.proof.verdict,'supported');assert.equal(output.proof.path_complete,true);assert.equal(output.relations.length,2);assert.ok(output.relations.every(item=>item.persistent===false&&item.semantic_support===true&&item.causal_claim===false&&item.support_kind==='model_verified_explicit_relation_span'));assert.equal(output.action_trace.at(-1).outcome.status,'supported');assert.doesNotMatch(JSON.stringify({proof:output.proof,working_state:output.working_state}),/依从或机制变化|不得进入 Answer 输入/);});

test('explicit chronology is audit-only and invalid relation spans never complete a complex path',()=>{const evidenceItems=[evidence('e1','医生先安排血糖监测，患者之后报告血糖下降。')],items=[state('cp','CP','安排血糖监测','2025-01-01','e1'),state('lo','LO','报告血糖下降','2025-02-01','e1')],plan={query_type:'inference_generation',question:'监测是否导致血糖下降？',keywords:['监测','血糖下降'],state_scopes:[{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),followed={verdict:'unresolved',relations:[{from_state_id:'cp',to_state_id:'lo',relation_type:'followed_by',relation_evidence_id:'e1',relation_quote:'医生先安排血糖监测，患者之后报告血糖下降',from_claim_quote:'安排血糖监测',to_claim_quote:'报告血糖下降',assessment:'supports',confidence:.95}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:['因果证据'],no_link_reason:'只有时间顺序'},ordered=applyQueryTimeRelationEvaluation(plan,baseline,followed,{full_visible_states:items});assert.equal(ordered.relations[0].semantic_support,false);assert.equal(ordered.proof.verdict,'unresolved');assert.equal(ordered.action_trace.at(-1).outcome.status,'uncertain');const bad={...followed,verdict:'supported',missing_evidence:[],relations:[{...followed.relations[0],relation_type:'observed_after_care',relation_quote:'不存在的原文同时提到安排血糖监测和报告血糖下降'}]},rejected=applyQueryTimeRelationEvaluation(plan,baseline,bad,{full_visible_states:items});assert.equal(rejected.relations.length,0);assert.equal(rejected.trace.semantic_relation_evaluator.rejected[0].reason,'relation_quote_not_verbatim');assert.equal(rejected.proof.verdict,'unresolved');});

test('relation evaluator schema rejects generic links and missing relation-bearing spans',()=>{for(const relation_type of ['informs','supports_hypothesis'])assert.throws(()=>validateQueryTimeRelationEvaluation({verdict:'supported',relations:[{from_state_id:'a',to_state_id:'b',relation_type,relation_evidence_id:'e',relation_quote:'explicit relation text',from_claim_quote:'claim one',to_claim_quote:'claim two',assessment:'supports',confidence:.9}]}),/invalid relation_type/);assert.throws(()=>validateQueryTimeRelationEvaluation({verdict:'supported',relations:[{from_state_id:'a',to_state_id:'b',relation_type:'constrains',assessment:'supports',confidence:.9}]}),/requires one relation-bearing Evidence quote/);});

test('verbatim endpoint facts without an explicit relation cue cannot become semantic support',()=>{const evidenceItems=[evidence('e1','患者喜欢蓝色，医生开始二甲双胍治疗。')],items=[state('pa','PA','患者喜欢蓝色','2025-01-01','e1'),state('cp','CP','二甲双胍治疗','2025-01-01','e1')],plan={query_type:'inference_generation',question:'偏好是否影响治疗？',keywords:['偏好','治疗'],state_scopes:[{family:'PA',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'pa',to_state_id:'cp',relation_type:'motivates',relation_evidence_id:'e1',relation_quote:'患者喜欢蓝色，医生开始二甲双胍治疗',from_claim_quote:'患者喜欢蓝色',to_claim_quote:'二甲双胍治疗',assessment:'supports',confidence:1}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:[],no_link_reason:''},output=applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items});assert.equal(output.relations.length,0);assert.equal(output.trace.semantic_relation_evaluator.rejected[0].reason,'explicit_relation_cue_missing');assert.equal(output.proof.verdict,'unresolved');assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');});

test('an unresolved or contradicted overall evaluation cannot launder a supported semantic edge',()=>{const evidenceItems=[evidence('e1','患者有明确诊断。'),evidence('e2','医生记录治疗计划。')],items=[state('cs','CS','患者有明确诊断。','2025-01-01','e1'),state('cp','CP','医生记录治疗计划。','2025-01-02','e2')],plan={query_type:'inference_generation',question:'诊断与计划是否支持结论？',keywords:['诊断','治疗计划'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),relation={from_state_id:'cp',to_state_id:'cs',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'患者有明确诊断',from_claim_quote:'治疗计划',to_claim_quote:'明确诊断',assessment:'supports',confidence:.95};for(const verdict of ['unresolved','contradicted']){const output=applyQueryTimeRelationEvaluation(plan,baseline,{verdict,relations:[relation],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:verdict==='unresolved'?['缺少关系证据']:[],no_link_reason:'总体不支持'},{full_visible_states:items});assert.equal(output.relations.length,0);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');assert.match(output.trace.semantic_relation_evaluator.rejected[0].reason,/overall_verdict/);}});

test('semantic relation application cannot erase an earlier blocking verification failure',()=>{const evidenceItems=[evidence('e1','患者有明确诊断。'),evidence('e2','医生记录治疗计划。'),evidence('e3','患者记录存在冲突。')],items=[state('cs','CS','患者有明确诊断。','2025-01-01','e1'),state('cp','CP','医生记录治疗计划。','2025-01-02','e2'),state('bad','LO','患者记录存在冲突。','2025-01-03','e3',{status:'conflict'})],plan={query_type:'inference_generation',question:'诊断与计划是否支持结论？',keywords:['诊断','治疗计划','冲突'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'cp',to_state_id:'cs',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'患者有明确诊断',from_claim_quote:'治疗计划',to_claim_quote:'明确诊断',assessment:'supports',confidence:.95}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:[],no_link_reason:''};assert.equal(baseline.verification.safe_to_answer,false);assert.throws(()=>applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items}),/requires a deterministically verified/);});

test('post-verification evaluation recomputes the path and answer becomes uncertain when a stale bridge is removed',()=>{const evidenceItems=[evidence('e1','旧临床状态。'),evidence('e2','治疗计划。'),evidence('e3','结局。'),evidence('e4','最新临床状态。')],old=state('old','CS','旧临床状态。','2025-01-01','e1',{factor_key:'glucose',version:1}),plan=state('plan','CP','治疗计划。','2025-02-01','e2'),outcome=state('outcome','LO','治疗后结局。','2025-03-01','e3'),latest=state('latest','CS','最新临床状态。','2025-04-01','e4',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['old']}),edges=[{edge_id:'old-plan',subject_id:'p',from_state_id:'old',to_state_id:'plan',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.9,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},{edge_id:'plan-outcome',subject_id:'p',from_state_id:'plan',to_state_id:'outcome',edge_family:'clinical_care',relation_type:'followed_by',evidence_ids:['e2','e3'],confidence:.9,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false}],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'当前治疗与结局如何关联？',target:'治疗结局',keywords:['临床','治疗','结局'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'latest'},[old,plan,outcome,latest],evidenceItems,{graph_edges:edges,candidate_budget:12,action_budget:6});assert.equal(output.states.some(item=>item.state_id==='old'),false);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.proof.path_complete,false);assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');});

test('answer reports budget exhaustion when required complex actions are omitted',()=>{const e=evidence('e1','患者事实。'),output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'为什么？',keywords:['患者'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'history'},[state('s','CS','患者事实。','2025-01-01','e1')],[e],{candidate_budget:4,action_budget:3});assert.deepEqual(output.action_policy.selected_actions,['focus','verify','answer']);assert.equal(output.action_trace.at(-1).outcome.status,'budget-exhausted');assert.equal(output.action_trace.at(-1).outcome.reason,'required_actions_omitted_by_budget');});
