import test from 'node:test';
import assert from 'node:assert/strict';
import { applyQueryTimeRelationEvaluation,buildQueryTimeRelations,executeCareHarnessPolicy,selectCareHarnessActions,validateQueryTimeRelationEvaluation,verifyWorkingState } from '../src/careharness-actions.js';

const state=(id,family,value,time,evidenceId,extra={})=>({state_id:id,subject_id:'p',family,value,status:'active',event_time:time,episode_id:`session-${id}`,turn_id:'1',evidence_ids:[evidenceId],version:1,version_chain:[],supersedes:null,...extra});
const evidence=(id,text)=>({evidence_id:id,observation_id:`o-${id}`,subject_id:'p',text,source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2025-01-01',polarity:'affirmed',certainty:1});

test('actions are type-blind and use one universal route',()=>{
  const expected=['focus','anchor','connect','evaluate','verify','answer'];
  assert.deepEqual(selectCareHarnessActions({}),expected);
  assert.deepEqual(selectCareHarnessActions({query_type:'arbitrary-a',temporal_operator:'earliest'}),expected);
  assert.deepEqual(selectCareHarnessActions({query_type:'arbitrary-b',options:[{id:'x',text:'choice'}]}),expected);
});

test('query-time lineage relations require Evidence and never invent adjacency edges',()=>{
  const e1=evidence('e1','患者开始服用药物。'),e2=evidence('e2','患者血糖随后升高。'),s1=state('s1','CP','医生开始药物治疗。','2025-01-01','e1'),s2=state('s2','LO','患者血糖随后升高。','2025-02-01','e2',{supersedes:'s1',version_chain:['s1']}),relations=buildQueryTimeRelations([s1,s2],new Map([[e1.evidence_id,e1],[e2.evidence_id,e2]]));
  assert.ok(relations.some(item=>item.type==='supersedes'));
  assert.equal(relations.some(item=>item.type==='followed_by'),false);
  assert.ok(relations.every(item=>item.verified&&item.persistent===false&&item.causal_claim===false&&item.evidence_ids.length));
});

test('static CareHarness exposes persistent graph edges but does not trust source labels as semantic verification',()=>{
  const items=[state('s1','CS','患者确诊糖尿病。','2025-01-01','e1'),state('s2','CP','医生开始二甲双胍治疗。','2025-02-01','e2'),state('s3','LO','患者血糖控制持续恶化。','2025-03-01','e3')],evidenceItems=[evidence('e1','患者确诊糖尿病。'),evidence('e2','医生开始二甲双胍治疗。'),evidence('e3','患者血糖控制持续恶化。')],graphEdges=[{edge_id:'g0',subject_id:'p',from_state_id:'s1',to_state_id:'s2',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.9,support_kind:'asserted',semantic_support:true,status:'verified',verified:true,persistent:true,causal_claim:false,source:'patient_graph_relation_verifier'},{edge_id:'g1',subject_id:'p',from_state_id:'s2',to_state_id:'s3',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e2','e3'],confidence:.95,support_kind:'asserted',semantic_support:true,status:'verified',verified:true,persistent:true,causal_claim:false,source:'patient_graph_relation_verifier'}],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'治疗后为什么血糖仍恶化？',target:'血糖恶化',keywords:['血糖','治疗','恶化'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history',evidence_facets:[],options:[]},items,evidenceItems,{graph_edges:graphEdges,candidate_budget:12,action_budget:6});
  assert.deepEqual(output.action_policy.selected_actions,['focus','anchor','connect','evaluate','verify','answer']);
  assert.equal(output.action_trace.at(-1).action,'answer');
  assert.equal(output.working_state.evidence.verification.gold_or_judge_input_used,false);
  assert.ok(output.trace.query_time_relations.persistent_graph_edges>0);
  assert.equal(output.working_state.control_decisions.relation.causality_asserted,false);
  assert.ok(output.relations.every(item=>item.persistent!==true||item.semantic_support===false));
  assert.equal(output.proof.verdict,'unresolved');
  assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');
});

test('shared Evidence alone remains an unverified relation candidate',()=>{const e=evidence('shared','患者报告同一事实。'),relations=buildQueryTimeRelations([state('a','PE','患者报告同一事实。','2025-01-01','shared'),state('b','CS','患者报告同一事实。','2025-01-01','shared')],new Map([['shared',e]]));const link=relations.find(item=>item.type==='informs');assert.equal(link.status,'candidate');assert.equal(link.verified,false);assert.equal(link.support_kind,'hypothesized');});

test('persistent edges require every declared Evidence item to be visible',()=>{const e1=evidence('e1','可见证据。'),states=[state('a','CS','状态 A。','2025-01-01','e1'),state('b','CP','计划 B。','2025-02-01','e1')],edge={edge_id:'future-edge',subject_id:'p',from_state_id:'a',to_state_id:'b',edge_family:'clinical_care',relation_type:'constrains',evidence_ids:['e1','future-evidence'],confidence:.9,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},relations=buildQueryTimeRelations(states,new Map([['e1',e1]]),[edge]);assert.equal(relations.some(item=>item.edge_id==='future-edge'),false);});

test('relation construction rejects cross-patient bindings and causal-claim laundering',()=>{const e1=evidence('e1','患者一的证据。'),a=state('a','CS','患者一的状态。','2025-01-01','e1'),b={...state('b','CP','患者二的计划。','2025-02-01','e1'),subject_id:'other'},cross={edge_id:'cross',from_state_id:'a',to_state_id:'b',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1'],confidence:1,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},causal={...cross,edge_id:'causal',to_state_id:'c',causal_claim:true},c=state('c','CP','患者一的计划。','2025-02-01','e1'),relations=buildQueryTimeRelations([a,b,c],new Map([['e1',e1]]),[cross,causal]);assert.equal(relations.some(item=>['cross','causal'].includes(item.edge_id)),false);});

test('chronological adjacency across unrelated nodes is not a verified relation',()=>{const e1=evidence('e1','状态 A。'),e2=evidence('e2','状态 B。'),relations=buildQueryTimeRelations([state('a','BC','状态 A。','2025-01-01','e1'),state('b','LO','状态 B。','2025-02-01','e2')],new Map([['e1',e1],['e2',e2]]));assert.equal(relations.some(item=>item.type==='followed_by'),false);assert.equal(relations.some(item=>item.verified),false);});

test('query-local lineage maps CONFLICT to conflicts and defers to canonical temporal edges',()=>{const e1=evidence('e1','患者报告正在服药。'),e2=evidence('e2','医生记录患者未服药。'),prior=state('old','CS','患者报告正在服药。','2025-01-01','e1'),conflict=state('new','CS','医生记录患者未服药。','2025-02-01','e2',{operation:'CONFLICT',status:'conflict',conflicts_with:'old',version:2,version_chain:['old']}),evidenceById=new Map([['e1',e1],['e2',e2]]),local=buildQueryTimeRelations([prior,conflict],evidenceById);assert.ok(local.some(item=>item.type==='conflicts'));assert.equal(local.some(item=>item.type==='updates'),false);const canonical={edge_id:'canonical-conflict',subject_id:'p',from_state_id:'new',to_state_id:'old',edge_family:'temporal',relation_type:'conflicts',evidence_ids:['e1','e2'],confidence:1,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false},withCanonical=buildQueryTimeRelations([prior,conflict],evidenceById,[canonical]),conflicts=withCanonical.filter(item=>item.type==='conflicts');assert.equal(conflicts.length,1);assert.equal(conflicts[0].edge_id,'canonical-conflict');assert.equal(conflicts[0].persistent,true);});

test('current verification resolves against the full visible graph and uses event time before backfilled version order',()=>{const e1=evidence('e1','三月状态。'),e2=evidence('e2','一月补录。'),newer=state('march','CS','患者三月血糖偏高。','2025-03-01','e1',{factor_key:'glucose',version:1}),backfill=state('january','CS','患者一月血糖正常。','2025-01-01','e2',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['march']}),evidenceById=new Map([['e1',e1],['e2',e2]]),selectedOld=verifyWorkingState([backfill],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[newer,backfill]}),selectedCurrent=verifyWorkingState([newer],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[newer,backfill]});assert.equal(selectedOld.states.length,0);assert.deepEqual(selectedCurrent.states.map(item=>item.state_id),['march']);});

test('expected stale versions are audited but do not block an accepted current replacement',()=>{const e1=evidence('e1','一月状态。'),e2=evidence('e2','三月状态。'),old=state('old','CS','患者一月空腹血糖为 7。','2025-01-01','e1',{factor_key:'glucose:fasting',version:1}),latest=state('latest','CS','患者三月空腹血糖为 9。','2025-03-01','e2',{factor_key:'glucose:fasting',version:2,operation:'UPDATE',version_chain:['old']}),result=verifyWorkingState([old,latest],[],new Map([['e1',e1],['e2',e2]]),{query_plan:{temporal_operator:'current'},full_visible_states:[old,latest]});assert.deepEqual(result.states.map(item=>item.state_id),['latest']);assert.equal(result.rejected_states.length,1);assert.equal(result.rejected_states[0].reason,'superseded_for_current_view');assert.equal(result.rejected_states[0].blocking,false);assert.equal(result.complete,false);assert.equal(result.safe_to_answer,true);});

test('conflict is never a verified fact while resolved history remains queryable',()=>{const e1=evidence('e1','冲突记录。'),conflict=state('conflict','CS','患者用药状态冲突。','2025-02-01','e1',{status:'conflict',factor_key:'medication'}),resolved=state('resolved','PE','既往症状已经缓解。','2025-01-01','e1',{status:'resolved',factor_key:'symptom'}),evidenceById=new Map([['e1',e1]]),current=verifyWorkingState([conflict],[],evidenceById,{query_plan:{temporal_operator:'latest'},full_visible_states:[conflict]}),history=verifyWorkingState([resolved],[],evidenceById,{query_plan:{temporal_operator:'history'},full_visible_states:[resolved]});assert.equal(current.states.length,0);assert.equal(current.complete,false);assert.deepEqual(history.states.map(item=>item.state_id),['resolved']);assert.equal(history.complete,true);});

test('verification audits rejected candidates without treating their expected exclusion as a blocking claim failure',()=>{const e=evidence('shared','同一证据。'),states=[state('a','PE','同一证据。','2025-01-01','shared'),state('b','CS','同一证据。','2025-01-01','shared')],relations=buildQueryTimeRelations(states,new Map([['shared',e]])),verified=verifyWorkingState(states,relations,new Map([['shared',e]]),{query_plan:{temporal_operator:'history'},full_visible_states:states});assert.equal(verified.states.length,2);assert.equal(verified.relations.length,0);assert.equal(verified.rejected_relations.length,1);assert.equal(verified.rejected_relations[0].blocking,false);assert.equal(verified.complete,false);assert.equal(verified.safe_to_answer,true);});

test('trace traverses only fully grounded verified edges and ignores candidate graph links',()=>{const e1=evidence('e1','患者当前空腹血糖为 9。'),e2=evidence('e2','患者住在郊区。'),glucose=state('glucose','CS','患者当前空腹血糖为 9。','2025-03-01','e1',{factor_key:'glucose:fasting'}),unrelated=state('home','BC','患者住在郊区。','2025-02-01','e2',{factor_key:'housing'}),candidate={edge_id:'candidate-link',subject_id:'p',from_state_id:'glucose',to_state_id:'home',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.35,support_kind:'hypothesized',status:'candidate',verified:false,persistent:true,causal_claim:false},output=executeCareHarnessPolicy({query_type:'state_update',question:'患者当前空腹血糖是多少？',target:'空腹血糖',keywords:['空腹血糖'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'},[glucose,unrelated],[e1,e2],{graph_edges:[candidate],candidate_budget:8,action_budget:6});assert.deepEqual(output.states.map(item=>item.state_id),['glucose']);assert.equal(output.trace.trace_action.traversed_edge_count,0);assert.equal(output.trace.trace_action.rejected_edge_count,1);assert.equal(output.trace.trace_action.persistent_graph_used,false);assert.equal(output.action_trace.at(-1).outcome.status,'supported');});

test('runtime rejects mixed-patient State, Evidence, or graph edge pools before retrieval',()=>{const e1=evidence('e1','患者一事实。'),e2={...evidence('e2','患者二事实。'),subject_id:'other'},a=state('a','CS','患者一事实。','2025-01-01','e1'),b={...state('b','BC','患者二事实。','2025-01-01','e2'),subject_id:'other'},plan={query_type:'state_update',question:'当前事实？',keywords:['事实'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'current'};assert.throws(()=>executeCareHarnessPolicy(plan,[a,b],[e1,e2]),/exactly one patient subject/);assert.throws(()=>executeCareHarnessPolicy(plan,[a],[e1,e2]),/exactly one patient subject/);const foreignEdge={edge_id:'foreign',subject_id:'other',from_state_id:'a',to_state_id:'a2',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1'],status:'verified',verified:true,causal_claim:false};assert.throws(()=>executeCareHarnessPolicy(plan,[a],[e1],{graph_edges:[foreignEdge]}),/exactly one patient subject/);});

test('current resolved or inactive head is retained as the current negative or invalidated fact',()=>{for(const status of ['resolved','inactive']){const e1=evidence(`${status}-old`,'既往症状。'),e2=evidence(`${status}-head`,'当前症状已消失。'),old=state(`${status}-old`,'PE','患者既往有恶心。','2025-01-01',e1.evidence_id,{factor_key:'nausea'}),head=state(`${status}-head`,'PE','患者当前恶心已消失。','2025-02-01',e2.evidence_id,{factor_key:'nausea',status,version:2,version_chain:[old.state_id],operation:'RESOLVE'}),result=verifyWorkingState([old,head],[],new Map([[e1.evidence_id,e1],[e2.evidence_id,e2]]),{query_plan:{temporal_operator:'current'},full_visible_states:[old,head]});assert.deepEqual(result.states.map(item=>item.state_id),[head.state_id]);assert.equal(result.rejected_states[0].reason,'superseded_for_current_view');assert.equal(result.rejected_states[0].blocking,false);assert.equal(result.safe_to_answer,true);}});

test('stale endpoints and their relations cannot survive the current-view verifier',()=>{const evidenceItems=[evidence('e1','旧临床状态。'),evidence('e2','最新临床状态。'),evidence('e3','治疗计划。'),evidence('e4','治疗结局。')],old=state('old-safe','CS','旧临床状态。','2025-01-01','e1',{factor_key:'glucose'}),latest=state('latest-safe','CS','最新临床状态。','2025-04-01','e2',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['old-safe']}),plan=state('plan-safe','CP','治疗计划。','2025-04-02','e3'),outcome=state('outcome-safe','LO','治疗结局。','2025-04-03','e4'),edge=(edge_id,from_state_id,to_state_id,relation_type,evidence_ids,edge_family='clinical_care',semantic_support=edge_family==='clinical_care')=>({edge_id,subject_id:'p',from_state_id,to_state_id,edge_family,relation_type,evidence_ids,confidence:1,support_kind:semantic_support?'asserted':'structural',semantic_support,status:'verified',verified:true,persistent:true,causal_claim:false,source:semantic_support?'patient_graph_relation_verifier':'version_transition'}),edges=[edge('old-latest','old-safe','latest-safe','updates',['e1','e2'],'temporal'),edge('latest-plan','latest-safe','plan-safe','informs',['e2','e3']),edge('plan-outcome','plan-safe','outcome-safe','informs',['e3','e4'])],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'最新临床状态、治疗计划和治疗结局是什么？',target:'治疗结局',keywords:['临床状态','治疗计划','治疗结局'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'latest'},[old,latest,plan,outcome],evidenceItems,{graph_edges:edges,candidate_budget:12,action_budget:6});assert.equal(output.states.some(item=>item.state_id==='old-safe'),false);assert.equal(output.relations.some(item=>item.from_state_id==='old-safe'||item.to_state_id==='old-safe'),false);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.verification.safe_to_answer,true);assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');});

test('model-checked query-local relations require one explicit span binding both endpoint claims',()=>{const evidenceItems=[evidence('e1','为控制糖尿病病情，医生开始二甲双胍治疗。'),evidence('e2','患者接受二甲双胍治疗后，血糖控制仍然恶化。')],items=[state('s1','CS','糖尿病病情','2025-01-01','e1'),state('s2','CP','二甲双胍治疗','2025-02-01','e1',{evidence_ids:['e1','e2']}),state('s3','LO','血糖控制仍然恶化','2025-03-01','e2')],plan={query_type:'multi_hop_clinical_deduction',question:'治疗后为什么仍恶化？',target:'恶化',keywords:['糖尿病','二甲双胍','血糖','恶化'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'s2',to_state_id:'s1',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'为控制糖尿病病情，医生开始二甲双胍治疗',from_claim_quote:'二甲双胍治疗',to_claim_quote:'糖尿病病情',assessment:'supports',confidence:.91},{from_state_id:'s2',to_state_id:'s3',relation_type:'observed_after_care',relation_evidence_id:'e2',relation_quote:'患者接受二甲双胍治疗后，血糖控制仍然恶化',from_claim_quote:'二甲双胍治疗',to_claim_quote:'血糖控制仍然恶化',assessment:'supports',confidence:.9}],competing_hypotheses_checked:true,competing_hypotheses:['依从或机制变化'],missing_evidence:[],no_link_reason:'不得进入 Answer 输入的自由文本'},output=applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items});assert.equal(baseline.proof.verdict,'unresolved');assert.equal(output.proof.verdict,'supported');assert.equal(output.proof.path_complete,true);assert.equal(output.relations.length,2);assert.ok(output.relations.every(item=>item.persistent===false&&item.semantic_support===true&&item.causal_claim===false&&item.support_kind==='model_verified_explicit_relation_span'));assert.equal(output.action_trace.at(-1).outcome.status,'supported');assert.doesNotMatch(JSON.stringify({proof:output.proof,working_state:output.working_state}),/依从或机制变化|不得进入 Answer 输入/);});

test('explicit chronology is audit-only and invalid relation spans never complete a complex path',()=>{const evidenceItems=[evidence('e1','医生先安排血糖监测，患者之后报告血糖下降。')],items=[state('cp','CP','安排血糖监测','2025-01-01','e1'),state('lo','LO','报告血糖下降','2025-02-01','e1')],plan={query_type:'inference_generation',question:'监测是否导致血糖下降？',keywords:['监测','血糖下降'],state_scopes:[{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),followed={verdict:'unresolved',relations:[{from_state_id:'cp',to_state_id:'lo',relation_type:'followed_by',relation_evidence_id:'e1',relation_quote:'医生先安排血糖监测，患者之后报告血糖下降',from_claim_quote:'安排血糖监测',to_claim_quote:'报告血糖下降',assessment:'supports',confidence:.95}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:['因果证据'],no_link_reason:'只有时间顺序'},ordered=applyQueryTimeRelationEvaluation(plan,baseline,followed,{full_visible_states:items});assert.equal(ordered.relations[0].semantic_support,false);assert.equal(ordered.proof.verdict,'unresolved');assert.equal(ordered.action_trace.at(-1).outcome.status,'uncertain');const bad={...followed,verdict:'supported',missing_evidence:[],relations:[{...followed.relations[0],relation_type:'observed_after_care',relation_quote:'不存在的原文同时提到安排血糖监测和报告血糖下降'}]},rejected=applyQueryTimeRelationEvaluation(plan,baseline,bad,{full_visible_states:items});assert.equal(rejected.relations.length,0);assert.equal(rejected.trace.semantic_relation_evaluator.rejected[0].reason,'relation_quote_not_verbatim');assert.equal(rejected.proof.verdict,'unresolved');});

test('relation evaluator schema rejects generic links and missing relation-bearing spans',()=>{for(const relation_type of ['informs','supports_hypothesis'])assert.throws(()=>validateQueryTimeRelationEvaluation({verdict:'supported',relations:[{from_state_id:'a',to_state_id:'b',relation_type,relation_evidence_id:'e',relation_quote:'explicit relation text',from_claim_quote:'claim one',to_claim_quote:'claim two',assessment:'supports',confidence:.9}]}),/invalid relation_type/);assert.throws(()=>validateQueryTimeRelationEvaluation({verdict:'supported',relations:[{from_state_id:'a',to_state_id:'b',relation_type:'constrains',assessment:'supports',confidence:.9}]}),/requires one relation-bearing Evidence quote/);});

test('semantic relation meaning is model-checked while deterministic verification stays language-agnostic',()=>{const evidenceItems=[evidence('e1','患者喜欢蓝色，医生开始二甲双胍治疗。')],items=[state('pa','PA','患者喜欢蓝色','2025-01-01','e1'),state('cp','CP','二甲双胍治疗','2025-01-01','e1')],plan={query_type:'inference_generation',question:'偏好是否影响治疗？',keywords:['偏好','治疗'],state_scopes:[{family:'PA',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'pa',to_state_id:'cp',relation_type:'motivates',relation_evidence_id:'e1',relation_quote:'患者喜欢蓝色，医生开始二甲双胍治疗',from_claim_quote:'患者喜欢蓝色',to_claim_quote:'二甲双胍治疗',assessment:'supports',confidence:1}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:[],no_link_reason:''},output=applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items});assert.equal(output.relations.length,1);assert.equal(output.proof.verdict,'supported');assert.equal(output.action_trace.at(-1).outcome.status,'supported');});

test('an unresolved or contradicted overall evaluation cannot launder a supported semantic edge',()=>{const evidenceItems=[evidence('e1','患者有明确诊断。'),evidence('e2','医生记录治疗计划。')],items=[state('cs','CS','患者有明确诊断。','2025-01-01','e1'),state('cp','CP','医生记录治疗计划。','2025-01-02','e2')],plan={query_type:'inference_generation',question:'诊断与计划是否支持结论？',keywords:['诊断','治疗计划'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),relation={from_state_id:'cp',to_state_id:'cs',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'患者有明确诊断',from_claim_quote:'治疗计划',to_claim_quote:'明确诊断',assessment:'supports',confidence:.95};for(const verdict of ['unresolved','contradicted']){const output=applyQueryTimeRelationEvaluation(plan,baseline,{verdict,relations:[relation],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:verdict==='unresolved'?['缺少关系证据']:[],no_link_reason:'总体不支持'},{full_visible_states:items});assert.equal(output.relations.length,0);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');assert.match(output.trace.semantic_relation_evaluator.rejected[0].reason,/overall_verdict/);}});

test('semantic relation application cannot erase an earlier blocking verification failure',()=>{const evidenceItems=[evidence('e1','患者有明确诊断。'),evidence('e2','医生记录治疗计划。'),evidence('e3','患者记录存在冲突。')],items=[state('cs','CS','患者有明确诊断。','2025-01-01','e1'),state('cp','CP','医生记录治疗计划。','2025-01-02','e2'),state('bad','LO','患者记录存在冲突。','2025-01-03','e3',{status:'conflict'})],plan={query_type:'inference_generation',question:'诊断与计划是否支持结论？',keywords:['诊断','治疗计划','冲突'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'}],temporal_operator:'history'},baseline=executeCareHarnessPolicy(plan,items,evidenceItems,{candidate_budget:8,action_budget:6}),evaluation={verdict:'supported',relations:[{from_state_id:'cp',to_state_id:'cs',relation_type:'care_targets',relation_evidence_id:'e1',relation_quote:'患者有明确诊断',from_claim_quote:'治疗计划',to_claim_quote:'明确诊断',assessment:'supports',confidence:.95}],competing_hypotheses_checked:true,competing_hypotheses:[],missing_evidence:[],no_link_reason:''};assert.equal(baseline.verification.safe_to_answer,false);assert.throws(()=>applyQueryTimeRelationEvaluation(plan,baseline,evaluation,{full_visible_states:items}),/requires a deterministically verified/);});

test('post-verification evaluation recomputes the path and answer becomes uncertain when a stale bridge is removed',()=>{const evidenceItems=[evidence('e1','旧临床状态。'),evidence('e2','治疗计划。'),evidence('e3','结局。'),evidence('e4','最新临床状态。')],old=state('old','CS','旧临床状态。','2025-01-01','e1',{factor_key:'glucose',version:1}),plan=state('plan','CP','治疗计划。','2025-02-01','e2'),outcome=state('outcome','LO','治疗后结局。','2025-03-01','e3'),latest=state('latest','CS','最新临床状态。','2025-04-01','e4',{factor_key:'glucose',version:2,operation:'UPDATE',version_chain:['old']}),edges=[{edge_id:'old-plan',subject_id:'p',from_state_id:'old',to_state_id:'plan',edge_family:'clinical_care',relation_type:'informs',evidence_ids:['e1','e2'],confidence:.9,support_kind:'asserted',status:'verified',verified:true,persistent:true,causal_claim:false},{edge_id:'plan-outcome',subject_id:'p',from_state_id:'plan',to_state_id:'outcome',edge_family:'clinical_care',relation_type:'followed_by',evidence_ids:['e2','e3'],confidence:.9,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false}],output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'当前治疗与结局如何关联？',target:'治疗结局',keywords:['临床','治疗','结局'],state_scopes:[{family:'CS',priority:'primary'},{family:'CP',priority:'primary'},{family:'LO',priority:'primary'}],temporal_operator:'latest'},[old,plan,outcome,latest],evidenceItems,{graph_edges:edges,candidate_budget:12,action_budget:6});assert.equal(output.states.some(item=>item.state_id==='old'),false);assert.equal(output.proof.verdict,'unresolved');assert.equal(output.proof.path_complete,false);assert.equal(output.action_trace.at(-1).outcome.status,'uncertain');});

test('answer reports budget exhaustion when required complex actions are omitted',()=>{const e=evidence('e1','患者事实。'),output=executeCareHarnessPolicy({query_type:'multi_hop_clinical_deduction',question:'为什么？',keywords:['患者'],state_scopes:[{family:'CS',priority:'primary'}],temporal_operator:'history'},[state('s','CS','患者事实。','2025-01-01','e1')],[e],{candidate_budget:4,action_budget:3});assert.deepEqual(output.action_policy.selected_actions,['focus','verify','answer']);assert.equal(output.action_trace.at(-1).outcome.status,'budget-exhausted');assert.equal(output.action_trace.at(-1).outcome.reason,'required_actions_omitted_by_budget');});
