import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Store } from '../src/db.js';

test('SQLite configures lock waiting before migrations and keeps WAL enabled',()=>{const dir=mkdtempSync(join(tmpdir(),'careharness-db-')),path=join(dir,'test.sqlite');try{const store=new Store(path);assert.equal(store.db.prepare('PRAGMA busy_timeout').get().timeout,5000);assert.equal(store.db.prepare('PRAGMA journal_mode').get().journal_mode,'wal');store.close()}finally{rmSync(dir,{recursive:true,force:true})}});

test('startup leaves historical payloads on disk and cleans them lazily when read',()=>{const dir=mkdtempSync(join(tmpdir(),'careharness-db-')),path=join(dir,'test.sqlite');try{const first=new Store(path),now=new Date().toISOString(),legacy='{"observation_id":"obs-1","subject_id":"patient","source_type":"patient","episode_id":"session-1","turn_id":"1","event_time":null,"raw_text":"hello","derived":{"legacy":true}}';first.db.prepare('INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('run-1','patient','test','completed','formal',42,'{}','{}',now,now,'{}',null);first.db.prepare('INSERT INTO observations VALUES(?,?,?,?,?,?,?)').run('obs-1','run-1','patient','session-1','1','patient',legacy);first.db.exec('CREATE TABLE update_audit(n INTEGER);CREATE TRIGGER audit_observation_update AFTER UPDATE ON observations BEGIN INSERT INTO update_audit VALUES(1);END;');first.close();const second=new Store(path);assert.equal(second.db.prepare('SELECT COUNT(*) AS n FROM update_audit').get().n,0);assert.equal(second.db.prepare('SELECT payload_json FROM observations WHERE id=?').get('obs-1').payload_json,legacy);assert.deepEqual(second.observationsForIds(['obs-1']),[{observation_id:'obs-1',subject_id:'patient',source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:null,raw_text:'hello'}]);second.close()}finally{rmSync(dir,{recursive:true,force:true})}});

test('observationsForIds returns unique raw records in requested order',()=>{const store=new Store(':memory:'),now=new Date().toISOString();store.db.prepare('INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('run-obs','patient','test','completed','formal',42,'{}','{}',now,now,'{}',null);const insert=store.db.prepare('INSERT INTO observations VALUES(?,?,?,?,?,?,?)');for(const id of ['obs-1','obs-2'])insert.run(id,'run-obs','patient','session-1',id,'patient',JSON.stringify({observation_id:id,subject_id:'patient',source_type:'patient',episode_id:'session-1',turn_id:id,event_time:null,raw_text:id}));assert.deepEqual(store.observationsForIds(['obs-2','obs-1','obs-2','missing']).map(item=>item.observation_id),['obs-2','obs-1']);store.close()});
