import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Store } from '../src/db.js';

test('SQLite configures lock waiting before migrations and keeps WAL enabled',()=>{const dir=mkdtempSync(join(tmpdir(),'careharness-db-')),path=join(dir,'test.sqlite');try{const store=new Store(path);assert.equal(store.db.prepare('PRAGMA busy_timeout').get().timeout,60000);assert.equal(store.db.prepare('PRAGMA journal_mode').get().journal_mode,'wal');store.close()}finally{rmSync(dir,{recursive:true,force:true})}});
test('new storage has only unified memory tables',()=>{const store=new Store(':memory:'),tables=new Set(store.db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(row=>row.name));for(const table of['memory_nodes','memory_edges','memory_graph_checkpoints','memory_scopes'])assert.ok(tables.has(table));for(const table of['evidence','states','patient_graph_nodes','patient_graph_edges'])assert.equal(tables.has(table),false);store.close()});
test('Memory Graph returns one multi-family semantic node and separate episode membership metadata',()=>{const store=new Store(':memory:'),now=new Date().toISOString(),run='run-graph',subject='patient',node={memory_id:'memory-1',observation_id:'obs-1',subject_id:subject,text:'同一条患者事实。',source_text:'同一条患者事实。',span:[0,9],families:['PE','CS'],factor_key:'topic:事实',factor_domains:['biological'],status:'active',polarity:'affirmed',certainty:1,source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2025-01-01',valid_from:'2025-01-01',version:1,version_chain:[],predecessor_memory_id:null,successor_memory_id:null,conflicts_with_memory_id:null,operation:'ADD'};store.db.prepare('INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(run,subject,'test','completed','formal',42,'{}','{}',now,now,'{}',null);store.db.prepare('INSERT INTO memory_nodes VALUES(?,?,?,?,?,?,?,?)').run(node.memory_id,run,subject,node.observation_id,node.episode_id,node.status,node.version,JSON.stringify(node));const graph=store.memoryGraphFor(subject);assert.equal(graph.version,'careharness-memory-graph.v2-semantic-state');assert.equal(graph.nodes.length,1);assert.strictEqual(graph.nodes[0].memory_id,node.memory_id);assert.deepEqual(graph.nodes[0].families,['PE','CS']);assert.deepEqual(graph.episode_memberships,[{episode_id:'session-1',memory_ids:['memory-1']}]);assert.equal(graph.summary.context_edge_count,0);assert.equal(Object.hasOwn(graph,'concept_graph'),false);store.close()});
