import test from 'node:test';
import assert from 'node:assert/strict';
import { ModelGateway } from '../src/gateway.js';

test('gateway increases structured-output budget after a length-truncated response',async()=>{
  const gateway=new ModelGateway({provider:'openai-compatible',base_url:'https://provider.test/v1',model:'test-model',max_tokens:1200,retries:1},{apiKey:'memory-key'}),originalFetch=globalThis.fetch,budgets=[],prompts=[];let call=0;
  globalThis.fetch=async(_url,options)=>{const body=JSON.parse(options.body);budgets.push(body.max_tokens);prompts.push(body.messages.at(-1).content);call++;return new Response(JSON.stringify({choices:[{message:{content:call===1?'{"partial":"x"':'{"ok":true}'},finish_reason:call===1?'length':'stop'}],usage:{completion_tokens:call===1?body.max_tokens:4}}),{status:200})};
  try{const result=await gateway.completeJSON('extractor','x'.repeat(1000),value=>value,()=>({ok:true}));assert.deepEqual(budgets,[2500,5000]);assert.equal(result.value.ok,true);assert.equal(result.trace.finish_reason,'stop');assert.equal(result.trace.requested_max_tokens,5000);assert.equal(result.trace.raw_model_attempts[0].finish_reason,'length');assert.match(prompts[1],/Start over from the original INPUT/);assert.match(prompts[1],/at most 24 highest-priority durable Evidence items/);assert.doesNotMatch(prompts[1],/\{"partial":"x"/)}finally{globalThis.fetch=originalFetch}
});

test('DashScope requests disable thinking for low-latency structured extraction',async()=>{const gateway=new ModelGateway({provider:'dashscope',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen3.5-flash',retries:0},{apiKey:'dashscope-key'}),originalFetch=globalThis.fetch;let request;globalThis.fetch=async(_url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}]}),{status:200})};try{const result=await gateway.completeJSON('judge',{question:'测试'},value=>value,()=>({ok:true}));assert.equal(result.value.ok,true);assert.equal(request.enable_thinking,false);assert.equal(request.model,'qwen3.5-flash')}finally{globalThis.fetch=originalFetch}});

test('Router uses provider strict JSON Schema when the selected model supports it',async()=>{const gateway=new ModelGateway({provider:'dashscope',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen3.7-plus',retries:0},{apiKey:'dashscope-key'}),originalFetch=globalThis.fetch;let request;globalThis.fetch=async(_url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({choices:[{message:{content:'{"families":[["PA"],[]]}'},finish_reason:'stop'}]}),{status:200})};try{const input=[{id:'0',text:'a',source:'patient'},{id:'1',text:'b',source:'doctor'}],result=await gateway.completeJSON('router',input,value=>value,()=>null);const families=request.response_format.json_schema.schema.properties.families;assert.equal(request.response_format.type,'json_schema');assert.equal(request.response_format.json_schema.strict,true);assert.equal(families.minItems,2);assert.equal(families.maxItems,2);assert.deepEqual(families.items.items.enum,['BC','PE','PA','CS','CP','LO']);assert.equal(result.trace.schema_enforcement,'provider_strict_json_schema')}finally{globalThis.fetch=originalFetch}});

test('Router applies the same strict application schema when Qwen 3.5 only supports JSON Object mode',async()=>{const gateway=new ModelGateway({provider:'dashscope',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen3.5-flash',retries:0},{apiKey:'dashscope-key'}),originalFetch=globalThis.fetch;let request;globalThis.fetch=async(_url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({choices:[{message:{content:'{"families":[["PA"]]}'},finish_reason:'stop'}]}),{status:200})};try{const result=await gateway.completeJSON('router',[{id:'0',text:'a',source:'patient'}],value=>value,()=>null);assert.equal(request.response_format.type,'json_object');assert.equal(result.trace.schema_enforcement,'application_strict_json_schema');assert.equal(result.trace.response_format.type,'json_object');assert.equal(result.trace.output_json_schema.strict,true);assert.equal(result.trace.output_json_schema.schema.properties.families.minItems,1)}finally{globalThis.fetch=originalFetch}});

test('benchmark answer transport keeps the judge JSON call and carries decision-gate input',async()=>{const gateway=new ModelGateway({provider:'openai-compatible',base_url:'https://provider.test/v1',model:'answer-model',max_tokens:1200,retries:0},{apiKey:'memory-key'}),originalFetch=globalThis.fetch;let request;globalThis.fetch=async(_url,options)=>{request=JSON.parse(options.body);return new Response(JSON.stringify({choices:[{message:{content:'{"answer":"患者已停用恩格列净。"}'},finish_reason:'stop'}]}),{status:200})};try{const input={task:'state_update',question:'目前是否服药？',answer_contract:{language:'zh-CN',format:'简短状态'},query_plan:{intent:'current status'},retrieved_states:[],retrieved_evidence:[],decision_gates:{enabled_gate_count:1,gates:{clinical_need_and_safety:{must_escalate:false}}},protocol:null},result=await gateway.completeJSON('judge',input,value=>value,()=>({answer:'mock'}));assert.equal(result.value.answer,'患者已停用恩格列净。');assert.equal(request.response_format.type,'json_object');assert.deepEqual(request.messages.map(message=>message.role),['user']);assert.equal(result.trace.prompt_version,'judge.task-contract.v4');assert.deepEqual(result.trace.model_input,input);assert.match(request.messages[0].content,/decision_gates/)}finally{globalThis.fetch=originalFetch}});

test('official Judge transport accepts the benchmark bracket-extracted JSON form',async()=>{const gateway=new ModelGateway({provider:'openai-compatible',base_url:'https://provider.test/v1',model:'judge-model',retries:0},{apiKey:'memory-key'}),originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:'评判如下：\n{"is_correct":true,"reason":"符合"}\n结束'},finish_reason:'stop'}]}),{status:200});try{const result=await gateway.completeJSON('medmemory_judge',{query_type:'state_update',question:'q',expected_answer:'a',explanation:'e',model_output:'m'},value=>value,()=>null,{extractJsonObject:true,maxTokens:500});assert.equal(result.value.is_correct,true);assert.equal(result.value.reason,'符合')}finally{globalThis.fetch=originalFetch}});
