import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../src/db.js';
import { ModelRegistry } from '../src/model-registry.js';
import { CareLifecycle } from '../src/lifecycle.js';

const item=(text,source_type,turn_id)=>({subject_id:'life-patient',source_type,episode_id:'session-1',turn_id:String(turn_id),event_time:'2026-01-01',raw_text:text});

test('memory build reads one complete historical Session without generating replies or Gates',async()=>{const store=new Store(':memory:'),life=new CareLifecycle(store,new ModelRegistry(store));const built=await life.buildMemory([item('既往记录：对青霉素过敏。','structured',0),item('我最近有时会恶心。','patient',1),item('建议下周复诊。','doctor',2)]);assert.equal(built.processed,1);assert.equal(built.source_observations,3);assert.equal(built.runs[0].final.observation.source_type,'structured');assert.match(built.runs[0].final.observation.raw_text,/\[Role=Patient\]/);assert.match(built.runs[0].final.observation.raw_text,/\[Role=Doctor\]/);for(const run of built.runs){assert.equal(run.phase,'memory_build');assert.equal(run.final.response,null);assert.equal(run.traces.some(x=>x.component.startsWith('gate_')),false);assert.equal(run.traces.some(x=>x.component==='action_policy'),false)}assert.ok(built.memory.length);store.close()});

test('new conversation commits Patient first and Doctor response second for the next turn',async()=>{const store=new Store(':memory:'),life=new CareLifecycle(store,new ModelRegistry(store));await life.buildMemory([item('建议下周复诊。','doctor',1)]);const result=await life.converse({...item('我按时吃药了，但还是会恶心。','patient',2),episode_id:'session-2'});assert.equal(result.conversation.final.phase,'conversation');assert.ok(result.conversation.final.action);assert.equal(result.conversation.traces.some(x=>x.component.startsWith('gate_')),false);assert.ok(result.feedback);assert.equal(result.feedback.final.observation.source_type,'doctor');assert.equal(result.feedback.final.observation.raw_text,result.conversation.final.response);assert.equal(result.memory_ready_for_next_turn,true);assert.deepEqual(result.writes.map(x=>[x.sequence,x.role,x.committed]),[[1,'patient',true],[2,'doctor',true]]);const written=store.db.prepare(`SELECT source_type,payload_json FROM observations WHERE episode_id='session-2' ORDER BY rowid`).all();assert.deepEqual(written.map(x=>x.source_type),['patient','doctor']);assert.equal(JSON.parse(written[1].payload_json).raw_text,result.conversation.final.response);store.close()});

test('phase 2 and Doctor feedback use one Patient Graph updater and keep communication policy separate',async()=>{const store=new Store(':memory:'),life=new CareLifecycle(store,new ModelRegistry(store));await life.buildMemory([item('患者对青霉素过敏。','structured',1)],{reset_memory:true});const result=await life.converse({...item('我按时吃药了，但有时候会恶心。','patient',2),episode_id:'session-2'}),removed=['derived','normalization','speaker','normalized_entity','numbers','relation_hints','checkpoint','entity','relations','operation_reason','derived_from'],removedSteps=['entity_relation_linker','temporal_reconciler','state_validity','updater_bc','updater_pe','updater_pa','updater_cs','updater_cp','updater_lo'];for(const run of [result.conversation,result.feedback]){const names=run.traces.map(x=>x.component);for(const step of removedSteps)assert.equal(names.includes(step),false,`${run.phase}:${step}`);assert.equal(names.filter(step=>step==='patient_graph_updater').length,1);const structured=JSON.stringify({observation:run.final.observation,evidence:run.final.evidence,states:run.final.states,deltas:run.final.deltas,memory:run.final.memory});for(const field of removed)assert.equal(new RegExp(`"${field}"\\s*:`).test(structured),false,`${run.phase}:${field}`)}assert.deepEqual(result.conversation.traces.map(x=>x.component),['observation_ingest','atomic_evidence_extractor','multi_label_router','patient_graph_updater','patient_memory_commit','action_policy','response_generator','response_auditor','conversation_commit']);assert.equal(result.feedback.traces.length,5);const policyInput=result.conversation.traces.find(x=>x.component==='action_policy').input;assert.deepEqual(Object.keys(policyInput).sort(),['current_patient_message','memory']);assert.equal('validity_warnings'in policyInput,false);const generatorMemory=result.conversation.traces.find(x=>x.component==='response_generator').input.memory;assert.equal(JSON.stringify(generatorMemory).includes('entity'),false);assert.equal(result.feedback.final.states.length,0);assert.equal(result.memory.some(x=>x.source_type==='doctor'),false);assert.ok(result.patient_graph);store.close()});

test('memory build can clear one patient State memory while preserving audit Runs',async()=>{const store=new Store(':memory:'),life=new CareLifecycle(store,new ModelRegistry(store));await life.buildMemory([item('我有时恶心。','patient',1)]);const before=store.listRuns().length,result=await life.buildMemory([item('患者对青霉素过敏。','structured',2)],{reset_memory:true});assert.ok(result.cleared>0);assert.equal(store.statesFor('life-patient').some(x=>/恶心/.test(x.value)),false);assert.ok(store.listRuns().length>before);store.close()});

test('State Explorer subject index follows stored memory and removal preserves Runs',async()=>{const store=new Store(':memory:'),life=new CareLifecycle(store,new ModelRegistry(store));await life.buildMemory([item('我有时恶心。','patient',1),{...item('患者对青霉素过敏。','structured',1),subject_id:'other-patient'}]);assert.deepEqual(new Set(store.memorySubjects().map(x=>x.subject_id)),new Set(['life-patient','other-patient']));const runCount=store.listRuns().length;assert.ok(store.clearMemory('other-patient')>0);assert.equal(store.memorySubjects().some(x=>x.subject_id==='other-patient'),false);assert.equal(store.listRuns().length,runCount);store.close()});

test('Patient memory remains committed when Doctor response generation fails',async()=>{const store=new Store(':memory:'),registry=new ModelRegistry(store);const broken=registry.save({name:'Broken generator',config:{provider:'openai-compatible',base_url:'https://provider.invalid/v1',model:'qwen'}});registry.assign({global:'offline-mock',generator:broken.id});const life=new CareLifecycle(store,registry),patient={...item('我今天仍然恶心。','patient',3),subject_id:'failure-patient',episode_id:'session-failure'};await assert.rejects(()=>life.converse(patient),error=>{assert.equal(error.publicError.write_progress.committed,true);assert.equal(error.publicError.write_progress.doctor_committed,false);return true});const written=store.db.prepare(`SELECT source_type FROM observations WHERE subject_id='failure-patient' ORDER BY rowid`).all();assert.deepEqual(written.map(x=>x.source_type),['patient']);assert.ok(store.statesFor('failure-patient').length>0);store.close()});
