import test from'node:test';import assert from'node:assert/strict';import{STATE_FAMILIES,validateEvidence,validateObservation,validateProviderConfig,validateState,SchemaError,sanitizeSecrets}from'../src/schema.js';
test('core rejects query, gold and derived protocol data as observations',()=>{for(const source_type of ['query','gold_answer','answer_options','judge_score','derived'])assert.throws(()=>validateObservation({subject_id:'p',source_type,episode_id:'1',turn_id:'1',raw_text:'leak'}),SchemaError)});
test('observation schema contains only identity, source type, order, time and text',()=>{const value=validateObservation({subject_id:'p',source_type:'patient',episode_id:'session-1',turn_id:'1',raw_text:'hello'});assert.deepEqual(Object.keys(value),['observation_id','subject_id','source_type','episode_id','turn_id','event_time','raw_text']);for(const extra of [{speaker:'Patient'},{dataset:'x'},{checkpoint:1}])assert.throws(()=>validateObservation({...value,...extra}),/unsupported observation fields/)});
test('provider rejects raw keys and sanitizes nested secrets',()=>{assert.throws(()=>validateProviderConfig({provider:'mock',model:'m',api_key:'secret'}));assert.deepEqual(sanitizeSecrets({api_key:'x',nested:{token:'y',api_key_ref:'OPENAI_API_KEY'}}),{api_key:'[REDACTED]',nested:{token:'[REDACTED]',api_key_ref:'OPENAI_API_KEY'}})});
test('provider presets validate real OpenAI-compatible endpoints',()=>{for(const provider of ['openai','deepseek','openrouter','openai-compatible'])assert.equal(validateProviderConfig({provider,model:'m',base_url:'https://example.test/v1'}).provider,provider);assert.throws(()=>validateProviderConfig({provider:'openai',model:'m'}),SchemaError)});
test('DashScope validates as a first-class provider',()=>{const value=validateProviderConfig({provider:'dashscope',base_url:'https://dashscope.aliyuncs.com/compatible-mode/v1',model:'qwen3.5-flash'});assert.equal(value.provider,'dashscope');assert.equal(value.base_url,'https://dashscope.aliyuncs.com/compatible-mode/v1')});
test('Evidence uses Session provenance and validates legacy spans only when present',()=>{const e={evidence_id:'e',observation_id:'o',subject_id:'p',text:'患者有症状',source_type:'structured',episode_id:'session-1',source_session_id:'session-1',polarity:'affirmed',certainty:1};assert.doesNotThrow(()=>validateEvidence(e));assert.throws(()=>validateEvidence({...e,span:[1,1]}),SchemaError);assert.doesNotThrow(()=>validateEvidence({...e,span:[0,1]}))});
test('Evidence source is limited to Patient, Doctor or Structured provenance',()=>{const e={evidence_id:'e',observation_id:'o',subject_id:'p',text:'患者有症状',source_type:'derived',episode_id:'s',polarity:'affirmed',certainty:1,span:[0,1]};assert.throws(()=>validateEvidence(e),/invalid evidence source_type/)});
test('State schema validates only the six controlled families',()=>{const base={state_id:'s',subject_id:'p',family:'PE',value:'患者口渴。',status:'active',evidence_ids:['e'],version_chain:[]};for(const family of STATE_FAMILIES)assert.doesNotThrow(()=>validateState({...base,family}),family);assert.throws(()=>validateState({...base,family:'OTHER'}),/invalid state family/)});
