import test from 'node:test';
import assert from 'node:assert/strict';
import { MEMORY_FAMILIES,SchemaError,inspectMemoryNodeSourceAlignment,isAnswerableMemoryNode,sanitizeSecrets,sourceGroundedMemoryGraph,validateMemoryEdge,validateMemoryNode,validateObservation,validateProviderConfig } from '../src/schema.js';

const memoryNode=(extra={})=>({memory_id:'m1',observation_id:'o1',subject_id:'p',text:'患者口渴。',source_text:'患者口渴。',span:[0,6],source_type:'patient',episode_id:'session-1',turn_id:'1',event_time:'2026-01-01',certainty:1,polarity:'affirmed',families:['PE','CS'],factor_key:'topic:口渴',factor_domains:['biological'],status:'active',valid_from:'2026-01-01',version:1,version_chain:[],predecessor_memory_id:null,successor_memory_id:null,conflicts_with_memory_id:null,operation:'ADD',...extra});

test('core rejects query, gold and derived protocol data as observations',()=>{for(const source_type of ['query','gold_answer','answer_options','judge_score','derived'])assert.throws(()=>validateObservation({subject_id:'p',source_type,episode_id:'1',turn_id:'1',raw_text:'leak'}),SchemaError)});
test('observation schema contains only identity, provenance, time and text',()=>{const value=validateObservation({subject_id:'p',source_type:'patient',episode_id:'session-1',turn_id:'1',raw_text:'hello'});assert.deepEqual(Object.keys(value),['observation_id','subject_id','source_type','episode_id','turn_id','event_time','raw_text']);for(const extra of [{speaker:'Patient'},{dataset:'x'},{checkpoint:1}])assert.throws(()=>validateObservation({...value,...extra}),/unsupported observation fields/)});
test('Memory Node is the only patient-memory object and carries all family labels and provenance',()=>{const value=memoryNode();assert.equal(validateMemoryNode(value),value);assert.deepEqual(value.families,['PE','CS']);for(const family of MEMORY_FAMILIES)assert.doesNotThrow(()=>validateMemoryNode(memoryNode({families:[family]})));for(const forbidden of [{state_id:'s1'},{evidence_id:'e1'},{value:'projection'}])assert.throws(()=>validateMemoryNode({...value,...forbidden}),/unsupported Memory Node fields/)});
test('semantic Memory Nodes may retain verified context-unit audit metadata',()=>{assert.doesNotThrow(()=>validateMemoryNode(memoryNode({support_unit_ids:['turn-1-unit-1'],construction_kind:'semantic'})));assert.doesNotThrow(()=>validateMemoryNode(memoryNode({support_unit_ids:['turn-1-unit-2'],construction_kind:'fallback'})));assert.throws(()=>validateMemoryNode(memoryNode({support_unit_ids:[],construction_kind:'semantic'})),/support_unit_ids/);assert.throws(()=>validateMemoryNode(memoryNode({support_unit_ids:['u','u'],construction_kind:'semantic'})),/duplicates/);assert.throws(()=>validateMemoryNode(memoryNode({construction_kind:'raw'})),/construction_kind/)});
test('source grounding eligibility is stricter than backward-compatible Memory Node validation',()=>{const legacy=memoryNode({source_text:null,span:null});assert.equal(validateMemoryNode(legacy),legacy);assert.equal(isAnswerableMemoryNode(legacy),false);assert.deepEqual(inspectMemoryNodeSourceAlignment(legacy).reasons,['missing_source_text','missing_source_span']);const observation={observation_id:'o1',raw_text:'患者口渴。'},mismatched=memoryNode({source_text:'患者头痛。',span:[0,5]});assert.equal(inspectMemoryNodeSourceAlignment(mismatched,observation).aligned,false);assert.ok(inspectMemoryNodeSourceAlignment(mismatched,observation).reasons.includes('source_span_text_mismatch'))});
test('a fabricated unaligned node and its edge cannot enter the Answer-eligible graph',()=>{const eligible=memoryNode(),ungrounded=memoryNode({memory_id:'m2',text:'患者已确诊原文不存在的疾病。',source_text:null,span:null}),edge={edge_id:'edge-1',subject_id:'p',from_memory_id:'m1',to_memory_id:'m2',edge_family:'temporal',relation_type:'updates',support_memory_ids:['m1','m2'],confidence:1,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false,source:'test',created_episode_id:'session-1'},result=sourceGroundedMemoryGraph([eligible,ungrounded],[edge]);assert.deepEqual(result.nodes.map(node=>node.memory_id),['m1']);assert.equal(result.nodes.some(node=>node.text.includes('原文不存在')),false);assert.equal(result.edges.length,0);assert.equal(result.audit.shape_only_memory_node_count,2);assert.equal(result.audit.observation_verified_memory_node_count,0);assert.equal(result.audit.quarantined_memory_node_count,1);assert.deepEqual(result.audit.quarantined_memory_ids,['m2'])});
test('Memory Edge only connects Memory IDs',()=>{const edge={edge_id:'edge-1',subject_id:'p',from_memory_id:'m1',to_memory_id:'m2',edge_family:'temporal',relation_type:'updates',support_memory_ids:['m1','m2'],confidence:1,support_kind:'structural',status:'verified',verified:true,persistent:true,causal_claim:false,source:'memory_version_transition',created_episode_id:'session-2'};assert.equal(validateMemoryEdge(edge),edge);assert.throws(()=>validateMemoryEdge({...edge,from_state_id:'s1'}),/unsupported Memory Edge fields/)});
test('provider rejects raw keys and sanitizes nested secrets',()=>{assert.throws(()=>validateProviderConfig({provider:'mock',model:'m',api_key:'secret'}));assert.deepEqual(sanitizeSecrets({api_key:'x',nested:{token:'y',api_key_ref:'OPENAI_API_KEY'}}),{api_key:'[REDACTED]',nested:{token:'[REDACTED]',api_key_ref:'OPENAI_API_KEY'}})});
test('provider presets validate real OpenAI-compatible endpoints',()=>{for(const provider of ['openai','deepseek','openrouter','openai-compatible','dashscope'])assert.equal(validateProviderConfig({provider,model:'m',base_url:'https://example.test/v1'}).provider,provider);assert.throws(()=>validateProviderConfig({provider:'openai',model:'m'}),SchemaError)});
