import { existsSync,readdirSync } from 'node:fs';
import { BenchmarkAdapter,pjoin } from './base.js';
import { benchmarkAnswerContract,benchmarkQuestionPrompt } from '../prompts.js';
import { cpcdAnswerInput,cpcdAnswerMaxTokens,cpcdJudgeInput,cpcdJudgeMaxTokens,scoreCpcdJudge,scoreCpcdJudgeUnavailable,validateCpcdJudgeOutput } from '../cpcd-official.js';

const TASK_DIRS=Object.freeze({session_level_response_generation:'srg',memory_recall:'memory_recall',temporal_causal_reasoning:'TCR'});
export class CpcdBenchAdapter extends BenchmarkAdapter{
  constructor(root){super(pjoin(root,'Psy-Chronicle'));this.name='cpcdbench';}
  catalog(){const taskRoot=pjoin(this.root,'eval_task_info'),cases=this.#caseIds();return{benchmark:this.name,path:this.root,available:existsSync(taskRoot)&&cases.length>0,sample_count:159,cases,task_types:Object.keys(TASK_DIRS),task_counts:{session_level_response_generation:99,memory_recall:40,temporal_causal_reasoning:20},official_judge:'GPT-5.2 in the paper/repository; CareHarness uses the configured CPCD-Bench Judge model and records its identity.',official_metrics:{session_level_response_generation:['empathy','coherence','professionalism'],memory_recall:['accuracy','completeness','temporal_consistency','no_hallucination'],temporal_causal_reasoning:['temporal_accuracy','causal_coherence','completeness','no_hallucination']},prompt_protocol:{source_commit:'ff812c9084b606631dac3a8c01f7be0d5cbc8c8d',session_level_response_generation:'official-online-script-exact',memory_recall:'official-online-template-adapted-careharness-memory',temporal_causal_reasoning:'official-online-template-adapted-careharness-memory'},visible_boundary:'SR Answer uses only official input_to_model. MR/TCR Answer replaces the official raw-history slot with query-time CareHarness Memory Nodes. representative_point, answer_source, reference_answer, evaluation_focus, rubric and raw full history are evaluator-only and become visible after the answer is frozen.'};}
  load(config={}){const caseId=String(config.case_id||this.#caseIds()[0]||'').trim();if(!caseId)throw new Error('CPCD-Bench has no available cases');const fullPath=findFullSession(this.root,caseId),full=fullPath?this.json(fullPath):[],subjectId=`cpcd-${caseId}`,observations=[];for(let index=0;index<full.length;index+=60){const turns=full.slice(index,index+60).map((turn,offset)=>({subject_id:subjectId,source_type:/student|client|patient/i.test(turn.role)?'patient':'doctor',episode_id:`history-chunk-${Math.floor(index/60)+1}`,turn_id:String(index+offset+1),event_time:null,raw_text:String(turn.content||'').trim()})).filter(item=>item.raw_text);if(turns.length)observations.push(this.sessionObservation(turns));}const tasks=this.#tasks(caseId),rubrics=Object.fromEntries(Object.entries(TASK_DIRS).map(([task,dir])=>{const path=pjoin(this.root,'eval_task_info',dir,'rubric.md');return[task,existsSync(path)?this.text(path):''];}));return{sample_id:caseId,subject_id:subjectId,observations,tasks,rubrics,full_consultation_history:full,full_session_file:fileName(fullPath),history_chunks:observations.length,visibility:{answer_visible:['SR: official input_to_model only','MR/TCR: official question plus retrieved Memory Nodes'],judge_only:['representative_point','answer_source','reference_answer','evaluation_focus','official rubric','MR/TCR raw full consultation history'],not_visible_to_answer:['representative_point','answer_source','reference_answer','evaluation_focus','official rubric','raw full consultation history']}};}
  cases(data,config={}){const type=String(config.task_type||'all');return data.tasks.filter(task=>type==='all'||task.task_type===type).map(task=>{const protocolOnly=task.task_type==='session_level_response_generation';return{score_id:task.task_id,task:task.task_type,question:taskQuestion(task),gold:[task.reference_answer],metadata:{answer_contract:benchmarkAnswerContract(this.name,task.task_type),scope:protocolOnly?'official_task_input_only':'complete_history',long_term:true,protocol_only:protocolOnly,case_id:task.case_id||data.sample_id,task_file:task.task_file||null,full_session_file:data.full_session_file||null,official_input:task.input_to_model,representative_point:task.representative_point??null,answer_source:task.answer_source??null,evaluation_focus:task.evaluation_focus??{},official_rubric:data.rubrics?.[task.task_type]||'',full_consultation_history:protocolOnly?null:data.full_consultation_history,answer_prompt_protocol:protocolOnly?'official-online-script-exact':'official-online-template-adapted-careharness-memory',official_evaluation:{benchmark:'cpcdbench',metric:'official online-script rubric LLM-as-Judge',source_commit:'ff812c9084b606631dac3a8c01f7be0d5cbc8c8d'}}};});}
  normalizeAnswer(value){return String(value||'').trim();}
  requiresOfficialJudge(){return true;}
  officialAnswerInput(runtimeInput,item={}){return cpcdAnswerInput(runtimeInput,item);}
  officialAnswerMaxTokens(item={}){return cpcdAnswerMaxTokens(item);}
  officialJudgeInput(output,item={}){return cpcdJudgeInput(output,item);}
  officialJudgeMaxTokens(item={}){return cpcdJudgeMaxTokens(item);}
  validateOfficialJudge(value,item={}){return validateCpcdJudgeOutput(value,item);}
  scoreOfficialJudge(value,_output,item={}){return scoreCpcdJudge(value,item);}
  scoreOfficialJudgeUnavailable(_output,_item,reason){return scoreCpcdJudgeUnavailable(reason);}
  #caseIds(){const dir=pjoin(this.root,'eval_task_info','full_session');return existsSync(dir)?readdirSync(dir).filter(name=>name.endsWith('_fullsession.json')).map(name=>name.replace(/_fullsession\.json$/,'').replace(/^(.*?)(\d+)$/,'$1_$2')).sort():[];}
  #tasks(caseId){const aliases=new Set([caseId,caseId.replace('_','')]),out=[];for(const [taskType,dir] of Object.entries(TASK_DIRS)){for(const file of this.list(pjoin(this.root,'eval_task_info',dir),entry=>entry.isFile()&&entry.name.endsWith('.json'))){const stem=file.name.replace(/\.json$/,'');if(!aliases.has(stem)&&!aliases.has(stem.replace('_','')))continue;const parsed=this.json(pjoin(this.root,'eval_task_info',dir,file.name)),items=Array.isArray(parsed)?parsed:[parsed];for(const item of items)out.push({...item,task_type:item.task_type||taskType,task_file:file.name});}}return out;}
}
function findFullSession(root,caseId){const dir=pjoin(root,'eval_task_info','full_session'),compact=caseId.replace('_',''),candidates=[`${compact}_fullsession.json`,`${caseId}_fullsession.json`];return candidates.map(name=>pjoin(dir,name)).find(existsSync)||null;}
function fileName(path){return path?String(path).split(/[\\/]/u).at(-1):null;}
function taskQuestion(task){if(task.task_type!=='session_level_response_generation')return String(task.question||'');const input=task.input_to_model||{},context=(input.current_session_context||[]).map(turn=>`${turn.role}: ${turn.content}`).join('\n');return benchmarkQuestionPrompt('cpcdbench','session_level_response_generation',{student_profile_summary:input.student_profile_summary,history_until_previous_session:input.history_until_previous_session,current_session_event:input.current_session_event,current_session_context:context,current_student_utterance:input.current_student_utterance});}
