import { BenchmarkAdapter,pjoin } from './base.js';
export class MedLoCoMoAdapter extends BenchmarkAdapter{
  constructor(root){super(pjoin(root,'MedLoCoMo','MedLoCoMo'));this.name='medlocomo';}
  catalog(){const patients=this.list(this.root,d=>d.isDirectory()&&/^\d+$/.test(d.name)).map(d=>d.name);return{benchmark:this.name,path:this.root,available:patients.length>0,sample_count:patients.length,patients,visible_boundary:'Formal QA uses combined_conversation.json plus benchmark_qa.json; summaries are inspection-only.',discrepancies:[]};}
  load(config={}){const id=String(config.patient_id||'16957952'),dir=pjoin(this.root,id),combined=this.json(pjoin(dir,'combined_conversation.json')),qa=this.json(pjoin(dir,'benchmark_qa.json'));const max=config.max_admission??Infinity;const admissions=combined.admissions.slice(0,max);const observations=[];
    for(const a of admissions)for(const t of a.conversation_lines||[])observations.push(this.assertCoreObservation({subject_id:`medlocomo-${id}`,source_type:String(t.speaker).toLowerCase()==='patient'?'patient':'doctor',speaker:t.speaker,episode_id:String(a.hadm_id),turn_id:String(t.turn_number),event_time:t.time,raw_text:t.text,dataset:this.name,checkpoint:a.hadm_id,metadata:{admission_start:a.admission_start,admission_end:a.admission_end}}));
    return{sample_id:id,observations,admissions:admissions.map(a=>({hadm_id:a.hadm_id,admission_start:a.admission_start,admission_end:a.admission_end,turn_count:a.conversation_lines?.length||0})),queries:qa.qas,inspection_only:{patient_summary:pjoin(dir,'patient_summary.json'),admission_summaries:admissions.map(a=>pjoin(dir,String(a.hadm_id),'summary.json'))},visibility:{visible:['combined_conversation.admissions.conversation_lines'],inspection_only:['summary.json','patient_summary.json','previous_admission_summary'],harness_only:['benchmark_qa.qas']}};}
  cases(data){return data.queries.slice(0,20).map(q=>({score_id:q.qa_id,task:q.question_type,question:q.question,gold:[q.answer],checkpoint:q.scope,metadata:{scope:q.scope,evidence:q.evidence,long_term:q.scope==='cross_admission'}}));}
}
