import { BenchmarkAdapter,pjoin } from './base.js';
export class MedMemoryAdapter extends BenchmarkAdapter {
  constructor(root){super(pjoin(root,'MedMemoryBench','data','MedMemoryBench'));this.name='medmemorybench';}
  catalog(){const personas=this.list(this.root,d=>d.isDirectory()&&/^persona_\d+$/.test(d.name)).map(d=>d.name).sort((a,b)=>+a.split('_')[1]-+b.split('_')[1]);return{benchmark:this.name,path:this.root,available:personas.length>0,sample_count:personas.length,personas,visible_boundary:'Only dated Patient/Doctor messages are core observations. knowledge_points and queries remain read-only harness data.',discrepancies:[]};}
  load(config={}){const id=config.persona_id||1,noise=config.noise??false,dir=pjoin(this.root,`persona_${id}`,'eval');const dialog=this.json(pjoin(dir,noise?'generated_dialogues_with_noise.json':'generated_dialogues.json'));const query=this.json(pjoin(dir,'generated_queries.json'));const max=config.max_session??Infinity;
    const sessions=dialog.sessions.filter(s=>(s.session_id||0)<=max).map(s=>({session_id:s.session_id,is_noise:'noise_id'in s||'noise_family_id'in s,noise_type:'noise_family_id'in s?'family_health_consultation':'noise_id'in s?'health_knowledge':null,date:s.event_info?.date||null,turn_count:s.turn_count,messages:s.messages,knowledge_points_reference:s.knowledge_points||[]}));
    const observations=[];for(const s of sessions)for(const m of s.messages||[]) observations.push(this.assertCoreObservation({subject_id:`medmemory-persona-${id}`,source_type:m.role==='user'?'patient':'doctor',speaker:m.role==='user'?'Patient':'Doctor',episode_id:`session-${s.session_id}`,turn_id:String(m.turn??observations.length+1),event_time:s.date,raw_text:m.content,dataset:this.name,checkpoint:s.session_id,metadata:{is_noise:s.is_noise,noise_type:s.noise_type}}));
    const queries=query.queries.filter(q=>(q.session_id||0)<=max&&(config.query_type?config.query_type===q.query_type:true));return{sample_id:`persona-${id}`,observations,sessions,queries:queries.map(q=>({...q,gold:q.answers?.filter(a=>a.is_correct).map(a=>a.content)||[]})),visibility:{visible:['messages.role=user','messages.role=assistant','event_info.date'],reference_only:['knowledge_points'],harness_only:['query','answers','source_key_points','metadata']}};}
  cases(data){return data.queries.slice(0,20).map(q=>({score_id:q.query_id,task:q.query_type,question:q.question,gold:q.gold,checkpoint:q.session_id,metadata:{answers:q.answers,source_key_points:q.source_key_points,long_term:['state_update','temporal_localization','multi_hop_clinical_deduction'].includes(q.query_type)}}));}
}
