import { createHash } from 'node:crypto';
import { BenchmarkAdapter,pjoin } from './base.js';
import { MEDMEMORY_QUERY_METRICS,medMemoryJudgeInput,medMemoryJudgeMaxTokens,medMemoryMetric,medMemoryRequiresJudge,scoreMedMemoryEmptyAnswer,scoreMedMemoryJudge,scoreMedMemoryJudgeFailure,scoreMedMemoryOfficial,validateMedMemoryJudgeOutput } from '../medmemory-official.js';
import { benchmarkAnswerContract } from '../prompts.js';
export class MedMemoryAdapter extends BenchmarkAdapter {
  constructor(root){super(pjoin(root,'MedMemoryBench','data','MedMemoryBench'));this.name='medmemorybench';}
  catalog(){const personas=this.list(this.root,d=>d.isDirectory()&&/^persona_\d+$/.test(d.name)).map(d=>d.name).sort((a,b)=>+a.split('_')[1]-+b.split('_')[1]);return{benchmark:this.name,path:this.root,available:personas.length>0,sample_count:personas.length,personas,visible_boundary:'Each complete dated Session is one core observation; its Patient/Doctor turns remain role-attributed inside the transcript. Gold, answer explanations, Judge metadata, source_key_points and knowledge_points are excluded from memory/retrieval/answer generation and become visible only to the post-answer evaluator.',official_metrics:MEDMEMORY_QUERY_METRICS,official_judge_required_for:['temporal_localization','state_update','inference_generation','multi_hop_clinical_deduction'],discrepancies:[]};}
  load(config={}){const id=config.persona_id||1,noise=config.noise===true||config.noise==='true',subjectId=medMemorySubjectId(id,noise),memoryNamespace=noise?'with-noise':'clean',dir=pjoin(this.root,`persona_${id}`,'eval');const dialog=this.json(pjoin(dir,noise?'generated_dialogues_with_noise.json':'generated_dialogues.json'));const query=this.json(pjoin(dir,'generated_queries.json')),start=positiveSession(config.start_session??1),legacyMax=config.max_session==null?null:positiveSession(config.max_session),count=config.session_count==null?null:positiveSession(config.session_count),end=legacyMax??(count?start+count-1:Infinity);
    const prefix=selectThroughSession(dialog.sessions,end),normalized=prefix.map((s,index)=>{const isFamily='noise_family_id'in s,isHealth='noise_id'in s,isNoise=isFamily||isHealth,episode_id=isFamily?`noise-family-${s.noise_family_id}`:isHealth?`noise-health-${s.noise_id}`:`session-${s.session_id}`;return{session_id:s.session_id??null,episode_id,is_noise:isNoise,noise_type:isFamily?'family_health_consultation':isHealth?'health_knowledge':null,date:s.event_info?.date||null,turn_count:s.turn_count,messages:s.messages,original_index:index,knowledge_points_reference:s.knowledge_points||[]}}),allObservations=[],allRanges=[];let rangeStart=0;
    for(const s of normalized){const turns=(s.messages||[]).map((m,index)=>({subject_id:subjectId,source_type:m.role==='user'?'patient':'doctor',episode_id:s.episode_id,turn_id:String(m.turn??index+1),event_time:s.date,raw_text:m.content}));if(turns.length)allObservations.push(this.sessionObservation(turns));if(!s.is_noise){const prefixHash=hashObservations(allObservations);allRanges.push({session_id:Number(s.session_id),start_index:rangeStart,end_index:allObservations.length,prefix_hash:prefixHash});rangeStart=allObservations.length;}}
    const selectedRanges=allRanges.filter(r=>r.session_id>=start&&r.session_id<=end);if(!selectedRanges.length)throw new Error(`MedMemoryBench does not contain Session ${start}${Number.isFinite(end)?`–${end}`:''}`);if(count&&selectedRanges.length!==count)throw new Error(`MedMemoryBench 从 Session ${start} 起只有 ${selectedRanges.length} 个可用 Session，少于请求的 ${count} 个`);const sliceStart=selectedRanges[0].start_index,sliceEnd=selectedRanges.at(-1).end_index,observations=allObservations.slice(sliceStart,sliceEnd),sessionRanges=selectedRanges.map(r=>({...r,start_index:r.start_index-sliceStart,end_index:r.end_index-sliceStart})),selectedEpisodes=new Set(observations.map(item=>item.episode_id)),sessions=normalized.filter(s=>selectedEpisodes.has(s.episode_id)),resumeRange=allRanges.find(r=>r.session_id===start-1),resumePrefixHash=start===1?hashObservations([]):resumeRange?.prefix_hash||null;
    const queryId=String(config.query_id||'').trim(),queryIds=queryId?[queryId]:normalizeQueryIds(config.query_ids),requestedIds=new Set(queryIds),knownIds=new Set(query.queries.map(q=>String(q.query_id))),missingIds=queryIds.filter(id=>!knownIds.has(id));if(missingIds.length)throw new Error(`MedMemoryBench does not contain query_id ${missingIds.join(', ')}`);
    const typeQueries=query.queries.filter(q=>(config.query_type?config.query_type===q.query_type:true)&&(!requestedIds.size||requestedIds.has(String(q.query_id)))),queries=typeQueries.filter(q=>Number(q.session_id)>=start&&Number(q.session_id)<=end),nextQuerySession=Math.min(...typeQueries.map(q=>Number(q.session_id)).filter(n=>Number.isFinite(n)&&n>end));return{sample_id:`persona-${id}`,subject_id:subjectId,logical_subject_id:`medmemory-persona-${id}`,memory_namespace:memoryNamespace,observations,sessions,query_visibility:normalized.map(s=>({episode_id:s.episode_id,session_id:s.session_id,is_noise:s.is_noise})),session_ranges:sessionRanges,memory_window:{start_session:start,end_session:selectedRanges.at(-1).session_id,session_count:selectedRanges.length,resume_session:start-1,resume_prefix_hash:resumePrefixHash},queries:queries.map(q=>({...q,gold:q.answers?.filter(a=>a.is_correct).map(a=>a.content)||[]})),query_selection:{query_id:queryId||null,query_ids:queryIds,query_type:config.query_type||'all',selected_count:queries.length,next_available_session:Number.isFinite(nextQuerySession)?nextQuerySession:null},visibility:{visible:['messages.role=user','messages.role=assistant','event_info.date'],reference_only:['knowledge_points'],harness_only:['query','answers','source_key_points','metadata']}};}
  cases(data){return data.queries.filter(q=>String(q.question||'').trim()).map(q=>{const cutoff=data.query_visibility.findIndex(item=>!item.is_noise&&Number(item.session_id)===Number(q.session_id)),visibleEpisodes=cutoff<0?[]:data.query_visibility.slice(0,cutoff+1).map(item=>item.episode_id);return{score_id:q.query_id,task:q.query_type,question:q.question,gold:q.gold,metadata:{answer_contract:benchmarkAnswerContract(this.name,q.query_type),long_term:['state_update','temporal_localization','multi_hop_clinical_deduction'].includes(q.query_type),query_session:Number(q.session_id),visible_episode_ids:visibleEpisodes,official_evaluation:{metric:medMemoryMetric(q.query_type),answers_data:q.answers||[],metadata:q.metadata||{}}}};});}
  normalizeAnswer(output,item={}){
    const text=String(output||'').trim();
    if((item.task||item.query_type)!=='multiple_choice')return text;
    // MQ's contract is letters only. Canonicalize compact model variants such
    // as "AB" or "A， B" only when the entire response is made of option
    // letters and separators; never infer letters from explanatory prose.
    const normalized=text.normalize('NFKC').toUpperCase();
    if(!/^[A-F\s,，、;；]+$/u.test(normalized))return text;
    const letters=[...new Set(normalized.match(/[A-F]/gu)||[])].sort();
    return letters.length?letters.join(','):text;
  }
  compatibleScore(output,golds,item={}){return scoreMedMemoryOfficial(output,golds,item);}
  requiresOfficialJudge(item){return medMemoryRequiresJudge(item);}
  officialJudgeInput(output,item){return medMemoryJudgeInput(output,item);}
  officialJudgeMaxTokens(item){return medMemoryJudgeMaxTokens(item);}
  validateOfficialJudge(value,item){return validateMedMemoryJudgeOutput(value,item);}
  scoreOfficialJudge(value,item){return scoreMedMemoryJudge(value,item);}
  scoreOfficialEmptyAnswer(item){return scoreMedMemoryEmptyAnswer(item);}
  scoreOfficialJudgeFailure(item){return scoreMedMemoryJudgeFailure(item);}
}
export function medMemorySubjectId(personaId,noise=false){return`medmemory-persona-${personaId}-${noise===true||noise==='true'?'with-noise':'clean'}`;}
function selectThroughSession(sessions,max){if(max===Infinity)return sessions;let cutoff=-1;for(let i=0;i<sessions.length;i++){const s=sessions[i],isNoise='noise_id'in s||'noise_family_id'in s;if(!isNoise&&Number(s.session_id)<=Number(max))cutoff=i;}return cutoff<0?[]:sessions.slice(0,cutoff+1);}
function positiveSession(value){const n=Number(value);if(!Number.isInteger(n)||n<1)throw new Error('Session must be a positive integer');return n;}
function normalizeQueryIds(value){if(value==null||value==='')return[];const items=Array.isArray(value)?value:String(value).split(',');return[...new Set(items.map(item=>String(item||'').trim()).filter(Boolean))];}
function hashObservations(observations){return createHash('sha256').update(JSON.stringify(observations)).digest('hex');}
