import { BenchmarkAdapter,pjoin } from './base.js';
export class MusPsyAdapter extends BenchmarkAdapter{
  constructor(root){super(pjoin(root,'MusPsy'));this.name='muspsy';}
  catalog(){const users=this.list(pjoin(this.root,'datasets','dialogues'),d=>d.isFile()&&/^dialogues_\d+\.txt$/.test(d.name)).map(d=>d.name.match(/\d+/)[0]);return{benchmark:this.name,path:this.root,available:users.length>0,sample_count:users.length,users:users.slice(0,500),visible_boundary:'Task 3 Last Memory is visible as Derived protocol context, never as a new core observation.',discrepancies:['README documents dialogue/memory/card files; executable task boundaries are provided by train/task1.json, task2.json, task3.json.']};}
  load(config={}){const task=Number(config.task||1),index=Number(config.index||0),all=this.json(pjoin(this.root,'train',`task${task}.json`)),row=all[index%all.length];const turns=task===1?parseDialogue(row.input):historyTurns(row.history,row.input);const observations=turns.map((t,i)=>this.assertCoreObservation({subject_id:`muspsy-${index}`,source_type:/user/i.test(t.role)?'patient':'doctor',speaker:t.role,episode_id:`session-${config.session||1}`,turn_id:String(i+1),event_time:null,raw_text:t.text,dataset:this.name,checkpoint:config.session||1,metadata:{}}));
    const lastMemory=task===3?extractSection(row.instruction,'Last Memory'):null;return{sample_id:`task${task}-${index}`,task,observations,protocol_input:{instruction:row.instruction,input:row.input,history:row.history,last_memory:lastMemory?{source_type:'derived',protocol_visible:true,text:lastMemory,not_patient_quote:true}:null},gold_output:row.output,visibility:{visible:task===1?['current session dialogue']:task===2?['background','existing counseling memory']:['background','goal','Last Memory (Derived)','current history','latest User input'],forbidden_core_observation:['Last Memory','gold output']}};}
  cases(data){return[{score_id:data.sample_id,task:`task_${data.task}`,question:data.protocol_input.input||data.protocol_input.instruction,gold:[data.gold_output],checkpoint:data.sample_id,metadata:{protocol_input:data.protocol_input,long_term:data.task>1}}];}
}
function parseDialogue(text){const out=[];for(const m of String(text).matchAll(/(?:^|\n)(Consultant|Counselor|User|Patient|Client):\s*([\s\S]*?)(?=\n(?:Consultant|Counselor|User|Patient|Client):|$)/g))out.push({role:m[1],text:m[2].trim()});return out;}
function historyTurns(history,input){const out=[];for(const pair of history||[]){if(pair[0])out.push({role:'User',text:String(pair[0])});if(pair[1])out.push({role:'Consultant',text:String(pair[1])});}if(input)out.push({role:'User',text:String(input)});return out;}
function extractSection(text,label){const i=String(text).toLowerCase().indexOf(label.toLowerCase());return i<0?null:String(text).slice(i,i+1200);}
