import { BenchmarkAdapter,pjoin } from './base.js';
export class PsychEvalAdapter extends BenchmarkAdapter{
  constructor(root){super(pjoin(root,'PsychEval','data'));this.name='psycheval';}
  catalog(){const therapies=this.list(this.root,d=>d.isDirectory()).map(d=>d.name),cases=Object.fromEntries(therapies.map(t=>[t,this.list(pjoin(this.root,t),d=>d.isFile()&&/\.json$/.test(d.name)).length]));return{benchmark:this.name,path:this.root,available:therapies.length>0,sample_count:Object.values(cases).reduce((a,b)=>a+b,0),therapies,cases,visible_boundary:'Official mode is client_info + current single session_dialogue. Rollout is explicitly separate.',discrepancies:['Public evaluator offers session-level scores; continuity, goal tracking, and adaptive planning have data support but no separate official metric.']};}
  load(config={}){const therapy=config.therapy||'cbt',caseId=String(config.case_id||1),mode=config.mode||'official_session',data=this.json(pjoin(this.root,therapy,`${caseId}.json`)),n=Number(config.session||1),session=data.sessions.find(s=>Number(s.session_number)===n)||data.sessions[0];const selected=mode==='official_session'?[session]:data.sessions.filter(s=>Number(s.session_number)<=n);const observations=[];
    for(const s of selected)for(const t of s.session_dialogue||[])observations.push(this.assertCoreObservation({subject_id:`psycheval-${therapy}-${caseId}`,source_type:/client|patient|user/i.test(t.role)?'patient':'doctor',speaker:t.role,episode_id:`session-${s.session_number}`,turn_id:String(t.turn_number||observations.length+1),event_time:null,raw_text:t.text||t.content||'',dataset:this.name,checkpoint:s.session_number,metadata:{therapy,mode}}));
    return{sample_id:`${therapy}-${caseId}-s${n}`,mode,observations,official_evaluator_input:{client_info:data.client_info,session_dialogue:session.session_dialogue},rollout_context:mode==='rollout'?{global_plan:data.global_plan,sessions:selected.map(s=>({session_number:s.session_number,session_goals:s.session_goals,suggest_skills:s.suggest_skills,session_summary:s.session_summary,client_info_last:s.client_info_last}))}:null,visibility:{visible:mode==='official_session'?['client_info','current session_dialogue']:['client_info','global_plan','sessions through checkpoint'],data_product_only:['session_summary','client_info_last'],not_visible_in_official:['other session summaries','other session client_info_last']},metrics:['WAI','HTAIS','CTRS','RRO','Custom','PANAS','SCL-90','SRS','BDI-II']};}
  cases(data){return data.metrics.map(metric=>({score_id:`${data.sample_id}-${metric}`,task:metric,question:`Evaluate current single session with ${metric}.`,gold:[],checkpoint:data.sample_id,metadata:{official_input:data.official_evaluator_input,long_term:false,requires_external_judge:true}}));}
}
