import { randomUUID } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { ModelGateway } from './gateway.js';
import { buildVersion } from './version.js';
import { STATE_FAMILIES, validateAction, validateEvidence, validateGateTrace, validateObservation, validateRelation, validateState, validateStateDelta } from './schema.js';

const FAMILY_NAMES = { BC:'BackgroundContext', PE:'PatientExperience', PA:'PatientAppraisal', CS:'ClinicalSafety', CP:'CareProcess', LO:'LongitudinalOutcome' };
const DESCRIPTIONS = {
  raw_observation:'保留用户真正提供的原始 observation；query 与评分字段不会进入这里。', input_packetizer:'固定患者、来源、episode、turn 与时间，避免来源互相冒充。',
  atomic_evidence_extractor:'把原文拆成可由原始 span 直接支持的最小事实。', entity_relation_linker:'规范实体并建立可追踪关系。', multi_label_router:'同一证据可以进入多个 State，但每个路由保留同一原始 span。',
  temporal_reconciler:'保留时间点、版本、纠正与跨来源冲突，不物理删除历史。', state_validity:'这是 Gate 前的可用性检查，不选择行动。',
  gate_1:'先确定安全集合、禁止项、监测与强制升级。', gate_2:'再检查理解、缺失信息、冲突和时间歧义。', gate_3:'最后只在 G1 允许且 G2 足够的集合中排序。',
  action_policy:'用结构化规则选择 ASK / VERIFY / ESCALATE / ANSWER 等行动。', response_generator:'只表达 Policy 已选择的行动，不能自行改写决策。',
  response_auditor:'发送前检查证据、Gate、安全和必需内容。', commit_feedback:'Auditor 通过后才事务提交 evidence、State 和关系。'
};

export class Pipeline {
  constructor(store, config = {}) { this.store=store; this.config=config; this.gateway=new ModelGateway(config.model || {provider:'mock',model:'careharness-rules-v1'}); }

  async run(rawObservation, options={}) {
    const observation = validateObservation(rawObservation);
    const now=new Date().toISOString(), version=buildVersion();
    const run={ id:randomUUID(), subject_id:observation.subject_id, dataset:observation.dataset, checkpoint:observation.checkpoint,
      status:'running', branch_kind:options.branch_kind || 'formal', seed:options.seed ?? 42,
      config:{...this.config, model:this.gateway.publicConfig()}, version, created_at:now, updated_at:now };
    this.store.createRun(run); let ordinal=0; const traces=[];
    const step=(component,input,output,status='completed',gateway=null,error=null)=>{
      const trace={ordinal:ordinal++,component,description:DESCRIPTIONS[component] || `${component} typed updater`,status,input,output,diff:diff(input,output),gateway,error};
      traces.push(trace); this.store.saveTrace(run.id,trace); return output;
    };
    try {
      step('raw_observation',{},observation);
      const packet=step('input_packetizer',observation,{...observation,packetized:true,external_source_boundary:observation.source_type});
      const extracted=await this.gateway.completeJSON('extractor',packet,x=>x.map(validateEvidence),()=>extractEvidence(packet));
      const evidence=step('atomic_evidence_extractor',packet,extracted.value,'completed',extracted.trace);
      const linked=step('entity_relation_linker',evidence,linkEvidence(evidence));
      const routedResult=await this.gateway.completeJSON('router',linked,validateRoutes,()=>routeEvidence(linked,observation));
      const routes=step('multi_label_router',linked,routedResult.value,'completed',routedResult.trace);
      const historical=this.store.statesFor(observation.subject_id);
      const built=[]; const deltas=[];
      for (const family of STATE_FAMILIES) {
        const result=updateFamily(family,routes.filter(x=>x.families.some(f=>f.family===family)),historical,built,observation);
        result.states.forEach(validateState); result.deltas.forEach(validateStateDelta); built.push(...result.states); deltas.push(...result.deltas);
        step(`updater_${family.toLowerCase()}`,{family:FAMILY_NAMES[family],routes:routes.filter(x=>x.families.some(f=>f.family===family)),candidates:historical.filter(x=>x.family===family)},result);
      }
      const relations=buildRelations(routes,built).map(validateRelation);
      const reconciled=step('temporal_reconciler',{historical,new_states:built},reconcile([...historical,...built],observation));
      const validity=step('state_validity',reconciled,validityCheck(reconciled,observation));
      const g1Result=await this.gateway.completeJSON('g1',{states:validity.usable_states,evidence},x=>validateGateTrace(x,'G1'),()=>gate1(validity.usable_states,evidence));
      const g1=step('gate_1',{families:['PE','CS','LO','CP'],states:validity.usable_states.filter(x=>['PE','CS','LO','CP'].includes(x.family))},g1Result.value,'completed',g1Result.trace);
      const g2Result=await this.gateway.completeJSON('g2',{states:validity.usable_states,observation,validity},x=>validateGateTrace(x,'G2'),()=>gate2(validity,observation));
      const g2=step('gate_2',{depends_on:'G1',g1_constraints:g1.output,validity},g2Result.value,'completed',g2Result.trace);
      const g3Result=await this.gateway.completeJSON('g3',{states:validity.usable_states,g1,g2},x=>validateGateTrace(x,'G3'),()=>gate3(validity.usable_states,g1,g2));
      const g3=step('gate_3',{depends_on:['G1','G2'],safe_action_set:g1.output.safe_action_set,sufficient_to_act:g2.output.sufficient_to_act},g3Result.value,'completed',g3Result.trace);
      const action=step('action_policy',{g1:g1.output,g2:g2.output,g3:g3.output},policy(g1,g2,g3)); validateAction(action);
      const genResult=await this.gateway.completeJSON('generator',{action,allowed_evidence:evidence.filter(e=>action.required_evidence_ids.includes(e.evidence_id))},validateGenerated,()=>generate(action));
      const generated=step('response_generator',{action,constraints:{required:action.required_content,forbidden:action.forbidden_content}},genResult.value,'completed',genResult.trace);
      const auditResult=await this.gateway.completeJSON('auditor',{action,generated,g1,g2,g3,validity},validateAudit,()=>audit(action,generated,g1,g2,g3));
      const audited=step('response_auditor',{action,generated},auditResult.value,auditResult.value.passed?'completed':'failed',auditResult.trace);
      if (!audited.passed) throw Object.assign(new Error('Response blocked by Auditor'),{publicError:{step:'response_auditor',input:{action,generated},raw_model_output:auditResult.trace.raw_model_response,parsed_output:audited,suggestion:'Review each violation, then rerun the Generator or adjust the upstream Gate.'}});
      const final={observation,evidence,states:built,deltas,relations,validity,gates:{g1,g2,g3},action,response:generated.response,audit:audited,version,mock:this.gateway.config.provider==='mock'};
      step('commit_feedback',{audit:audited,branch_kind:run.branch_kind},{committed:run.branch_kind==='formal',reason:run.branch_kind==='formal'?'Auditor passed; transaction committed.':'Debug branch is isolated and did not alter formal state.'});
      if(run.branch_kind==='formal') this.store.commitPipeline(run.id,observation,evidence,built,relations,final);
      else this.store.db.prepare(`UPDATE runs SET status='completed',final_json=?,updated_at=? WHERE id=?`).run(JSON.stringify(final),new Date().toISOString(),run.id);
      return {...run,status:'completed',traces,final};
    } catch(error) {
      const publicError=error.publicError || error.gatewayTrace ? { step:error.gatewayTrace?.component || 'pipeline', input:error.gatewayTrace?.input || rawObservation,
        raw_model_output:error.gatewayTrace?.raw_model_response || '', parsed_output:error.gatewayTrace?.parsed_response || null,
        validation_errors:error.gatewayTrace?.error?.validation_errors || [], message:String(error.message), suggestion:error.gatewayTrace?.error?.suggestion || 'Inspect this step input/output, correct the data or model configuration, then rerun.' } :
        {step:'pipeline',input:rawObservation,raw_model_output:'',parsed_output:null,message:String(error.message),suggestion:'Inspect the last completed trace and retry from that step.'};
      this.store.failRun(run.id,publicError); throw Object.assign(error,{run_id:run.id,publicError});
    }
  }
}

function extractEvidence(o) {
  const segments=[]; const re=/[^。！？!?;；\n]+[。！？!?;；]?/g; let match;
  while((match=re.exec(o.raw_text))) { const text=match[0].trim(); if(!text) continue; const parts=text.split(/(?:，|,|\band\b|而且|并且|所以|because|but|但是)/i).map(x=>x.trim()).filter(x=>x.length>1);
    let cursor=match.index; for(const part of parts){const start=o.raw_text.indexOf(part,cursor); cursor=Math.max(start+part.length,cursor); segments.push({text:part,start:Math.max(0,start),end:Math.max(0,start)+part.length});} }
  return segments.map(s=>validateEvidence({evidence_id:randomUUID(),observation_id:o.observation_id,subject_id:o.subject_id,text:s.text,span:[s.start,s.end],source_type:o.source_type,speaker:o.speaker,episode_id:o.episode_id,turn_id:o.turn_id,event_time:o.event_time,record_time:o.record_time,certainty:/可能|也许|maybe|might|不确定/i.test(s.text)?.55:1,polarity:/没有|否认|未|not |no /i.test(s.text)?'negated':/可能|也许|maybe|might/i.test(s.text)?'uncertain':'affirmed',derived:false}));
}

function linkEvidence(evidence) { return evidence.map(e=>({...e,normalized_entity:entityFor(e.text),numbers:[...e.text.matchAll(/(\d+(?:\.\d+)?)\s*(mg\/g|mg\/dL|mmol\/L|分|%|次)?/gi)].map(m=>({value:+m[1],unit:m[2]||null})),relation_hints:/因为|所以|because/i.test(e.text)?['causes']:[]})); }
function entityFor(text) { const rules=[['self_harm',/自伤|自杀|轻生|self[- ]?harm|suicid/i],['insulin',/胰岛素|insulin/i],['medication',/药|medication|medicine|Prilosec|sertraline/i],['anxiety',/焦虑|紧张|anxi|on edge/i],['sleep',/睡眠|失眠|sleep/i],['glucose',/血糖|glucose/i],['UACR',/UACR/i],['copay',/copay|付不起|afford|费用|保险/i],['goal',/目标|希望|想要|goal|hope/i],['safety_plan',/安全计划|联系人|预警信号|safety plan|warning sign/i],['risk_assessment',/风险等级|高风险|中风险|低风险|risk level/i],['plan',/计划|作业|下次|follow.?up|homework|plan/i]]; return rules.find(([,r])=>r.test(text))?.[0] || text.replace(/[\s\p{P}]/gu,'').slice(0,28).toLowerCase(); }

function validateRoutes(value){if(!Array.isArray(value)) throw new Error('routes must be an array'); for(const r of value){if(!r.evidence_id||!Array.isArray(r.families))throw new Error('invalid route'); if(r.families.some(x=>!STATE_FAMILIES.includes(x.family)))throw new Error('invalid route family');}return value;}
function routeEvidence(evidence,o){return evidence.map(e=>{const t=e.text; const f=[]; const add=(family,subtype,reason)=>{if(!f.some(x=>x.family===family&&x.subtype===subtype))f.push({family,subtype,reason});};
  if(/copay|付不起|afford|费用|保险|家庭|父母|学校|工作|住房|交通/i.test(t))add('BC',/copay|付不起|afford|费用|保险|交通/i.test(t)?'resource_constraint':'social_context','Context or resource is directly stated.');
  if(o.source_type==='patient' && /症状|疼|恶心|焦虑|紧张|抑郁|睡|血糖|服|停|漏|自伤|自杀|轻生|symptom|pain|nause|anxi|depress|sleep|taking|stopped|missed|self[- ]?harm|suicid/i.test(t))add('PE',/自伤|自杀|轻生|self[- ]?harm|suicid/i.test(t)?'safety_disclosure':/服|停|漏|taking|stopped|missed/i.test(t)?'adherence':'symptom','Patient experience/report remains patient-sourced.');
  if(o.source_type==='patient'&&/认为|担心|希望|目标|想|偏好|觉得|think|believe|worr|hope|want|prefer/i.test(t))add('PA',/希望|目标|想要|hope|goal|want/i.test(t)?'goal':'belief','Patient appraisal is explicitly stated.');
  if((o.source_type==='doctor'||o.source_type==='structured')&&/诊断|检查|数值|风险|药|过敏|禁忌|血糖|UACR|diagnos|test|risk|medication|allerg|contra|glucose|insulin/i.test(t))add('CS',/风险|risk/i.test(t)?'risk_assessment':/过敏|allerg|禁忌|contra/i.test(t)?'contraindication':/\d/.test(t)?'test_result':'clinical_fact','Clinical/structured source supports safety state.');
  if(o.source_type==='doctor'&&/建议|计划|作业|随访|联系|预警|急诊|安全|recommend|plan|homework|follow.?up|contact|warning|emergency/i.test(t))add('CP',/安全|预警|联系|急诊|safety|warning|contact|emergency/i.test(t)?'safety_plan':'care_plan','Doctor action or care process is explicitly stated.');
  if(/改善|恶化|缓解|复发|变得|下降|升高|比|helped|worse|better|improv|decreas|increas|again/i.test(t))add('LO','change_report','Change is explicitly reported; computed comparisons require compatible snapshots.');
  return {...e,families:f.length?f:[{family:o.source_type==='doctor'?'CP':o.source_type==='structured'?'BC':'PE',subtype:'other',reason:'Preserve otherwise uncategorized real observation.'}]};});}

function updateFamily(family,routes,historical,built,o){const states=[],deltas=[]; for(const r of routes){for(const route of r.families.filter(x=>x.family===family)){const candidates=[...historical,...built].filter(x=>x.family===family&&x.entity===r.normalized_entity); const prior=candidates.at(-1); let operation='ADD',reason='No matching prior state; append a new version.';
    const correction=/纠正|更正|不是.*而是|actually|correction/i.test(r.text); if(prior){ if(correction&&prior.source_type===r.source_type){operation='SUPERSEDE';reason='The same source explicitly corrected its earlier statement.';} else if(prior.source_type!==r.source_type&&opposite(prior.value,r.text)){operation='CONFLICT';reason='Different sources provide incompatible current claims; both remain visible.';} else if(hasNumber(prior.value)&&hasNumber(r.text)){operation='ADD';reason='A new measurement is a new timepoint; the old value is retained.';} else {operation='UPDATE';reason='A matching entity has a new longitudinal observation.';} }
    const state={state_id:randomUUID(),subject_id:o.subject_id,family,subtype:route.subtype,entity:r.normalized_entity,value:r.text,status:operation==='CONFLICT'?'conflict':'active',source_type:r.source_type,speaker:r.speaker,event_time:r.event_time,record_time:r.record_time,episode_id:r.episode_id,turn_id:r.turn_id,certainty:r.certainty,polarity:r.polarity,evidence_ids:[r.evidence_id],relations:[],version:(prior?.version||0)+1,version_chain:[...(prior?.version_chain||[]),...(prior?[prior.state_id]:[])],supersedes:operation==='SUPERSEDE'?prior.state_id:null,conflicts_with:operation==='CONFLICT'?prior.state_id:null,operation,operation_reason:reason,derived_from:[]}; states.push(state); deltas.push({operation,family,state_id:state.state_id,prior_state_id:prior?.state_id||null,evidence_id:r.evidence_id,reason});
    if(hasNumber(prior?.value)&&hasNumber(r.text)&&family!=='LO'){const lo={...state,state_id:randomUUID(),family:'LO',subtype:'computed_change',entity:`${r.normalized_entity}_change`,value:`${prior.value} → ${r.text}`,version:1,version_chain:[],evidence_ids:[...prior.evidence_ids,r.evidence_id],operation:'ADD',operation_reason:'Two comparable timepoint snapshots retained; LO references before and after.'};states.push(lo);deltas.push({operation:'ADD',family:'LO',state_id:lo.state_id,prior_state_id:null,evidence_id:r.evidence_id,reason:lo.operation_reason});}
  }} return {states,deltas};}
function hasNumber(x){return /\d/.test(String(x||''));} function opposite(a,b){return /(stop|停|未|没有|否认|not|no )/i.test(a)!==/(stop|停|未|没有|否认|not|no )/i.test(b);}
function buildRelations(routes,states){const out=[]; for(const r of routes){const linked=states.filter(s=>s.evidence_ids.includes(r.evidence_id)); for(let i=0;i<linked.length;i++)for(let k=i+1;k<linked.length;k++)out.push({relation_id:randomUUID(),type:r.relation_hints[0]||'co_supported_by',source_id:linked[i].state_id,target_id:linked[k].state_id,evidence_ids:[r.evidence_id]});}return out;}
function reconcile(states,o){const current=states.filter(s=>!s.superseded_by); const future=[],usable=[]; for(const s of current){const futureCheckpoint=s.checkpoint!=null&&o.checkpoint!=null&&Number(s.checkpoint)>Number(o.checkpoint); const futureEpisode=numericEpisode(s.episode_id)>numericEpisode(o.episode_id); const futureTime=s.event_time&&o.event_time&&Date.parse(s.event_time)>Date.parse(o.event_time); if(futureCheckpoint||futureEpisode||futureTime)future.push({...s,exclusion_reason:'Future session/admission/time'});else usable.push(s);} return {all_states:states,usable_candidates:usable,future_excluded:future,conflicts:usable.filter(s=>s.status==='conflict')};}
function numericEpisode(x){const m=String(x||'').match(/\d+/);return m?+m[0]:0;}
function validityCheck(rec,o){const warnings=[]; if(rec.future_excluded.length)warnings.push({type:'temporal',state_ids:rec.future_excluded.map(x=>x.state_id),message:'Future evidence excluded.'}); if(rec.conflicts.length)warnings.push({type:'conflict',state_ids:rec.conflicts.map(x=>x.state_id),message:'Unresolved cross-source conflict requires verification.'}); const derived=rec.usable_candidates.filter(s=>s.source_type==='derived'&&!s.derived_from?.length); if(derived.length)warnings.push({type:'provenance',state_ids:derived.map(x=>x.state_id),message:'Ungrounded Derived state excluded.'}); const usable=rec.usable_candidates.filter(s=>!derived.includes(s)); return {valid:true,checkpoint:o.checkpoint,usable_states:usable,excluded_states:[...rec.future_excluded,...derived],warnings,coverage:{has_patient_experience:usable.some(s=>s.family==='PE'),has_clinical_safety:usable.some(s=>s.family==='CS'),has_goal:usable.some(s=>s.family==='PA')}};}

function gate1(states,evidence){const pe=states.filter(s=>s.family==='PE'),cs=states.filter(s=>s.family==='CS'),cp=states.filter(s=>s.family==='CP'); const selfHarm=pe.filter(s=>s.subtype==='safety_disclosure'&&s.polarity!=='negated'); const professionalRisk=cs.filter(s=>s.subtype==='risk_assessment'); const red=states.filter(s=>/急诊|高风险|过敏|禁忌|呼吸困难|胸痛|self[- ]?harm|suicid|自伤|自杀|轻生/i.test(s.value)); const must=selfHarm.length>0||professionalRisk.some(s=>/高|high|imminent/i.test(s.value)); const ids=[...new Set([...pe,...cs,...cp].flatMap(s=>s.evidence_ids))]; return {gate:'G1',evidence_ids:ids,state_ids:[...pe,...cs,...cp].map(s=>s.state_id),output:{clinical_status:professionalRisk.length?'Professional assessment available':selfHarm.length?'Patient safety disclosure present; no professional risk level inferred':'No acute professional risk assessment in visible State',risk_level:professionalRisk.at(-1)?.value||'not professionally assessed',red_flags:red.map(s=>s.value),safe_action_set:must?['ESCALATE','ASK_SAFETY_DETAILS','SUPPORT']:['ANSWER','ASK','VERIFY','EDUCATE','PLAN','MONITOR'],forbidden_actions:must?['ROUTINE_ANSWER','DISMISS_RISK','LEAVE_ALONE']:red.some(s=>/过敏|禁忌|allerg|contra/i.test(s.value))?['USE_CONTRAINDICATED_OPTION']:[],required_monitoring:selfHarm.length?['intent','plan','means','immediacy','support_contact']:[],must_escalate:must},constraints:{patient_disclosure_is_not_risk_level:selfHarm.length>0&&professionalRisk.length===0}};}
function gate2(validity,o){const conflicts=validity.warnings.filter(x=>x.type==='conflict'); const ambiguity=validity.warnings.filter(x=>x.type==='temporal'); const uncertain=/不确定|可能|maybe|might|不清楚/i.test(o.raw_text); const question=/[?？]/.test(o.raw_text); const missing=[]; if(uncertain)missing.push('Clarify the uncertain claim with its source and time.'); const sufficient=!conflicts.length&&!ambiguity.length&&!uncertain; return {gate:'G2',evidence_ids:validity.usable_states.flatMap(s=>s.evidence_ids),state_ids:validity.usable_states.map(s=>s.state_id),output:{belief_gap:uncertain?['Current belief is uncertain against available evidence.']:[],missing_information:missing,source_conflicts:conflicts.flatMap(x=>x.state_ids),temporal_ambiguity:ambiguity.flatMap(x=>x.state_ids),verification_targets:[...conflicts,...ambiguity].flatMap(x=>x.state_ids),required_questions:missing,education_target:question&&sufficient?'Explain only from grounded visible evidence.':null,sufficient_to_act:sufficient}};}
function gate3(states,g1,g2){const pa=states.filter(s=>s.family==='PA'),bc=states.filter(s=>s.family==='BC'),cp=states.filter(s=>s.family==='CP'),lo=states.filter(s=>s.family==='LO'); const allowed=g1.output.safe_action_set; const candidates=['ANSWER','ASK','VERIFY','EDUCATE','PLAN','MONITOR','ESCALATE'].filter(x=>allowed.includes(x)); const feasible=g2.output.sufficient_to_act?candidates:candidates.filter(x=>['ASK','VERIFY','ESCALATE'].includes(x)); return {gate:'G3',evidence_ids:[...pa,...bc,...cp,...lo].flatMap(s=>s.evidence_ids),state_ids:[...pa,...bc,...cp,...lo].map(s=>s.state_id),output:{active_goal:pa.filter(s=>s.subtype==='goal').at(-1)?.value||null,applicable_preferences:pa.filter(s=>s.subtype!=='goal').map(s=>s.value),resource_constraints:bc.filter(s=>s.subtype==='resource_constraint').map(s=>s.value),prior_plan_status:cp.at(-1)?.status||null,prior_outcome:lo.at(-1)?.value||null,feasible_set:feasible,ranked_options:feasible,next_step:feasible[0]||null,implementation_support:bc.filter(s=>s.subtype==='resource_constraint').length?'Adapt timing/cost without weakening G1 safety.':null,rejected_by_g1:['ROUTINE_ANSWER','DISMISS_RISK','USE_CONTRAINDICATED_OPTION'].filter(x=>g1.output.forbidden_actions.includes(x)),blocked_by_g2:!g2.output.sufficient_to_act}};}
function policy(g1,g2,g3){let type,why; if(g1.output.must_escalate){type='ESCALATE';why='Gate 1 detected a mandatory safety escalation; later Gates cannot cancel it.';} else if(g2.output.source_conflicts.length||g2.output.temporal_ambiguity.length){type='VERIFY';why='Gate 2 found a source conflict or temporal ambiguity.';} else if(!g2.output.sufficient_to_act){type='ASK';why='Gate 2 says available information is insufficient to act.';} else if(g2.output.education_target){type='EDUCATE';why='Gate 2 identified a grounded education target.';} else if(!g3.output.feasible_set.length){type='ASK';why='Gate 3 found no feasible option within earlier constraints.';} else {type='ANSWER';why='All Gates permit a grounded response within the feasible safe set.';} return {type,explanation:why,required_evidence_ids:[...new Set([...(g1.evidence_ids||[]),...(g2.evidence_ids||[]),...(g3.evidence_ids||[])])],required_content:type==='ESCALATE'?['明确建议立即联系当地急救/危机支持或可信任的人','直接询问当前安全、计划与手段可及性']:type==='ASK'?g2.output.required_questions:['仅使用可追溯证据'],forbidden_content:[...g1.output.forbidden_actions,'编造诊断','泄露密钥']};}
function validateGenerated(x){if(!x||typeof x.response!=='string'||!x.response.trim())throw new Error('generated response required');if(!x.action_type)throw new Error('action_type required');return x;}
function generate(action){const response={ESCALATE:'你现在的安全最重要。请立即联系当地急救或危机支持，并尽快让一位可信任的人陪在你身边。你现在是否安全？是否有具体计划、可用手段或马上行动的可能？',VERIFY:'现有记录之间有冲突或时间不清，先核对来源和发生时间后再决定会更安全。',ASK:`在继续前需要补充：${action.required_content.join('；')||'关键事实、来源和时间。'}`,EDUCATE:'根据当前可追溯信息，我可以先解释已确认部分，同时明确未知之处。',ANSWER:'根据当前可追溯信息，可以在安全边界内继续；建议按既有计划执行并观察真实反馈。',REFUSE:'这个请求超出安全范围，我不能协助。'}[action.type];return {action_type:action.type,response,citations:action.required_evidence_ids};}
function validateAudit(x){if(typeof x?.passed!=='boolean'||!Array.isArray(x?.violations))throw new Error('invalid AuditResult');return x;}
function audit(action,g,g1,g2,g3){const v=[];if(g.action_type!==action.type)v.push('Generator changed the Action Policy decision.');for(const x of action.forbidden_content)if(x&&g.response.includes(x))v.push(`Response includes forbidden content: ${x}`);if(action.type==='ESCALATE'&&!/急救|危机|emergency|crisis/i.test(g.response))v.push('Mandatory escalation language is missing.');if(!g1.output.safe_action_set.includes(action.type)&&!(action.type==='ASK'&&g1.output.safe_action_set.includes('ASK_SAFETY_DETAILS')))v.push('Action is outside Gate 1 safe set.');if(!g2.output.sufficient_to_act&&action.type==='ANSWER')v.push('Direct ANSWER is forbidden when Gate 2 is insufficient.');if(g3.output.rejected_by_g1.includes(action.type))v.push('Gate 3 reused an option forbidden by Gate 1.');return {passed:v.length===0,violations:v,grounded_evidence_ids:g.citations||[],blocked_response:v.length?g.response:null,safe_response:v.length?'系统已阻止不符合 Gate 的回复。':g.response};}
function diff(a,b){const aa=JSON.stringify(a),bb=JSON.stringify(b);return {changed:aa!==bb,input_bytes:aa.length,output_bytes:bb.length,summary:aa===bb?'No structured change.':'Output produced or transformed fields; inspect raw JSON for exact values.'};}
